### ISSUE TITLE
Post analysis visual style needed.

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#1]
There is no access from the visual mapper to the edge colour/node color/node shape of the post analysis edges so people can't customize it. (post analysis visual style mapping is done through visual mapper bypass instead of creating or modifying existing visual style.)

Need to put it into the EM visual style or create a new visual style (clone original and add new details to it)

**Comment by mikekucera** [comment]
Fixed in pa_merge
