### ISSUE TITLE
Issue running post analysis after deleting nodes in the network 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#100]
[Run on Windows with cytoscape 3.2.1, EM revision r5a6539d

Run Post analysis using known signature, hypergeometric p-value, against the whole network

Delete PA node and all its edges

Delete all up-regulated genesets in the network (select -> EM1_NES_dataset1 value between 0-10 -> Delete all selected nodes and edges)

Re run post analysis with the same thresholds 

![image](https://cloud.githubusercontent.com/assets/3842763/7942130/0d4e46c6-092a-11e5-9316-985db6083746.png)

Stack:

java.lang.IllegalArgumentException: target node is not a member of this network
        at org.cytoscape.model.internal.SimpleNetwork.addEdgeInternal(SimpleNetw
ork.java:291)
        at org.cytoscape.model.internal.CyRootNetworkImpl.addEdge(CyRootNetworkI
mpl.java:254)
        at org.cytoscape.model.internal.CySubNetworkImpl.addEdge(CySubNetworkImp
l.java:149)
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.c
reateEdge(BuildDiseaseSignatureTask.java:491)
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.b
uildDiseaseSignature(BuildDiseaseSignatureTask.java:389)
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.r
un(BuildDiseaseSignatureTask.java:664)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:321)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
The problem is that the GenesetSimilarity objects for the deleted nodes still exist in memory. I think I have to listen for the node delete event and remove the corresponding GenesetSimilarity objects. I hope that doesn't cause problems elsewhere in the codebase.

**Comment by risserlin** [comment]
When the sliders in the right hand panel are moved nodes and edges get removed/added depending on direction.  I am not sure if they get hidden or deleted as we had different issues with various versions of cytoscape so in some versions we deleted these nodes and edges and then readded them and in other version we hid and unhid them.

We need to calculate post analysis edges to hidden nodes but they should be hidden similar to the node.  Not sure if that is the right way it should work.  I will check with veronique.

**Comment by mikekucera** [comment]
Its less risky to just check for the existence of the node before creating the edge. I don't want to break something else.
