### ISSUE TITLE
About dialog says 'null' in a few places

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#103]

**Comment by risserlin** [comment]
What are you missing?  There are no null values with the version I built.  Probably because of un-versioned file.

**Comment by mikekucera** [comment]
![screen shot 2015-06-09 at 10 52 53 am](https://cloud.githubusercontent.com/assets/5350528/8062088/e6951902-0e9b-11e5-84a4-f708d5ff8610.png)

That's what I see.
And in the code it looks like the fields in EnrichmentMapUtils are not being initialized.
Should be easy to fix.

**Comment by risserlin** [comment]
You removed this line from the CyActivator class: 

//Initialize Enrichment Map parametres
EnrichmentMapUtils utils = new EnrichmentMapUtils("");

in revision:
(https://github.com/BaderLab/EnrichmentMapApp/commit/5ae0f53068971ecc8893d36305cadf91c64d35bd#diff-eb545baa1127d788e13bfd3110fe0029)

which initializes those variables and also handles the version that is specifically for gsea (still uses 2.8) but will hopefully move to 3 very soon so we can hopefully get rid of this class soon.

Adding it back should fix part of the above.  the bottom line comes from build.properties file which is not versioned but not sure if the build will automatically create  it if it isn't there.
