### ISSUE TITLE
Some post-analysis edges are black

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#107]

**Comment by mikekucera** [comment]
This one was fun to track down...

Its caused by a problem with the strategy that cytoscape uses to fire payload events. 
- A payload event fires (RowsSetEvent)
- UpdateHeatMapTask responds to the RowsSetEvent and tries to focus the heat map panel
- That causes a normal event to fire
- The first line of EventHelperImpl.fireEvent() calls flushPayloadEvents()
- A payload event fires (RowsSetEvent)
- UpdateHeatMapTask responds to the RowsSetEvent...

And so on. It loops until there are no more payload events, causing a storm of small payload events and other events (which defeats the purpose of payload events).

This is getting in the way of the visual property events, causing a race condition, which causes some of the edges to be black.

I will need to discuss with the cytoscape team how to deal with the underlying problem. In the meantime I have implemented a workaround which prevents UpdateHeatMapTask from looping.

**Comment by drseamonster** [comment]
Hi just wonder have this problem being fixed in Enrichment Map v2.1.0 with Cytoscape 3.3.0.
The edges for the first geneset calculated for post analysis are all pink, but after deleted the first one, all subsequent ones have grey edges.

**Comment by mikekucera** [comment]
Have you tried resetting the visual style?

**Comment by drseamonster** [comment]
No, I have not, let me try

Jeff

**Comment by drseamonster** [comment]
Hi Mike

Yes, reset the style will fix it, thank you. Cheers

Jeff
