### ISSUE TITLE
Issue with edge creation in 2 distinct dataset EM

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#114]
Incorrect edges are being created in the 2 distinct dataset build:

Example:
![example_bug_2dataset](https://cloud.githubusercontent.com/assets/3842763/8755201/0d47ec5a-2c97-11e5-89d2-188022541713.png)

highlighted nodes are only significant in dataset2.
Remaining node is significant in both dataset1 and dataset2.  
There should not be green edges to the highlighted nodes from the non-highlighted node.

**Comment by mikekucera** [comment]
Hi Ruth, can you provide me with your session file please?

**Comment by mikekucera** [comment]
I think this is fixed.
