### ISSUE TITLE
for GSEA results we need a way to visualize the FDR in addtion to the pvalue

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#115]
For datasets where the only difference is the GSEA FDR it would be useful to be able to visualize it in addition to the p-value.  (don't necessarily want to replace the p-value with the FDR)

**Comment by mikekucera** [comment]
I believe this is supported in EM 3, there are chart options for both p-value and FDR. Please reopen if I am mistaken.
