### ISSUE TITLE
Flip rank order arrow click doesn't work

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#118]
In the heatmap the flip rank order doesn't work.  It also defaults to smallest to largest even for genesets that are downregulated.  (should to largest to smallest for downregulated and smallest to largest for upregulated by default)
![screen shot 2015-07-29 at 9 27 22 am](https://cloud.githubusercontent.com/assets/3842763/8958637/0dbd9900-35d4-11e5-86b8-fa85a5132250.png)

**Comment by mikekucera** [comment]
It seems to be working for me. Do you have a session file where it doesn't work?

**Comment by risserlin** [comment]
Seems to be working for me as well.
