### ISSUE TITLE
Deadlock sometimes when using search bar

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#120]
When using the search bar to search the network and there are a lot of results that match the search and EM question whether to hierarchical cluster dead locks.

**Comment by mikekucera** [comment]
same problem as #108?

**Comment by risserlin** [comment]
Yes.  Is this one of those that will get fixed in cytoscape 3.3?

**Comment by mikekucera** [comment]
Yes this should get fixed in 3.3.

**Comment by mikekucera** [comment]
I have diagnosed the underlying problem in Cytoscape. The bug report is here: https://code.cytoscape.org/redmine/issues/3370.

Since this won't get fixed until 3.4 in the meantime we need to find a workaround for EM.
