### ISSUE TITLE
a few observations (bugs ans enhancements): built 535

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#123]
please find below a few observations regarding EM that I gathered last week while working on it in case it helps.  It was built 535 of EM on Cytoscape 3.2.1

BUG: "Continuous Mapping Editor for Node Size": "Selected Handle Position" box does not work properly + wrong handle positions selected on a click 

BUG: although I have selected No sort in Default Sorting Order (advanced parameter), cytoscape tried to sort nodes sometimes when I click on the map (not sure what I.m doing to activate it): "The combination of the selected nodes contains more than 1000 genes...."

BUG: saved my session after rearranging nodes (no label annotation) : the stored session had lost the expression panel; restored it by unzipping the file and pasting the EnrichmentMap folder in App from original session that was not broken

ENHANCEMENT: new layout (prefused)  when removed nodes using q value slide bar:  better but not perfect: sparse nodes (they were too far apart and I needed to move them closer manually)

ENHANCEMENT: release 535 soon in the app manager as despite the report bugs, it is much better than the current version that is available?

**Comment by mikekucera** [comment]
Fixed these
