### ISSUE TITLE
ENHANCEMENT: post-analysis: is it possible to implement 1 sided withney test (2 sides)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#124]
ENHANCEMENT: post-analysis: is it possible to implement 1 sided withney test (2 sides)
built 535

**Comment by risserlin** [comment]
in order to implement one-sided test need to modify calculateAsyptoticPValue function in MannWhitneyUtest class:

if two.sided
return 2 \* standardNormal.cumulativeProbability(z);
if(greater)
return standardNormal.cumulativeProbability(z);
if(lesser)
return 1 - standardNormal.cumulativeProbability(z);

**Comment by veroniquevoisin** [comment]
Hi Ruth,
please let me know as soon as it is available in a development version!
Thanks
Veronique

On Mon, Nov 23, 2015 at 3:56 PM, Ruth Isserlin notifications@github.com
wrote:

> in order to implement one-sided test need to modify
> calculateAsyptoticPValue function in MannWhitneyUtest class:
> 
> if two.sided
> return 2 \* standardNormal.cumulativeProbability(z);
> if(greater)
> return standardNormal.cumulativeProbability(z);
> if(lesser)
> return 1 - standardNormal.cumulativeProbability(z);
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BaderLab/EnrichmentMapApp/issues/124#issuecomment-159061651
> .

## 

_Veronique Voisin, PhD_

Pathway and Network Analyses for OICR Cancer Stem Cell Research
Terrence Donnelly Centre for Cellular and Biomedical Research, University
of Toronto, 160 College Street, Toronto, M5S3E1.
_https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources
https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources_
http://baderlab.org/CSCPathwayAnalysisService
http://baderlab.org

**Comment by risserlin** [comment]
if('greater') 
    If (z > 0), 
      return  0.5_standardNormal.cumulativeProbability(z);. 
    else if z < or = 0, the 
     return  1 - 0.5_standardNormal.cumulativeProbability(z);.
if( 'less')
 If (z < 0), 
      return  0.5_standardNormal.cumulativeProbability(z);. 
    else if z > or = 0, the 
     return  1 - 0.5_standardNormal.cumulativeProbability(z);.
 if("two.sided)
   return 2 \* standardNormal.cumulativeProbability(z)

**Comment by mikekucera** [comment]
I just pushed a commit that provides this functionality. Please give it a try and let me know if there are any problems.

(Note: The column name for the two-sided test is still "Overlap_Mann_Whit_pVal". I kept it that way for backwards compatibility. The new columns are called "Overlap_Mann_Whit_greater_pVal" and "Overlap_Mann_Whit_less_pVal".)
