### ISSUE TITLE
Add "publication ready birds eye" toggle

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#134]
Add button to legend panel that:
deletes node label mapping (by stores what the mapping is so when they unselect option the EM label is returned to what it was previously)

Veronique, 
Should we also set background to white?  (Not sure if this is necessary).

**Comment by veroniquevoisin** [comment]
Hi Ruth,
not sure I'm following here:
you mean remove labels font when they want to export a map image?
yes,  setting the background to white is a good idea, better if there is
the option to do it or not
---------- Forwarded message ----------

**Comment by risserlin** [comment]
Yes I mean remove the labels.
They can always change the background color manually in the style tab just wondering if we should include it with the toggle to "publication ready" 

Checking the box next to "publication ready" would:
delete the labels
change background to white

Unchecking the box next to "publication ready" would
set labels to what they were previously
Change background back to what it was previously.

Or alternatively we can just have it:
Checking the box next to "publication ready" would:
delete the labels

Unchecking the box next to "publication ready" would
set labels to what they were previously

**Comment by veroniquevoisin** [comment]
yes, changing the background to white for publication ready is a good idea

On Fri, Oct 30, 2015 at 10:41 AM, Ruth Isserlin notifications@github.com
wrote:

> Yes I mean remove the labels.
> They can always change the background color manually in the style tab just
> wondering if we should include it with the toggle to "publication ready"
> 
> Checking the box next to "publication ready" would:
> delete the labels
> change background to white
> 
> Unchecking the box next to "publication ready" would
> set labels to what they were previously
> Change background back to what it was previously.
> 
> Or alternatively we can just have it:
> Checking the box next to "publication ready" would:
> delete the labels
> 
> Unchecking the box next to "publication ready" would
> set labels to what they were previously
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BaderLab/EnrichmentMapApp/issues/134#issuecomment-152543972
> .

## 

_Veronique Voisin, PhD_

Pathway and Network Analyses for OICR Cancer Stem Cell Research
Terrence Donnelly Centre for Cellular and Biomedical Research, University
of Toronto, 160 College Street, Toronto, M5S3E1.
_https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources
https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources_
http://baderlab.org/CSCPathwayAnalysisService
http://baderlab.org

**Comment by mikekucera** [comment]
I added the button to the results panel under the advanced preferences section.

It works by creating a copy of the current visual style, but with the labels blank and the background white. When the button is clicked again it switches back to the previous visual style.

Please let me know what you think.

**Comment by risserlin** [comment]
Hi Mike,  Thanks, This works very nicely.  
One addition though.  We don't want to delete the labels of post analysis edges.  I don't think this is easily fixed so people using this will have to bypass the names of the post analysis edges so they can seen in the export. (often there are only a few post analysis edges so not a big deal).
