### ISSUE TITLE
Modify hierarchical clustering threshold question so only asks user once

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#141]
If a user makes a selection with more than 1000 genes the question of whether to cluster comes up 4 times.  It would be good if we could reduce that to once.

**Comment by risserlin** [comment]
Explanation as to why there are 4 events from mike:
- node and edge selection are stored in tables and there are separate tables for nodes and edges
- selection is a payload event, and payload events fire essentially randomly, so a selection event is often broken into two parts

So the events are:
- first part of selected nodes
- rest of selected nodes
- first part of selected edges
- rest of selected edges

Its possible I could make the dialog a singleton, or there might be other work arounds

**Comment by mikekucera** [comment]
I reduced it to zero.
