### ISSUE TITLE
3 way comparison

### ISSUE THREAD

**Issue by wyim-pgl** [BaderLab/EnrichmentMapApp#147]
Dear EM,

We have 3 samples to analysis and is there anyway to use 3 Dataset for EM? 

it will be great to add 3 or 4 way comparison for input.

Thank you.

**Comment by risserlin** [comment]
We are working towards adding multi dataset support in the near future unfortunately not sure when it will get incorporated.  

I have done multi dataset analysis in the past though.  It involves filtering the three datasets by desired thresholds in R to generate a mock enrichment file.  A geneset is included if it is significant in at least one dataset.  
I create the EM with the mock enrichment file.
In R I create an additional file that contains the geneset name and p-value, FDR and NES for each geneset and each dataset.  I load this in as a node attribute and then use cytoscape charts to display the different enrichments by dataset. (NES works nicely for GSEA analyses)
I have R scripts that automate some of this process if you are interested. 

Thanks, 
Ruth

**Comment by mikekucera** [comment]
Implemented in EM3

**Comment by ternst23** [comment]
Was the cyrest implementation ever updated for this problem? 
Specifically, I am looking for a parameter like, getDataSet**3**Files.
(I would certainly like to be able to do 'n' number of files.)
Can this possibly be implemented as a list?

**Comment by mikekucera** [comment]
This was implemented in the 'enrichmentmap mastermap' command. But you don't specify each individual file path like with the old command, instead you give it the path to a folder that contains all the files and it automatically figures out which file is which. It usually works as expected with GSEA files. 

It uses the same heuristics as the create enrichmentmap dialog. You can test what its going to do by dragging the folder onto the create enrichmentmap dialog and checking each dataset's files. If it doesn't do the right thing then rename the files its getting wrong. Add 'enrichment', 'expression', or 'score' to the file name as needed to help it out.
