### ISSUE TITLE
Some nodes with no color

### ISSUE THREAD

**Issue by SethiyaPooja** [BaderLab/EnrichmentMapApp#148]
I am trying to perform enrichment analysis for two datasets but for some GO terms I am getting nodes with no color. While some nodes show a single color (RED). What does this mean?It can be visualised in the image attached.
![screenshot 2016-03-02_19-33-07](https://cloud.githubusercontent.com/assets/17592077/13459368/0522c01a-e0ae-11e5-8bce-9b04e1430c03.png)

**Comment by risserlin** [comment]
This is bug with the two dataset analysis.  The node size is dependent on dataset 1 and border width is dependent on dataset 2.  I have seen this issues before but I thought it was fixed.

What version of EM are you using?

It is either an issue with the max and min size of the node being set based on dataset1 when there are larger or smaller genesets in dataset2 so it falls outside the range.  You can fix this manually in the style tab (clicking on size mapping and changing the max and min)

Of it is an issue with that geneset not being found at all in dataset1 so it is lacking a node size.

**Comment by SethiyaPooja** [comment]
Thank you risserlin.

I am using EM version 2.1.0
And manually setting the node size is also  not solving the issue. 
Also, for "it is an issue with that geneset not being found at all in dataset1 so it is lacking a node size." 
If the geneset was not found in dataset1 then green edges would not have appeared, hence showing the overlapping Genes in the two datasets (for red nodes).

**Comment by mikekucera** [comment]
This bug does not apply to EM3 since we don't use border width anymore.
