### ISSUE TITLE
EnrichmentMapApp

### ISSUE THREAD

**Issue by potatotron** [BaderLab/EnrichmentMapApp#149]
I was following the tutorial for the g:profiler method found here: http://baderlab.org/Software/EnrichmentMap/GProfilerTutorial. At Step 2 #4 it says to simply select the "hsapiens.NAME.gmt" file.

Where does this file come from as it isn't in the tutorial zip file nor generated from the g:profiler website. 

Any help would be appreciated

**Comment by risserlin** [comment]
In the same tutorial in Step 1 #11 it shows you how to download the gmt file from the gprofiler website.  The gmt file is not included in the zip file because in the latest development version we no longer require it.
