### ISSUE TITLE
Clean up EM source tree

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#150]
Get rid of the following branches:
AutoAnnotate
AutoAnnotations
EM_project_pa
EMrefactor
HuAnnotation
pa_merge

Merge EM_Cyto3_port into master.

**Comment by mikekucera** [comment]
Hey, I actually did this without realizing there was a bug report for it.

I kept some of the older branches but renamed them to "feature/xxx". I created "release" branches for 1.3 and 2.1 for maintenance and bug fixes (ie 2.1.1). I renamed EM_Cyto3_port to "develop" (like the Cytoscape project uses) and that is the main branch for ongoing development.
