### ISSUE TITLE
Proposed interface change (by veronique)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#154]
replace "..." with "Load" next to every file input box.

Move expression box below Pos and Neg enrichment: [because people are often mistaking the expression field with the enrichment result field and also when we use the rpt to uload the files it loads the rank file in the expression field:  because people do the rpt after having loaded the expression, the rpt overwrites the expression field but they don’t notice

Change Enrichment1 and Enrichment 2 by POS and NEG so they don’t have to wonder which GSEA report should go where (although I know in reality it does not matter, but as a first users, we intuitively think that it matters)

Then  by  changing the Phenotype box with Pos and Neg, it may be more intuitive to know that it relates to the  GSEA reports and easier to explain. 

![image](https://cloud.githubusercontent.com/assets/3842763/14567339/98911a70-0301-11e6-9db7-11aa90ccfa73.png)

**Comment by risserlin** [comment]
Hi Veronique, 
I took the notes you made in the protocol and added it here.  Unfortunately this will not get done before the protocol goes out.  If we are going to change the interface I really think it would need a complete overhaul.  With multi-dataset feature the next up in the queue it would probably be a good time to revisit the interface in general. 
Thanks, 
Ruth

**Comment by veroniquevoisin** [comment]
Hi Ruth,
yes, that's fine. Thanks a lot!
Veronique

On Fri, Apr 15, 2016 at 12:03 PM, Ruth Isserlin notifications@github.com
wrote:

> Hi Veronique,
> I took the notes you made in the protocol and added it here. Unfortunately
> this will not get done before the protocol goes out. If we are going to
> change the interface I really think it would need a complete overhaul. With
> multi-dataset feature the next up in the queue it would probably be a good
> time to revisit the interface in general.
> Thanks,
> Ruth
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/BaderLab/EnrichmentMapApp/issues/154#issuecomment-210521556

## 

_Veronique Voisin, PhD_

Pathway and Network Analyses for OICR Cancer Stem Cell Research
Terrence Donnelly Centre for Cellular and Biomedical Research, University
of Toronto, 160 College Street, Toronto, M5S3E1.
_https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources
https://oicr.on.ca/oicr-programs-and-platforms/innovation-programs/cancer-stem-cells/resources_
http://baderlab.org/CSCPathwayAnalysisService
http://baderlab.org
