### ISSUE TITLE
reload stored session visual style does not get set to the right one

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#156]
open saved session
visual style is set to default style instead of EM1_visual_style. 

session attached as zip (just changed cys to zip) 
[Mesen_vs_Immuno_rnseq_formatted_v1.zip](https://github.com/BaderLab/EnrichmentMapApp/files/284873/Mesen_vs_Immuno_rnseq_formatted_v1.zip)

**Comment by risserlin** [comment]
cytoscape 3.4 with 2.1.0 EM released version

**Comment by mikekucera** [comment]
Sounds like the same bug that Shraddha reported.

Are you opening the session by double-clicking on the session file? There is a bug in 3.4 where the vizmapper doesn't get initialized properly when you do that. Christian already fixed it in 3.5. 

Can you please confirm that the bug goes away if you open Cytoscape first then open the session from File > Open menu?

**Comment by mikekucera** [comment]
Fixed in Cytoscape 3.5
