### ISSUE TITLE
not able to change Label Font Size

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#163]
EM v2.1.0 build 454 and Cytoscape 3.4.0:
unable to adjust label properties using Control Panel --> Style
e.g not able to change Label Font Size and Label Font Face

**Comment by veroniquevoisin** [comment]
it works with Cytoscape 3.3 but not 3.4
Because of this defect, it is not easy (impossible) to create a nice figure

**Comment by mikekucera** [comment]
Just created an EM and then try to set label font size... nothing happens.
Save session and reload, starts working as expected.

**Comment by veroniquevoisin** [comment]
I have created a map with Cytoscape 3.4 and I was not able to change the node size (node size set to NES values). It worked by first deleting the existing mapping and create a new one (Ruth tried but I haven't tried it on my computer).

**Comment by mikekucera** [comment]
I'm assuming this now works. Please reopen if needed.
