### ISSUE TITLE
EM throws error if rank or gct file have empty lines

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#167]
While helping a group create an EM kept getting error and unsuccessful build complaining of issues  parsing the expression file.  

It was a result of empty lines at the end of the expression or rank file.  If you deleted the blank rows EM was able to build but would be good to handle blank lines at the end of the file better.

**Comment by mikekucera** [comment]
Only happens for GSEA

**Comment by mikekucera** [comment]
I can't reproduce this. Expression and Rank files with blank lines load fine.

**Comment by mikekucera** [comment]
Cant reproduce this.
