### ISSUE TITLE
Enrichment Map gseabuild Cyrest command will not work if combinedconstant or expression file parameters are not defined

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#172]
Even through combinedconstant and expressionfile are optional parameters for gseabuild cyrest command if they are not specified cyrest will simply return - "Failed: source"

**Comment by mikekucera** [comment]
You were able to work around this by using the other command right?

**Comment by risserlin** [comment]
The command works as long as you specify the combined constant and expression file.  
(eventhough those are optional parameters). 
if the user doesn't specify them cyrest returns with a generic 500 Error "Failed"

Alternately you can use the build command and just specify the edb there as well.
