### ISSUE TITLE
heatmap - sorting direction arrow doesn't work

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#179]
![sorting arrow](https://cloud.githubusercontent.com/assets/3842763/23674709/d3b3b772-0344-11e7-97e4-9619b8e9db67.png)

**Comment by mikekucera** [comment]
This is already fixed in the 3.0 branch.

**Comment by risserlin** [comment]
Is the 3.0 branch useable?

**Comment by mikekucera** [comment]
We are planning to have an "alpha" for you to try this week.
