### ISSUE TITLE
Failed install of Enrichment Map from archive

### ISSUE THREAD

**Issue by eroberson** [BaderLab/EnrichmentMapApp#18]
Enrichment Map: EnrichmentMapPlugin_v2.0-Beta3.zip (v2.0 Beta build 367)
OS: Windows XP 64-bit
Cytoscape: v3.1.0 64-bit

Install from archive from app manager returns "No manifest was found in the jar file." Install fails.

**Comment by risserlin** [comment]
Try unzipping the file first. I think the jar is contained in the zip file.

**Comment by eroberson** [comment]
Blame that one on me. I did the unzip and install from file. But apparently more than once clicked on the wrong file. :\ Thanks!
