### ISSUE TITLE
Unable to delete labels in the enrichment map

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#180]
When you delete the labels it isn't refreshing the style so after you delete the labels nothing happens.

 As a work around right now you can get around this bug as follows:

delete the labels
Edit -> Remove Mapping from selected visual properties

Change the Style:
Change the style from EM1_Enrichment_map_style to default
and then
Change back from default to EM1_Enrichment_map_style

That should force the style to get refreshed and labels should be removed.

I am not sure if this is cytoscape issue or enrichment map issue.

**Comment by mikekucera** [comment]
This is fixed.
