### ISSUE TITLE
open existing session and create more network (via cyrest) and EM reused network numbers

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#182]
Opened an existing session and added enrichment maps to the existing session (from cyrest) and the new networks had the same network collection names and network names and style names to already existing networks.  

(all the network names in the original session had been changed, not sure if that is why the new networks are getting the wrong networks.)

![screen shot 2017-03-08 at 10 41 14 am](https://cloud.githubusercontent.com/assets/3842763/23710845/116d27fe-03ec-11e7-8da4-1b4fd29850ac.png)

**Comment by mikekucera** [comment]
This is working for me now. It must have been fixed at some point. If you see this problem again please reopen the bug.
