### ISSUE TITLE
post analysis edges empty after session re-load

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#183]
In initial session I was able to select a post analysis edge and see the contents in the heatmap.  On reload this doesn't work.  (only the post analysis edges don't work.

[Note - I have example in JD21 main session file]

Workaround - delete post analysis nodes and recalculate post analysis

**Comment by mikekucera** [comment]
Hi Ruth,

This is in 2.2?

**Comment by risserlin** [comment]
Yes
