### ISSUE TITLE
annotate genesets with gene names

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#186]
feature request from Stuart Lithwick:
Is there any simple way to print, as a feature on or beside an EnrichmentMap, the genes from a given
geneset that are included within the pathway that is being represented as a node, or even better the genes
that are shared between nodes?

Basically, I would like to display the gene names from the table panel as a feature directly on the EnrichmentMap itself
as a form of annotation, in addition to the annotations that have been added by AutoAnnotate.

**Comment by mikekucera** [comment]
You can change the Node Label mapping to use the EnrichmentMap::Genes column.
