### ISSUE TITLE
data input panel - file chooser does not remember the last folder I used

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#191]
When I create a new enrichment map and select a folder to use it always takes me to my home directory as opposed to going to the last directory I used.

**Comment by risserlin** [comment]
this bug is specific to the folder directory in the create enrichment map panel:
![image](https://cloud.githubusercontent.com/assets/3842763/25867559/e654152a-34c7-11e7-815e-390765a37c14.png)

In other places (for example add post analysis) the chooser gets the right directory

**Comment by mikekucera** [comment]
It always takes you to your home directory? Even after you select a folder to scan and it adds data sets to the list? Because I'm not seeing that behaviour, even on windows.

**Comment by risserlin** [comment]
Yes
