### ISSUE TITLE
Two data set analysis returning error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#192]
When I try and run a multi dataset analysis I keep getting an error that it can't find a particular geneset.  individually both datasets work but they don't work together.

![image](https://cloud.githubusercontent.com/assets/3842763/25866765/8164d9bc-34c5-11e7-8252-de6ac2a63653.png)

**Comment by mikekucera** [comment]
Can you send me the files please.

**Comment by risserlin** [comment]
related to this, when you have a few datasets it is hard to tell which dataset the error is coming from

**Comment by risserlin** [comment]
I think this is related to EM not finding specific files.  The GSEA analyses were done on different computers so any absolute paths in the rpt won't work.  (even when I make sure that the correct files are being used I get the above error though)

**Comment by mikekucera** [comment]
This works for me when I load the data sets using default parameters. What parameters are you using? Are you using the UI or a command?

**Comment by risserlin** [comment]
I was using the UI. From the folder of GSEA results that I sent yesterday try using all of them.

**Comment by mikekucera** [comment]
Thats what I did, it works. Maybe you need to show me tomorrow.

**Comment by risserlin** [comment]
Maybe it is a windows thing?  I'll try again from my computer at home.

**Comment by mikekucera** [comment]
I'll try in my windows vm.

**Comment by mikekucera** [comment]
This is a windows problem. I'm getting an exception from the WindowsPathParser class when I load the data sets.

**Comment by mikekucera** [comment]
So, on windows it can't resolve the GMT path from the RPT for two of the datasets. However, when I manually add those two GMT files it works. That's still different behaviour from what you originally reported (you say when you add all the files it still doesn't work). Can you confirm this on your windows machine please?

**Comment by mikekucera** [comment]
I think this is fixed. If you run into any more problems on windows please open a new bug.
