### ISSUE TITLE
cyrest commmand with analysisType="generic" does not use expression file that is specified

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#196]
http://localhost:1234/v1/commands/enrichmentmap/build?analysisType=generic&enrichmentsDataset1=%2FUsers%2Frisserlin%2FDropbox%20%28Personal%29%2FWorkFiles%2FSourcecode%2FCSCTeamCode%2FRottapel%2FRR01%2Fnotebooks%2Fresults%2Fcnvexp_sig_0.05_atleast_11_pat_minusoe_andcnv.txt&pvalue=1.0&qvalue=0.1&gmtFile=%2FUsers%2Frisserlin%2FDropbox%20%28Personal%29%2FWorkFiles%2FSourcecode%2FCSCTeamCode%2FRottapel%2FRR01%2Fnotebooks%2Fdata%2FHuman_GOBP_AllPathways_no_GO_iea_May_24_2016_symbol_moddiauresis.gmt&expressionDataset1=%2FUsers%2Frisserlin%2FDropbox%20%28Personal%29%2FWorkFiles%2FSourcecode%2FCSCTeamCode%2FRottapel%2FRR01%2Fnotebooks%2Fresults%2Fcnvexp_TCGA_cnvexp_all_minusoe_andcnv.txt&similaritycutoff=0.375&coeffecients=COMBINED

In beta1 : No error from the above command but em creates "dummy expression" set as opposed to using the one supplies

In 2.2.1 the network is created with the proper expression file.

**Comment by mikekucera** [comment]
Can you send me the files please.

**Comment by mikekucera** [comment]
Works for me.
