### ISSUE TITLE
Post analysis edges not visible

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#201]
In some respects the post analysis is more important than the enrichment map.  When an enrichment is huge and results are over whelming the post analysis is used to highlight a subsection of the network that is of specific interest.  With the current  visual style of post analysis edges they are barely visible and I think we need to modify it so they stand out.

**Comment by risserlin** [comment]
Current visualization:
![image](https://cloud.githubusercontent.com/assets/3842763/26504511/dcdec942-4212-11e7-8a66-44b31d9c7a5c.png)

Better visualization:
![image](https://cloud.githubusercontent.com/assets/3842763/26504673/8d999e24-4213-11e7-980a-9aca8b3e70dc.png)

increased the saturation to 100% for the post analysis edges, 
increased the thickness of the edges for those with p-value < 0.01 to width = 5
decreased the size of the post analysis node by calculating the overlap with the pa node and expression set that I loaded in. This is not 100% correct as the set of genes in the enrichment map is probably less than that.

**Comment by risserlin** [comment]
What about making the post analysis edges the same colour as the dataset but a neon version of the colour
This is the same as above but I made the blue color neon blue
![image](https://cloud.githubusercontent.com/assets/3842763/26505018/0462e4b0-4215-11e7-8097-2f87a4509e12.png)

**Comment by veroniquevoisin** [comment]
yes I like the pointed neon blue line for post analysis

**Comment by chrtannus** [comment]
I'm almost sure this will not work with more than a few datasets/colors. For instance, if there is two tints or shades of blue, the neon versions of the same colors may be confusing.
For example, how will the user be able to associated each neon-blue shade with the actual dataset blue colours? You could say "the darker neon version belongs to the dataset that has the darker blue colour", but with too many shades of colours, I don't think this will be intuitive. It only works when theres is not too many colours and/or not too many edges, or when the network is zoomed in, like in the screenshots above. This is not a good general solution for every scenario.

**Comment by chrtannus** [comment]
Here's another option: I tried the animated "Marquee Dash" line type instead of the simple "Dots" one for signature edges, and I think the animation makes it easier to find them. Of course, if the network is a huge hair ball, there is not a lot we can do without filtering, selecting edges and zooming in. Also, the new hub-nodes are now positioned to the left of the network, which also makes it easier to see the edges, at least when they are created.

**Comment by risserlin** [comment]
I prefer the nodes in the centre.  I automatically separate NES +ve and -ve nodes so placing the post analysis  nodes in the centre fits better.
The edges still don't stand out to me.  The marquee is better but they still look faint.  If color doesn't work can we make them thicker edges than the EM edges?
