### ISSUE TITLE
Post analysis command - how to specify which dataset to use for mann-whitney

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#202]
cutoff=<double>:
filterType=<ListSingleSelection (NO_FILTER|HYPERGEOM|MANN_WHIT_TWO_SIDED|MANN_WHIT_GREATER|MANN_WHIT_LESS|NUMBER|PERCENT|SPECIFIC)>:
gmtFile=<File>:
hypergeomUniverseType=<ListSingleSelection (GMT|EXPRESSION_SET|INTERSECTION|USER_DEFINED)>:
name=<String>:
network=current|[column:value|network name]:
userDefinedUniverseSize=<int>:

Also, what does name in the above parameter list refer to?

**Comment by risserlin** [comment]
name refers to the name of the analysis (for example: mirx_tarbase_MWgreater)

**Comment by mikekucera** [comment]
The name you want to give to the PA dataset (optional).

**Comment by mikekucera** [comment]
Are you asking how to specify which ranking to use for each dataset for mann-whitney?

**Comment by risserlin** [comment]
I was asking how to specify the dataset which from the other streams it turns out it is currently not available (batch vs. single dataset mode).

But now that you ask, what happens if there are multiple ranks for a given dataset.  Can you choose which one to use.  (In the previous version of EM it iwas possible to upload additional rankings after the EM was already created.  Does that feature still exist in this version?)

**Comment by mikekucera** [comment]
Yes that feature still exists, its the (+) button on the heat map toolbar.

**Comment by mikekucera** [comment]
You can choose which ranks to use in the UI. This is tricky to add to the command because you can't create arguments dynamically. 

Perhaps something like this:
ranks="DataSet1:MyRanks1,DataSet2:MyRanks2"

Its a similar format to the network/node selection syntax supported by cytoscape.

I am also going to add an argument for batch mode vs specific dataset
