### ISSUE TITLE
Post analysis command - multiple runs with the same network don't show different datasets

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#207]
Run pa with mann whitney less
http://localhost:1234/v1/commands/enrichmentmap/pa?cutoff=0.05&filterType=MANN_WHIT_LESS&gmtFile=C%3A%2FUsers%2Fzaphod%2FRuth_dropbox%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FmiRTargets%2Fmir194_tarbase7.gmt&name=mir194_tarbase_less

then mann whitney greater:
http://localhost:1234/v1/commands/enrichmentmap/pa?cutoff=0.05&filterType=MANN_WHIT_GREATER&gmtFile=C%3A%2FUsers%2Fzaphod%2FRuth_dropbox%2FDropbox%20%28Bader%20Lab%29%2FCSCTeam%2FDICK%2FJD22_mir194_Gabriela%2FPathwayAnalysis%2FmiRTargets%2Fmir194_tarbase7.gmt&name=mir194_tarbase_greater

Name each run a different name so you can distinguish them but in the dataset view only the first run is visible.  

(on windows)

**Comment by mikekucera** [comment]
I just fixed this in #203 

Closing as duplicate
