### ISSUE TITLE
right click on dataset in EM dataset panel to select all nodes/edges for that dataset

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#209]
This might be more useful in the context of post analysis sets but it would be useful to be able to click on one of the datasets in the list and select all the nodes or edges associated with the dataset
(Given that there is no distinction between the edge color of multiple post analysis if there was a way so the user can manually select all of the relevant edges/nodes and then modify the style would be helpful.)

![image](https://cloud.githubusercontent.com/assets/3842763/26600115/d6dc9356-4548-11e7-87ac-88e4a9db0449.png)

**Comment by chrtannus** [comment]
Good idea, but I think we should get rid of the option "select filtered nodes and edges" then, so this option with this new feature don't confuse the users.

**Comment by risserlin** [comment]
What does the  "select filtered nodes and edges"  option do?

Also, the new right click on the dataset only select the nodes and not the edges.  Is this a bug or by design?

**Comment by chrtannus** [comment]
"Select filtered nodes and edges" was a menu item under the "Options" button/icon, a filter mode, along with "Hide" and "Highlight" (filtered nodes/edges).

The right-click selection selects both nodes and edges. I can't see the bug...

**Comment by chrtannus** [comment]
OK, it seems no edges are selected when they are combined.
