### ISSUE TITLE
if I haven't moved my GSEA results file why can the interface not find the original gmt file

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#214]
When running an analysis with 4 gsea output directories that have not moved I get the following warning:
<img width="898" alt="screen shot 2017-06-16 at 11 59 36 am" src="https://user-images.githubusercontent.com/3842763/27234566-6e7beff0-528b-11e7-9fe6-0152cb3ca092.png">
Why isn't the interface able to find the gmt files?

**Comment by risserlin** [comment]
The same applies for expression file.  It looks like it is just using the ranks file by default but the expression file has not moved and should be specified in the rpt file. 

Sorry, the same does not apply for the expression file if you have run GSEA using an RNK file

**Comment by mikekucera** [comment]
This does seem to work. I just ran the GSEA tutorial on my machine then loaded it into EM and it works as expected.
