### ISSUE TITLE
Add class file to common files between datasets

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#218]
If the expression file is common to all datasets then the class file might also be.
<img width="804" alt="screen shot 2017-06-16 at 2 05 47 pm" src="https://user-images.githubusercontent.com/3842763/27238969-006d2f94-529d-11e7-9a85-18e680400083.png">

**Comment by mikekucera** [comment]
In EM2 and EM3 when you add a class file it parses it for the phenotypes and auto-fills the phenotype text boxes. To keep that consistent I would have to add the phenotype fields to the common files page as well.

**Comment by risserlin** [comment]
But what if there are multiple phenotypes.  In the example I am currently working through my dataset class file has 4 different phenotypes.
The phenotypes are still dataset specific, I think.

**Comment by mikekucera** [comment]
So then I should not auto-fill the phenotype text boxes of each data set. I think that would be confusing, and it wouldn't work if the user added data sets after setting the common class file. I will simply add a text field for the class file to the common page and thats it.
