### ISSUE TITLE
Leading edge missing when creating EM from command

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#222]
When creating a network from a command, specifying the edb file and the rank file (analysistype= gsea) there are no leading edges in the created network.  

Use the exact same files from the interface and the leading edges appear

example cyrest call that doesn't have leading edge (sorry truncated, missing the full pathname to my expression file and similarity coeff which is set to COMBINED)

http://localhost:1234/v1/commands/enrichmentmap/build?analysisType=gsea&gmtFile=%2FUsers%2Fruthisserlin%2FDropbox%20%28Bader%20Lab%29%2FRuth%20Isserlin%27s%20files%2FEnrichment_Analyses%2FEM_protocol%2FWorking_Copy%2FEnrichmentMapPipeline_notebooks%2F.%2Fdata%2FMesen_vs_Immuno.GseaPreranked.1497635459262%2Fedb%2Fgene_sets.gmt&pvalue=0.05&qvalue=0.0001&similaritycutoff=0.375&ranksDataset1=%2FUsers%2Fruthisserlin%2FDropbox%20%28Bader%20Lab%29%2FRuth%20Isserlin%27s%20files%2FEnrichment_Analyses%2FEM_protocol%2FWorking_Copy%2FEnrichmentMapPipeline_notebooks%2F.%2Fdata%2FMesen_vs_Immuno.GseaPreranked.1497635459262%2Fedb%2FMesenvsImmuno_RNASeq_ranks.rnk&enrichmentsDataset1=%2FUsers%2Fruthisserlin%2FDropbox%20%28Bader%20Lab%29%2FRuth%20Isserlin%27s%20files%2FEnrichment_Analyses%2FEM_protocol%2FWorking_Copy%2FEnrichmentMapPipeline_notebooks%2F.%2Fdata%2FMesen_vs_Immuno.GseaPreranked.1497635459262%2Fedb%2Fresults.edb&expressionDataset1=%2FUsers%2Fruthisserlin%2FDropbox%20%28Bader%20La... <truncated>

**Comment by mikekucera** [comment]
The problem is that "GSEA" must be uppercase. I'll fix it so that lowercase "gsea" is also accepted.
