### ISSUE TITLE
Special characters in pathway names not recognized by EM3

### ISSUE THREAD

**Issue by drseamonster** [BaderLab/EnrichmentMapApp#225]
pathways with names containing greek characters not recognized...

pathway name in .gmt file

DOWNSTREAM SIGNALING IN NAìVE CD8+ T CELLS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%DOWNSTREAM SIGNALING IN NAìVE CD8+ T CELLS

EM3 read the name as:
DOWNSTREAM SIGNALING IN NA?VE CD8+ T CELLS%PATHWAY INTERACTION DATABASE NCI-NATURE CURATED DATA%DOWNSTREAM SIGNALING IN NA?VE CD8+ T CELLS

**Comment by risserlin** [comment]
Hi Jeff, 
which gmt file are you using?  Also, are you running the GSEA analyses on a Mac or is it on a different computer?
Ruth

**Comment by drseamonster** [comment]
Hi Ruth

The gmt file is:

Human_GOBP_AllPathways_no_GO_iea_April_24_2016_symbol.gmt

Also I ran the analysis on Mac.

Cheers
Jeff

On Jun 21, 2017, at 10:23 AM, Ruth Isserlin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jeff,
which gmt file are you using? Also, are you running the GSEA analyses on a Mac or is it on a different computer?
Ruth

**Comment by risserlin** [comment]
Update:  the issue only occurs if Jeff specifies a common gmt file.  If he allows the interface to use the gmt for each analysis from the edb directory then this is not an issue.

**Comment by mikekucera** [comment]
Can you send me the data files please?

**Comment by drseamonster** [comment]
Hi Mike

Here is the link to the data

https://www.dropbox.com/s/a30lufm2pqvfghy/Archive.zip?dl=0

Thank you for your help.

Jeff

On Jun 21, 2017, at 1:25 PM, Mike Kucera <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you send me the data files please?
