### ISSUE TITLE
Using Common expression file but in compressed mode there is a value for each GSEA result

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#226]
Created a 4 dataset enrichment map with a common expression file (all 4 datasets are represented in one expression file.  Each gsea run is dataset vs rest)

In the expression viewer each GSEA analysis has a value in the compressed view eventhough it is the same file 4 times:
![screen shot 2017-06-21 at 10 21 10 am](https://user-images.githubusercontent.com/3842763/27389078-66e776fe-566b-11e7-973d-38c7f3f3635e.png)

**Comment by mikekucera** [comment]
There are 4 columns because there are 4 datasets. I think you are saying that when there is a common expression file there should only be one set of expressions in the viewer, otherwise its just redundant. Thats fine but I don't think its a bug, its an optimization.

**Comment by risserlin** [comment]
Sorry for the mis-classfication.

**Comment by mikekucera** [comment]
I fixed this in 3.0.
