### ISSUE TITLE
Even though loaded 4 dataset there is only one rank file option to sort by

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#227]
Created a 4 dataset enrichment map with a common expression file (all 4 datasets are represented in one expression file. Each gsea run is dataset vs rest)

In the expression viewer only have option to sort by one of the rank file 
![screen shot 2017-06-21 at 10 28 19 am](https://user-images.githubusercontent.com/3842763/27389482-85ef7974-566c-11e7-8ed5-ee1b95d02a20.png)

**Comment by mikekucera** [comment]
It will only show ranks for datasets that actually contain the gene set (after filtering). Can you check that the selected gene set only appears in the Immuno_vs_rest dataset please?

**Comment by risserlin** [comment]
confirmed.
Can we change that so that we can sort by any of the rank files available.

Use case: a geneset is significant in one dataset and not significant in another but very close.  Might want to compare the ranked list of the two datasets to see how they differ.

**Comment by mikekucera** [comment]
No problem.
