### ISSUE TITLE
Issues with coloring - pvalues

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#228]
p-values are coloured making it seem like the large the p-value the more significant the result

In the below the bottom right is the most significant set and should be the darkest:
![screen shot 2017-06-21 at 11 44 56 am](https://user-images.githubusercontent.com/3842763/27393365-19c7b076-5677-11e7-8b23-e1a919467b7c.png)

**Comment by risserlin** [comment]
same thing for q-values:
![screen shot 2017-06-21 at 11 45 41 am](https://user-images.githubusercontent.com/3842763/27393404-35d827d2-5677-11e7-9b8a-362947006dc4.png)

**Comment by chrtannus** [comment]
What about NES values? Are the colours correct?

**Comment by risserlin** [comment]
The NES values are correct because the larger the value the stronger the colour.  p-value and FDR it is the inverse, the smaller the value the more significamt it is.

**Comment by chrtannus** [comment]
OK, that makes sense. So in your screenshots, shouldn't the bottom **left** be the most significant then?

**Comment by risserlin** [comment]
Yes

**Comment by chrtannus** [comment]
And p/q-values must not be negative, right?

**Comment by risserlin** [comment]
In EM 3.0 RC1 when using gprofiler results higher p-values are colored deeper red and small p-value are white.  It should be the other way around.

**Comment by risserlin** [comment]
link to session showing the issue:

https://www.dropbox.com/sh/sfug424k1s3dvxw/AADYyhXkhLYPihvQ_MruXx4Ya?dl=0

**Comment by risserlin** [comment]
This is working perfectly now in the latest version (as of July 12,2017)
