### ISSUE TITLE
Colouring issue with heatmap

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#230]
There is no colouring difference between different compressed versions of the heatmap. (the values are different but the colouring looks the same)

Compress (Max)
![screen shot 2017-06-21 at 3 05 58 pm](https://user-images.githubusercontent.com/3842763/27401996-2f9598ca-5693-11e7-85c5-e00accd5d4d3.png)

Compress (Min)
![screen shot 2017-06-21 at 3 06 42 pm](https://user-images.githubusercontent.com/3842763/27402036-49a7339a-5693-11e7-9c17-b18a9085b2fe.png)

Compress (Median)
![screen shot 2017-06-21 at 3 07 20 pm](https://user-images.githubusercontent.com/3842763/27402078-695a69f0-5693-11e7-9719-cf9c17ade7af.png)

The coloring seems to be fine for the whole dataset using log ransform or row normalized:
![screen shot 2017-06-21 at 3 09 32 pm](https://user-images.githubusercontent.com/3842763/27402152-abffa252-5693-11e7-809d-1b04571391d4.png)

![screen shot 2017-06-21 at 3 10 37 pm](https://user-images.githubusercontent.com/3842763/27402203-d68fb584-5693-11e7-8ad4-b5e3dad78f63.png)

**Where is the heatmap legend?  I can't find it.**

**Comment by risserlin** [comment]
sorry one more.  It looks like the colors aren't working for the plain expression values as well:
![screen shot 2017-06-21 at 3 12 13 pm](https://user-images.githubusercontent.com/3842763/27402247-0a7dbcce-5694-11e7-8718-2cc496e1f80d.png)

**Comment by mikekucera** [comment]
Click on a table cell to see the heatmap legend for that dataset. The reason is that the legend can be different for each dataset, and there's no limit on the number of datasets, so my solution was to show one legend at a time based on which cell in the table is selected.

**Comment by mikekucera** [comment]
I don't think the colors for plain expression values are broken. The highest value in the expression file is 77402.62 but most of the expression values are less than a few hundred. That means most values are at the bottom of the color gradient which is white.

**Comment by mikekucera** [comment]
Ruth can you please try something for me. Select the entire network. Select "Compress (Max)", then sort by one of the dataset columns (descending). The largest expression values in the network are now visible and are coloured according the the same gradient. Does that seem to be working the way you expect?

**Comment by risserlin** [comment]
a handful of expression values kind of mess up the compression feature for the expression set. What about doing the compression on the row-normalized data as opposed to the raw values? 

It doesn't look like an artifact in the expression file that I should be filtering out. 
https://www.ncbi.nlm.nih.gov/pubmed/26063585

**Comment by mikekucera** [comment]
I could make compression a separate combo box, so you could choose:
Expressions: Row Normalize
Compress: Median
