### ISSUE TITLE
Model should be more memory effecient.

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#231]
Make sure to share expression data if it is the same.
Make sure to remove gene sets that are not of interest.

**Comment by mikekucera** [comment]
Hi Ruth,
Is there any reason to store all the loaded gene-sets in the session file? Perhaps we should only store the "gene-sets of interest" that pass the filter and become nodes in the network.

**Comment by risserlin** [comment]
In its current implementation I don't see why we would need to store the remaining genesets but for  the dark matter feature (#142) the rest of the genesets would be important and needed.

**Comment by mikekucera** [comment]
In that case I think we should keep them... as well as the full contents of the expression matrix. We may want to add features in the future that require that data (such as changing the phenotypes after the network has been created).

I'm working on creating a sharing feature where the expressions are stored in a central cache and can be shared by the data sets. This will eliminate the duplication when using a common expression file.

The only other thing that I can think of that might significantly reduce the session size is to use 32-bit floats instead of 64-bit doubles for the expression values. (We only show two significant digits in the HeatMap.) But that's a pretty big change this late in the cycle.

**Comment by gbader** [comment]
How much difference would the 64 to 32 bit change make?  Ruth, do we need 64 bits of precision? Are we storing p-values all the way to 1E-308?

**Comment by risserlin** [comment]
Definitely don't need 64 bit accuracy

**Comment by mikekucera** [comment]
There's two aspects, memory usage and session file size. 

For memory usage floats would be a savings of a little less than %50 (for just the expression values). 

For the session file it depends less on float vs double and more on the textual representation of the value. In the example Ruth sent me the values have 14 decimal points of precision. Truncating that to 2 decimal points gets me a %50 savings in session file size. This savings will be less if the original values have less precision.

**Comment by mikekucera** [comment]
The example from bug #228 now generates a session file that is about 20M, that is down from about 240M before these changes. I think I can declare victory.

**Comment by risserlin** [comment]
Can you send me a version with this fix?  I am assuming I can save sessions with this fix and they will be able to be restored?

**Comment by mikekucera** [comment]
Yes it should work. 
[enrichmentmap-3.0.0-RC1.zip](https://github.com/BaderLab/EnrichmentMapApp/files/1131938/enrichmentmap-3.0.0-RC1.zip)
