### ISSUE TITLE
loading an individual GSEA result doesn't recognize rpt file

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#234]
I have a directory of many gsea results and I want to create an EM for just one.  I click on the plus sign to add a single dataset.  Then I browse for the file and it doesn't recognize the rpt file in the directory as an possible file to choose.

**Comment by mikekucera** [comment]
You can select a single GSEA folder using the scan button. Does that work for your use case?

**Comment by risserlin** [comment]
yes
