### ISSUE TITLE
one dataset enrichment map - a lot of flickering whenever I move a node

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#235]
I have not annotated the network and no annotations on any of the created network
In a single dataset analysis every time I move a node all other nodes flicker and appear to be re-drawn.

**Comment by mikekucera** [comment]
I'm pretty sure this will be fixed in Cytoscape 3.6.

**Comment by mikekucera** [comment]
I'm not observing any flickering anymore, please reopen if the problem persists.
