### ISSUE TITLE
Auto discovery of gprofiler results puts gmt file in wrong field

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#236]
Created a directory witih gprofiler results:
gprofiler_results.txt
gprofiler_genesets.gmt

Click on folder icon.
clicked on gprofiler folder containing the above two files.
The gmt file is placed in the expression file field instead of the GMT field
![screen shot 2017-06-28 at 10 19 16 am](https://user-images.githubusercontent.com/3842763/27641956-679d6628-5beb-11e7-9d5c-9480034da0f5.png)

Network is built incorrectly.

**Comment by mikekucera** [comment]
Can you send me the files please.

**Comment by risserlin** [comment]
https://www.dropbox.com/sh/wigton0x5gzmfb7/AACbfsKG0dixbjngsaOAlD5Wa?dl=0
