### ISSUE TITLE
gprofiler change of network generation

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#241]
For gprofiler results require: gmt file and generic results file
Create a dummy expression file where genes found in the generic results file have values of dummy expression and the remaining genes in the geneset have a value of NA.
There will be different dummy expression files dependent on the generic enrichment results files. 
*** ideally in the future the presence of a gene in the generic enrichment file vs those not will be highlighted by a similar mechanism as the leading edge. ***

**Comment by mikekucera** [comment]
Hi Ruth, Can you send me the data files for this please.

**Comment by mikekucera** [comment]
Actually I think I can use the files attached to bug #236

**Comment by risserlin** [comment]
You can use any gprofiler files.  Those were the ones I was going to attach here.

**Comment by mikekucera** [comment]
Actually can you attach them please. You were using a 2-dataset analysis and I only have a gproflier files for one dataset.

**Comment by risserlin** [comment]
Here they are: 
gprofiler results file: https://www.dropbox.com/s/e29ix2nc3msvy7f/Supplementary_Table4_gprofiler_results.txt?dl=0
gprofiler gmt file:
https://www.dropbox.com/s/4iv8ey36bp22ivy/Supplementary_Table5_hsapiens.pathways.NAME.gmt?dl=0

**Comment by mikekucera** [comment]
Should be working. Please reopen if there are still issues.

**Comment by mikekucera** [comment]
Closing again. Please reopen if there are more issues.
