### ISSUE TITLE
GSEAResolver should be smarter about finding GMT file

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#244]
The gmt file path in the RPT file is absolute, so moving the GSEA folder generally breaks the resolution.
- Try to make the lookup smarter by checking for the file in a location relative to the current GSEA folder. (Note this may not even be possible.)

**Comment by risserlin** [comment]
Just adding the comment I made in slack.  It looks like the gmt is only absolute when using the GSEA interface.  If you use GSEa from the command line the gmt in the rpt will be whatever you specified as the path.

**Comment by mikekucera** [comment]
It now searches for the GMT file (using the file name from the rpt) in the parent folder of the gsea folder.
