### ISSUE TITLE
heatmap sort doesn't work correctly with new missing data

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#250]
With the latest update of EM where gene not found in the expression set are included in the heatmap (and in the map in general) the sorting isn't quite right in the heatmap
select node
change compress mode to "Max"
click on Expression column.  
First time the column will be sorted and the lowest values will be at the top of the list
Second time the column will be sorted and the missing values will be at the top of the list. 

Ideally the missing values should be ignored when sorting so that when you click first time it is the lowest values and the second time it is the highest values.

**Comment by mikekucera** [comment]
This is not possible to fix because the sorting logic is part of the JTable class.
