### ISSUE TITLE
export expression data issue

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#252]
Create EM with gsea results
Create second EM with gprofiler results
go to second network
select individual node
in heatmap select export to txt

first issue: it saves the file twice.  I specify the name of the file and then another dialog comes up prompt me to name the new file again.  I select the file it just created and then I get a pop up asking me if I want to replace the file as it exists.
second issue: prompts me if I want to export leading edge only.  This is a gprofiler analysis.  It has no leading edge.
third issue:  When I go to open the exported expression file it contains expression values from the first EM I created with gsea results and not the gprofiler results.

**Comment by risserlin** [comment]
issue is related to the presence of multiple analyses as when I create a clean session with just the gprofiler results the export does not prompt me to export the leading edge and it exports the correct data.

**Comment by mikekucera** [comment]
Should be fixed now.
