### ISSUE TITLE
not able to use NES colouring for single dataset

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#255]
Chart data and chart colours are greyed out in the Style panel in the EM input panel when you are using only one dataset.

**Comment by chrtannus** [comment]
Should it also show the radial heat map chart by default (when EM network is created) if there is only one dataset? Or should it have no charts selected, but with the chart options always enabled?

Remember that, in this case, node colour is painted by a continuous mapping (maps the _EM1_Colouring_ column), and the radial heat map would hide most of the node's fill colour--see in the images below how the original node fill colour looks like a border when the radial heat map is set.

![nocharts](https://user-images.githubusercontent.com/989686/28533469-36788ec6-706b-11e7-85e7-bd99618c3abb.png)
![withchart](https://user-images.githubusercontent.com/989686/28533473-39b1eb96-706b-11e7-8be3-93fb57764d94.png)

**Comment by risserlin** [comment]
I think it should be option 2 so no matter how many datasets you have the coloring is consistent.  If we change it will the user be able to change to the old coloring?

**Comment by chrtannus** [comment]
You mean always show the heat map initially to be consistent?
Yes, the user can always select "none" for Chart Data and clear it.

**Comment by chrtannus** [comment]
There's still a bug where charts are not displayed when network is created, only after refreshing the style.
See ControlPanelMediator.updateVisualStyle() -- line #709.

**Comment by mikekucera** [comment]
Think I fixed it. If anyone sees this still happening please reopen the bug.
