### ISSUE TITLE
collapsed network not using cluster name to annotate collapsed node

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#256]
<img width="448" alt="screen shot 2017-07-20 at 12 48 49 pm" src="https://user-images.githubusercontent.com/3842763/28429211-eddc6468-6d49-11e7-9769-7d9d8ec1d9fc.png">

Haven't test with straight forward usage but to get this issue
I had publication ready figure. (in publication ready mode)
collapsed all nodes
untoggled publication ready and this was the result.

**Comment by risserlin** [comment]
not an issue if the publication ready is not selected.

**Comment by mikekucera** [comment]
- turn publication ready mode on
- collapse the cluster
- turn publication mode off

**Comment by mikekucera** [comment]
Fixed in AutoAnnotate (BaderLab/AutoAnnotateApp#114)
