### ISSUE TITLE
usability? legend for mastermap

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#257]
I loaded two GMT files (one for each patient class in netDx), and it's nice to see that the new emap shows me which ones are common to both. But the colour scheme updates in an inconsistent way when I unselect some of the nets. Also not clear which colour corresponds to which net.

e.g. Here is a view with both nets on. Some circles are half orange and half white. But which is orange? The first one (from the orange-white-purple swatch in the dropdown box)?

![screen shot 2017-07-20 at 1 37 27 pm](https://user-images.githubusercontent.com/7502338/28431355-1b75c18c-6d52-11e7-984a-4994ea677889.png)

So I unselect one of the nets, to see which colour disappears.
And instead, the nodes all go red and the colour scheme is lost.

![screen shot 2017-07-20 at 1 39 37 pm](https://user-images.githubusercontent.com/7502338/28431365-229a8a42-6d52-11e7-823c-c5a99bca8d90.png)

At first I thought the little "paper sheet" icon next to the map name (in the "Data Sets:" text box) could be colour-coded according to the corresponding colour. And that would be an intuitive place to show the legend. But it's unclear where the user goes to see e.g. which net is "orange".

**Comment by mikekucera** [comment]
The "paper sheet" icon indicates the color of the edges. The chart legend is available under the "gear" button at the top of the panel.

**Comment by shraddhapai** [comment]
I see it. I found it unintuitive because you can set a lot of other basic parameters without having to go to an "Advanced"-esque menu like the gear.  I suggest a  "toggle legend" or "show/hide legend" button near the 'data sets:' panel. Perhaps just above the 'add signature gene sets' button but left-aligned. 

Also not intuitive that the paper sheet colour indicates edge colour. Perhaps along with the 'show/hide legend' there could be a little paper sheet icon with the words 'edge colour' next to it.

Right now I have a map where for some reason all three maps have the same colour edge. Whereas before each map had a different coloured edge. Not sure what changes the edge colour.

**Comment by risserlin** [comment]
HI Shradhha, 
We made a significant change in this version of EM with regards to how we calculate the universe.  Specifically the gmt file is not filtered by the expression file or the enrichment file.  If the same gmt is used in all of your datasets then there will be no different in the overlap between two pathway from one datasets to the other.  Not sure how this effects your use case though.  We should discuss this more in detail to make sure this change hasn't messed things up for you.
Ruth

**Comment by shraddhapai** [comment]
Hi Ruth,
I generate different gmts for each of my conditions, rather than generating
a single gmt and then filtering it with multiple expression/enrichment
files. So it sounds like the change in this version should be fine for my
purposes. But yes, happy to chat more on Slack e.g.

I'm really liking the feature of loading multiple EMs in succession and
having the pie chart automatically generated!

Thanks,Shraddha
