### ISSUE TITLE
mastermap legend doesn't correspond to view

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#258]
Just noticed. My circles are orange and white, but my legend claims they should be purple and white.
I'm using the EM build sent to me by Ruth yesterday.

![screen shot 2017-07-21 at 11 42 56 am](https://user-images.githubusercontent.com/7502338/28471102-f700ebc0-6e09-11e7-87e3-def56aa95034.png)

**Comment by chrtannus** [comment]
It should look better now. Just notice that the chart colours don't really mean anything in the legend, it's just used to better separate the chart items (i.e. slices, bars). It's the items position/order with the dataset name that matter. I'm a bit worried that the user may get confused by the colours in the legend, so maybe all the chart items should be grey to avoid that.
