### ISSUE TITLE
EM panel gets cut off irreversibly if Tool Panel opened 

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#259]
I generated several EMs. 
Then I wanted to rescale nodes so I opened the Tool Panel and moved nodes closer (scale). This of course obscures the Enrichment Map panel on the bottom. 
Went to a different panel to load an attribute for one of the nets.
Then came back to 'EnrichmentMap' panel, and tried to resize the tool panel down so I could do something in the EM panel. And the panel is still cut off as if I hadn't resized the Tool panel.

![screen shot 2017-07-21 at 6 41 57 pm](https://user-images.githubusercontent.com/7502338/28485016-4e3fb8b4-6e44-11e7-9828-f26e85bc142c.png)

**Comment by chrtannus** [comment]
This is not an EM bug. It's a Cytoscape one, because it happens with all the other tabs. So I'm closing this report and opening a ticket in Cytoscape's Redmine: http://code.cytoscape.org/redmine/issues/3878
Thanks for letting us know!
