### ISSUE TITLE
EMs don't get restored in EM panel on session reload

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#260]
I created a session with multiple EMs, saved and exited Cytoscape (because of the lack of refresh in the ticket previously opened; the one where opening the tool panel cuts it off).
On reopening Cytoscape (3.5.1) I see the enrichment maps in the network panel.

However the EMs don't show up in the "EnrichmentMap" panel, under "Data Sets:". I notice that for the 'Data Sets:' panel to register the new EMs, you have to first click on the network in the 'Networks' panel. Otherwise it doesn't show up. So to get all the EMs to show up in the EM panel, you have to methodically click on all of them in the 'networks' panel first.

**Comment by mikekucera** [comment]
Thats how it is meant to work. There is only room on the EM panel to show data for one network at a time, the current network. There is a network selector combo box at the top of the EM panel that lists the EM networks that allows to quickly switch between them without having to go back to the network panel. Is that satisfactory?
