### ISSUE TITLE
Hide Node Label

### ISSUE THREAD

**Issue by smsinks** [BaderLab/EnrichmentMapApp#264]
How do I hide node labels in EnrichmentMap? Furthermore, how can I produce an image with a legend?

Thanks

**Comment by risserlin** [comment]
which version of enrichment map are you using?

**Comment by smsinks** [comment]
Version 2.2.1

**Comment by risserlin** [comment]
In the results panel (if the result panel is not visible go to View --> show results panel) on the right hand side under the advanced tab there is an option "toggle publication ready".  If you click on that all node labels disappear.  click again to have them reappear. 
![image](https://user-images.githubusercontent.com/3842763/29332058-ac116ae6-81cc-11e7-8117-66c91c9dfc4d.png)

**Comment by risserlin** [comment]
Unfortunately legends are not automatic.  I usually export the image and then add the legend manually in a graphics program.  
Here is a link to a template I created for the EM legend.  It is specific to the latest version of EM that is coming out soon but should still be applicable to 2.2.1
https://www.dropbox.com/s/lwo96zwq7elsohl/Figure%2012_EM_generic_legend.pdf?dl=0

**Comment by smsinks** [comment]
Thank you very much. You have saved me. Kind regards
