### ISSUE TITLE
How can I export Heat map image?

### ISSUE THREAD

**Issue by crysrain** [BaderLab/EnrichmentMapApp#27]
Hi,

I generated Heat Map (Nodes). When I used "Export Expression Set (PDF)" to export the Heat Map, nothing happened. Is this the right way to export Heat Map image?
Thanks.

Jian

**Comment by risserlin** [comment]
Please just take a look to see if there is a pdf writer for the heatmap.

**Comment by mikekucera** [comment]
Works for me with EM 2.1 and Cytoscape 3.4.
