### ISSUE TITLE
generic/gprofiler command not recognizing gmt file

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#271]
when I run command from R and supply the gmt file and run the same analysis from the interface I get different results.  Results are correct from the interface but not from the command.  

The command is generating a generic gprofiler results as if it doesn't see the gmt file.

from the interface:
<img width="568" alt="screen shot 2017-09-14 at 5 04 05 pm" src="https://user-images.githubusercontent.com/3842763/30455679-cf3a71ca-996e-11e7-9a0f-81e762a52741.png">

from the command:
<img width="552" alt="screen shot 2017-09-14 at 5 03 40 pm" src="https://user-images.githubusercontent.com/3842763/30455687-d7f428ec-996e-11e7-89ae-7a4a29400d4e.png">

The one from command has more than double the edges because they are computed with the universe orginating only from the results file as opposed to the genesets defined in the gmt file.

**Comment by mikekucera** [comment]
Seems to be working for me. Can you send me the command you used and the data files please.

**Comment by risserlin** [comment]
command (ran it in the command tool window) - generates a network with 568 nodes and 12220 edges (same when I run it through cyrest from R):
enrichmentmap build analysisType="generic"  gmtFile="/Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Enrichment_Analyses/EM_protocol/Working_Copy/EnrichmentMapPipeline_notebooks/data/Supplementary_Table5_hsapiens.pathways.NAME.gmt" pvalue= 0.05 qvalue= 0.05 similaritycutoff= 0.25 coeffecients= JACCARD enrichmentsDataset1="/Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Enrichment_Analyses/EM_protocol/Working_Copy/EnrichmentMapPipeline_notebooks/data/Supplementary_Table4_gprofiler_results.txt" 

From the interface the same files generate a network with 568 nodes and 2939 edges.

Links to files:
gmt - https://www.dropbox.com/s/4iv8ey36bp22ivy/Supplementary_Table5_hsapiens.pathways.NAME.gmt?dl=0
enrichments - https://www.dropbox.com/s/e29ix2nc3msvy7f/Supplementary_Table4_gprofiler_results.txt?dl=0

**Comment by ghost** [comment]
Hi, I use the gProfiler result file and the GMT file downloaded from baderlab's website, however the EM in cytoscape (3.6.0) cannot find a geneset which is actually in the GMT file. Is there any problem in that line? And how to fix it?
![image](https://user-images.githubusercontent.com/30320615/34992065-d9fb1a20-fb06-11e7-87c6-82f43a04d638.png)

**Comment by risserlin** [comment]
For g:profiler you don’t need a gmt file. The Gmt file is optional for g:profiler results. If you want to use one then you need to download the g:profiler gmt file. 
See the g:profiler tutorial for how to download the gmt file
http://baderlab.org/Software/EnrichmentMap/GProfilerTutorial

**Comment by ghost** [comment]
Thank you very much Ruth, I just missed that step when looking the tutorial...
And I also want to ask how to generate an image like the following one introduced in a cytoscape video on Youtube.
![image](https://user-images.githubusercontent.com/30320615/35025618-85719080-fb81-11e7-995c-fab7cc7cea6a.png)

I have several gene lists and want to compare their g:Profiler results, so I think the final comparison presentation will look like the image above. 
I read some EM tutorials like http://www.pathwaycommons.org/guide/workflows/rna_seq_to_enrichment_map/visualize/, 
and know about the AutoAnnotate app combined usage. 
I have also checked the [cytoscape user manual](http://manual.cytoscape.org/en/stable/Introduction.html) but cannot find out the steps to compare.
Could you please give me some hints?

**Comment by risserlin** [comment]
unfortunately I have not had a chance to write a tutorial for this feature.  It is on my to do list.  
Briefly, 
 * first you will need the latest version of EM  which is currently in pre-release.  You can get it here: https://github.com/BaderLab/EnrichmentMapApp/releases/tag/v3.1.0-RC1
 * Run g:profiler for each of your gene lists.
 * create a multi-dataset enrichment map.  (there is no limit on the number of datasets that you can use.  I don't have a tutorial yet for multiple datasets but our updated protocol should have some good pointers on how to set this up with the new interface https://www.biorxiv.org/content/early/2017/12/12/232835)
 * Once you have your multi-dataset network created with the latest version of EM in the EM interface there is an option to "Color by dataset"
<img width="376" alt="screen shot 2018-01-09 at 10 09 43 am" src="https://user-images.githubusercontent.com/3842763/35055153-7253d116-fb7c-11e7-90d4-9e4bbbcee480.png">

let me know if you have any issues.  
Ruth

**Comment by ghost** [comment]
Thank you Ruth! I have created a multi-dataset enrichment map, still learning to make the style more beautiful.

**Comment by lukepoh** [comment]
Hi

Does anyone know how I can fix this? I downloaded (name) GMT file from gprofiler and data in GEM format, then extracted the file and uploaded onto *GMT and *Enrichments respectively. Would be great help, thank you!
![2018-10-26](https://user-images.githubusercontent.com/44488978/47545193-79783480-d91d-11e8-8ac1-0de10161fd45.png)
