### ISSUE TITLE
Different results when create EM using command vs using the interface (more specifically different results when using edb vs excel files)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#276]
Creating an EM using a command and edb file creates a different network than when I create it using the interface. 

It is a rounding issue.
For my example, In the EM created with command and the edb file there are 6 additional genesets.  All six have an FDR of 0.01 (which is the specified threshold).  When you look in the gsea results file all 6 genesets have FDR slightly over 0.01 but if you look in the edb file the p-value has been rounded by GSEA.

 **This is not an EM bug - the two different file types represent slightly different results because of the round** 

Should we eliminate the edb option?  That is how GSEA interfaces directly with EM. Can we just put a disclaimer?

**Comment by mikekucera** [comment]
I added the rounding. Can you give it a try please.

**Comment by risserlin** [comment]
command,edb and interface generated identical networks
