### ISSUE TITLE
Different number of edges when creating EM using command vs using the interface 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#277]
* only different parameter between the two runs is edb vs. excel spreadsheet.

When using the interface there are less edges than when using the edb

In the EM created using the interface in the resulting EM it has correctly NOT filtered the results by expression (i.e. when you click on a node you can see greyed out genes that are in the geneset but not found in the expression set.)
In the EM created using the command and edb file in the resulting EM it has  filtered the results by expression (i.e. when you click on a node you can NOT see greyed out genes that are in the geneset but not found in the expression set.)

There doesn't seem to be a parameter in the command to make sure it doesn't filter by expression set.  In the interface there is an option but by default it is not selected.

**Comment by mikekucera** [comment]
Woah, big oversight. I'll take a look asap.

**Comment by mikekucera** [comment]
I can't reproduce this with the mastermap command, which has a "filterByExpressions" argument that is false by default.

Are you using the older gseabuild command?

**Comment by risserlin** [comment]
here is the command I am using:
enrichmentmap build analysisType=\"gsea\" gmtFile= /Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Sourcecode/Cytoscape_workflows/EnrichmentMapPipeline/data/Supplementary_Table3_Human_GOBP_AllPathways_no_GO_iea_July_01_2017_symbol.gmt pvalue= 1.0 qvalue= 0.01 similaritycutoff= 0.375 coeffecients= COMBINED ranksDataset1= /Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Sourcecode/Cytoscape_workflows/EnrichmentMapPipeline/data/Mesen_vs_Immuno.GseaPreranked.1508347888063/edb/Supplementary_Table2_MesenvsImmuno_RNASeq_ranks.rnk enrichmentsDataset1= /Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Sourcecode/Cytoscape_workflows/EnrichmentMapPipeline/data/Mesen_vs_Immuno.GseaPreranked.1508347888063/edb/results.edb expressionDataset1= /Users/risserlin/Dropbox (Bader Lab)/Ruth Isserlin's files/Sourcecode/Cytoscape_workflows/EnrichmentMapPipeline/data/Supplementary_Table6_TCGA_OV_RNAseq_expression.txt
