### ISSUE TITLE
Where is the FDR slider

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#279]
thresholds were specified as p-value < 1 and fdr < 0.01 but only p-value slider is visible.
![screen shot 2017-10-19 at 1 25 08 pm](https://user-images.githubusercontent.com/3842763/31784829-1280b264-b4d1-11e7-9329-b6abbaa8e260.png)

**Comment by mikekucera** [comment]
Can you please confirm that the q-value attribute is present in the table. The radio buttons for selecting p/q value sliders won't show up if the fdr q-value attribute is missing.

**Comment by risserlin** [comment]
![screen shot 2017-10-19 at 3 24 57 pm](https://user-images.githubusercontent.com/3842763/31789939-bf93c8d2-b4e1-11e7-820e-07fa3bd2e58c.png)

**Comment by mikekucera** [comment]
Can you send me the session file please.
