### ISSUE TITLE
Chart showing up on post analysis node

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#284]
<img width="343" alt="screen shot 2017-11-03 at 12 58 02 pm" src="https://user-images.githubusercontent.com/3842763/32386171-b919bb7c-c096-11e7-9d4b-62f3d774aa8b.png">

Post analysis run through command (but got the same behaviour through the interface)

**Comment by mikekucera** [comment]
Looks like it has a chart layered on top.

**Comment by mikekucera** [comment]
You can get rid of it manually. Select the PA node, find Image/Chart 1 in the vizmapper, click the bypass button, then in the image dialog click the 'remove graphics' button at the bottom.
