### ISSUE TITLE
Post analysis - signature discovery No task monitors coming up

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#285]
I just tried helping someone who was having issues with post analysis and there were a slew of issues:
He was using a symbol gmt file when his map was built with entrez gene ids but no error message came up that there were no maps with file.  The only filter that worked was "no filter" but there was no indication that there were no matches in the file.
No task monitor came up that it was actually parsing through the file.  
He reverted to using EM 2 because couldn't figure out what was happening.

**Comment by mikekucera** [comment]
Fixed by new UI #288
