### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by marcomontagner** [BaderLab/EnrichmentMapApp#287]
Hi, 
thanks for this useful plugin. I'm having this problem while generating an enrichment map from GSEA Analysis files:
Parsing Generic Result File 1.
I'm using EnrichmentMap 3.0.0 with Cytoscape 3.5.1. I already generated other maps with this plugin so I'm wondering what the problem is with this specific map...
thanks a lot for the support,
Marco

**Comment by risserlin** [comment]
Hi Marco, 
Did you open any of the GSEA results files in excel?  When you load your GSEA results is the analysis type set to "GSEA" or "Generic"?

**Comment by marcomontagner** [comment]
Hi Ruth,

thanks a lot for your quick reply!

yes I opened them with Excel and I selected GSEA

Marco


Il 09/11/2017 16:46, Ruth Isserlin ha scritto:

**Comment by risserlin** [comment]
Hi Marco,
Unfortunately, if you saved the Gaea results files excel might have messed up the file. Although the file has an xls ending it is actually just a text file. I'll check to see if it fixable.
