### ISSUE TITLE
post analysis edges different when using filtered vs unfiltered gmt

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#289]
if I create an em with the filtered option as false (with the original gmt file) or with filtered option as true then I get different number of edges when I run post analysis.

issue: using different universe size based on input gmt.

Given that the default used to be filtered then it probably still should be.  Maybe add option to the universe setting to use original gs sizes.

**Comment by mikekucera** [comment]
I'm not sure how to reproduce this. I'm assuming you are talking about the hypergeometric universe. The different options are not effected by filtering. GMT is always the total number of genes in the gmt file before filtering. Expression set is the total number of genes in the expression file. And intersection is just the intersection of those.

What settings are you using exactly. Perhaps its choosing the wrong default?
