### ISSUE TITLE
GREAT option / Cytoscape 3.1.1 EM build 407

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#29]
suggested enhancement:
1) be able to get the Binomial and Fisher FDR values ('and' relationships , 'or' relationships by putting one cutoff to 1)
2) be able to enter low (lower than 0.001) values in the parameter boxes
3) be able to play effectively with the pvalue and qvalue slidebars (e.g. by replacing them by -log10(values)
(4) issues from GREAT: be able to select only the the GO and pathways terms)

Thanks a lot, Veronique.

**Comment by risserlin** [comment]
Added dialog popout for GREAT build that asks the user if they want to use hyper, binom, both or either  fe0504364c6dad91b21fac0e4bd8cc2349274938
Added option to swap pvalue and qvalue to scientific notation and 12 digits allowed in the text box so you can enter lower values. 95cd9826a1bab0385db998cf558be5e9643a70f3 
Updated filters so you can use them when the pvalue is very small (it will only go as low as 10-3 lower than the given cutoff though) --> currently can't use the minimum as the range from the cutoff to the lowest can be as large as 100 decimal places which messes up the slider. 9cf5cf274d78f4ab10af61e29d73e66e78c0317e
