### ISSUE TITLE
Enrichment map heatmap showing only black squares

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#290]
![pastedimage](https://user-images.githubusercontent.com/3842763/33219736-10cb1984-d112-11e7-80f5-21c9cc575ebd.png)

Using Em 3.0

**Comment by mikekucera** [comment]
session file please

**Comment by risserlin** [comment]
I sent via email on Nov. 24.

**Comment by mikekucera** [comment]
I can't reproduce this. Ruth if you get any new info please reopen the bug.

**Comment by risserlin** [comment]
Hi Mike, 
Uros sent the files for this bug to me and you.  I was able to reproduce it with his files.

**Comment by mikekucera** [comment]
The problem is caused by NaN values in the expression file. Also the session serializer was not handling NaN values and was throwing an exception, that's why the original session file did not contain any enrichment map data.

Reopening because there are still problems with normalization.
