### ISSUE TITLE
Color by dataset - change colors in style - restored session doesn't remember your changes

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#292]
Using the color by dataset feature.
Change the colors through the charts interface
save session
close session 
reload session
color setting you changed are re-set to the default instead of your choices.

**Comment by mikekucera** [comment]
The EM control panel has control over the style. Any time you make a change to the chart settings its going to override any changes to the style that were made manually. I guess this is also happening on session load.

What we need is to allow the user to change the color that's associated with each dataset. Then the charts will automatically use those colors.

**Comment by krassowski** [comment]
How can I change the colors through the charts interface?
Looking forward for the full support of "color by dataset" and 3.1 release :)

PS. If anyone wonders what are the names of the default colors: "Regent St Blue" and "Feijoa".

**Comment by mikekucera** [comment]
The ability to change the color of datasets was added in 3.3.0
