### ISSUE TITLE
Remove 'Common Files (included in all data sets)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#296]
It would be nice to be able to remove the content of the 'Common Files' folder in the 'Create Enrichment Map' dialog box by selecting it and selecting the trash icon. We can do it for the GSEA folders but wehave to manually remove the path of the expression file.
![screen shot 2017-12-18 at 10 25 30 am](https://user-images.githubusercontent.com/7570379/34113581-282ae968-e3de-11e7-9bd0-e1a9f5788bcb.png)

**Comment by mikekucera** [comment]
I'll add a "reset" button below the text fields. The trash icon is meant to remove an item from the data set list which doesn't work for the common files item.
