### ISSUE TITLE
Color by Data Set does not work when using Generic File input

### ISSUE THREAD

**Issue by s2hui** [BaderLab/EnrichmentMapApp#299]
1) Loaded two generic data sets into Enrichment Map formatted:
Pathway Id {tab} Pathway Description {tab} p-value

2) Selected Color By DataSet in the Style dropbox

3) Nodes in the EM are blank (not filled with any colour)

Comments: Ruth went to Style -> Image Chart, clicked on the Pie Chart icon and dragged DataSet_chart out and NES columns in.  This seemed to fix the problem as the nodes are coloured properly.

Cytoscape version v3.5.1
Enrichment Map version 3.1.0 SNAPSHOT (Snapshot from Ruth Jan 10, 2018)

**Comment by mikekucera** [comment]
I can't reproduce this problem with the generic tutorial files. Can you send me the data files you were using?

**Comment by s2hui** [comment]
Please try these files:

[KhokhaKim-erpos-5e-8-minigwas-enrichmentmapinputs.txt](https://github.com/BaderLab/EnrichmentMapApp/files/1686160/KhokhaKim-erpos-5e-8-minigwas-enrichmentmapinputs.txt)
[KhokhaKim-erneg-5e-8-minigwas-enrichmentmapinputs.txt](https://github.com/BaderLab/EnrichmentMapApp/files/1686161/KhokhaKim-erneg-5e-8-minigwas-enrichmentmapinputs.txt)

**Comment by mikekucera** [comment]
Can you send the GMT file as well, thanks!

**Comment by s2hui** [comment]
Try this:

[Human_GOBP_AllPathways_no_GO_iea_November_01_2017_symbol_repair_break_damage.gmt.zip](https://github.com/BaderLab/EnrichmentMapApp/files/1690187/Human_GOBP_AllPathways_no_GO_iea_November_01_2017_symbol_repair_break_damage.gmt.zip)

**Comment by mikekucera** [comment]
Thank you for sending the files.

It still works fine for me. I created two datasets, one for each of the enrichment files, and I put the GMT file in common files, and it works fine.

Can you please verify that you can still reproduce the bug. And if so can you please send me the exact steps you take to reproduce it. Thank you.

**Comment by s2hui** [comment]
Weird?! It seem to be working now!
