### ISSUE TITLE
restored session from filtered with slider bars EM has different universe for Post analysis

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#3]
on stored session universe is different (if sliders were used to filter genesets in the original anlaysis) which changes the p-values.

In original session all genesets in the initial created EM are used to calculate genes in the universe (even if some have been filtered out) In restored session on genesets present in the map are used making the universe smaller, making the p-values larger.

Will be resolved once the universe is calculated at build and stored as a parameter associated with each dataset.

**Comment by mikekucera** [comment]
This is solved by the new universe parameter on the new PA panel, right?

**Comment by mikekucera** [comment]
I'm assuming this is fixed.
