### ISSUE TITLE
input window: drag and drop folder and files

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#301]
it would be nice to be able to also drag and drop individual files (eg for the generic format) instead of having to click on the + sign and then browsing .
<img width="337" alt="screen shot 2018-01-17 at 7 05 10 pm" src="https://user-images.githubusercontent.com/7570379/35073981-a8453584-fbb9-11e7-97fc-989237fb74fa.png">

**Comment by mikekucera** [comment]
This very similar to #327, I will close this issue and address both drag and drop and the scan button in issue #327
