### ISSUE TITLE
RC 3.1.0 stored session and q and p value slide bar: it changes the layout

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#302]
when I work on  a stored session and want to use the pvalue/qvalue slide bar to reduce the number of gene-sets, it changes the layout of the map. 
<img width="943" alt="screen shot 2018-01-22 at 10 13 33 am" src="https://user-images.githubusercontent.com/7570379/35227907-60429ab8-ff5d-11e7-8469-6189a2b3e249.png">

**Comment by veroniquevoisin** [comment]
I think you can close this one. I forgot that I was working on a subnetwork and not on 'dataset1'

**Comment by mikekucera** [comment]
no worries
