### ISSUE TITLE
3.1 RC - when I bypass the style on some EM nodes the style is blocked by the chart

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#303]
![screen shot 2018-01-22 at 1 00 02 pm](https://user-images.githubusercontent.com/3842763/35236169-4cc3b5e6-ff74-11e7-9436-411e8446440b.png)

In order to get rid of this click on chart for bypass and manually remove the chart from these nodes.

**Comment by mikekucera** [comment]
I don't think there's anything I can do about this. All the charts can be removed by selecting "Chart Data: none" in the control panel. If you want charts on some nodes but not on others then the only way to do that is with bypasses.
