### ISSUE TITLE
RC3.1 purpose of the dataset box in input window?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#305]
not sure I understand the purpose of the 'Data sets:'box (see screenshot) as it displays only one dataset. Is it for post-analysis?

<img width="337" alt="screen shot 2018-01-23 at 2 54 46 pm" src="https://user-images.githubusercontent.com/7570379/35297620-8ec6cad0-004d-11e8-8418-9fe0781f99de.png">

**Comment by mikekucera** [comment]
If you have multiple datasets or post-analysis data sets they will be displayed there.

**Comment by veroniquevoisin** [comment]
I have 2 datasets but I just see only one in this window. All my datasets have been renames "Data Set 1" but you can see that I have 2 sorts of edges blue and green

![screen shot 2018-02-01 at 3 58 08 pm](https://user-images.githubusercontent.com/7570379/35703350-be87aa3c-0769-11e8-9702-baf5f54c9202.png)
![screen shot 2018-02-01 at 3 58 26 pm](https://user-images.githubusercontent.com/7570379/35703354-c11bb126-0769-11e8-8a99-9e2c02a62853.png)
![screen shot 2018-02-01 at 3 59 24 pm](https://user-images.githubusercontent.com/7570379/35703359-c3ef29f0-0769-11e8-9c1d-1e7dcf7d824c.png)

**Comment by mikekucera** [comment]
I opened a new issue (#312) to track the new problem.
