### ISSUE TITLE
RC3.1 coloring nodes using attributes imported as a table

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#307]
I have trouble recoloring the nodes using attributes imported as an external table. The attribute column is visible in style but the color does not change accordingly. I deleted the mapping and tried again and it did not work. I have to play with the"Chart Data:" box from the EM input window to be able to do it. I have to set Chart data to "None" and if set to None already, I still have to redo this selection so it works. 
![screen shot 2018-01-24 at 11 22 22 am](https://user-images.githubusercontent.com/7570379/35343623-10204006-00f9-11e8-840f-e1fd1242bed7.png)

**Comment by veroniquevoisin** [comment]
now that I have colored my nodes using an external attribute, I wanted to export the map as an image without the gene-set labels. In order to do it , I checked the box "publication ready" but it removed my coloring and replace it by default by the EM_Colouring column. When I uncheck the box, it did not revert it back to my attribute column I had chosen for the coloring. 
screenshot with my coloring:
![screen shot 2018-01-24 at 11 52 46 am](https://user-images.githubusercontent.com/7570379/35345603-0f6e14e4-00fe-11e8-9944-62766b4df2dd.png)
screenshot after I checked 'publication ready'
![screen shot 2018-01-24 at 11 55 09 am](https://user-images.githubusercontent.com/7570379/35345642-28351fd6-00fe-11e8-896f-76780785a58c.png)

**Comment by mikekucera** [comment]
EnrichmentMap has control over the style. Any time you make changes in the panel it will reset the style. If you need to make manual changes then copy the style first or you will lose your changes.

We could do a better job of communicating this limitation but this is how it works by design.

**Comment by veroniquevoisin** [comment]
What is doing "publication ready" in addition to remove gene-set labels? Before we used it to remove the purple background as well.
