### ISSUE TITLE
RC3.1 not able to upload a GSEA folder into EM but can upload the files manually

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#309]
I have generated 2 new GSEA results today. I m not sure why but i can't drag and drop with 2 folders into enrichmentmap. I tried to add them by browsing and it does not work either. I can upload the files manually and it works. I have tried GSEA results that I have generated last week and it worked for these folders.
<img width="541" alt="screen shot 2018-01-25 at 6 19 59 pm" src="https://user-images.githubusercontent.com/7570379/35417849-174dbcdc-01fd-11e8-8286-92bf61fb159e.png">

**Comment by mikekucera** [comment]
Can you send me the framework-cytoscape.log	file in the CytoscapeConfiguration/3 folder please.
