### ISSUE TITLE
EM 3.1 RC2: node color when map is created with 4 GSEA datasets?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#316]
I have created a session with 4 GSEA datasets. When the map is created, all the nodes are light grey although NES is selected in Chart Data. I have to select None in Chart Data and then back to NES to see the colors. Would it not be better to see directly the NES colors?
![screen shot 2018-02-15 at 5 19 26 pm](https://user-images.githubusercontent.com/7570379/36284179-bfbf34fe-1274-11e8-9faa-a1d338f47f3c.png)
![screen shot 2018-02-15 at 5 19 38 pm](https://user-images.githubusercontent.com/7570379/36284184-c204d8c2-1274-11e8-909c-7fc192873d15.png)

**Comment by mikekucera** [comment]
This is a bug in Cytoscape. As a workaround you can click the little refresh button at the bottom of the style section of the enrichmentmap panel
