### ISSUE TITLE
map with multiple datasets: node pie chart , is it possible to place the legend on the EM control panel?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#318]
It took me a while to discover the legend button to be able to see how the datesets are placed on the node pie chart. Would it be  possible to make the legend more accessible? for example by placing it in the control panel?  I also don 't understand why the pie chart order is different from the data set order (on my example below, trt is first and vehicle is second and one the pie chart vehicle is left and trt is right).

![screen shot 2018-02-20 at 2 46 52 pm](https://user-images.githubusercontent.com/7570379/36445887-959f6932-164d-11e8-98b4-ffa267c09646.png)

**Comment by mikekucera** [comment]
I think it starts at 12 o'clock and then goes clockwise around the circle. It seems strange for 2 datasets but if you have many more datasets then it makes more sense.

**Comment by mikekucera** [comment]
Nope its a bug in the legend.

**Comment by mikekucera** [comment]
I don't think there's enough space in the control panel to show the legend and all the other options. I do think there should be a dedicated button or label for opening the legend so its not so hard to find.

**Comment by mikekucera** [comment]
I added a button directly to the style panel that opens the legend. Hopefully that will make the legend easier to find.
