### ISSUE TITLE
RC3 EnrichmentMap Creation Parameters

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#319]
I opened with RC3 a map that I created with RC2 and wanted to check the creation parameters (which FDR I used). I was very happy to discover this option in the menu (not sure if this is a new option) but unfortunately the window was empty (see screenshot)
![screen shot 2018-02-21 at 2 24 11 pm](https://user-images.githubusercontent.com/7570379/36500788-4157a670-1713-11e8-946d-ba5103d1daa3.png)

**Comment by mikekucera** [comment]
Can you send me your session file please.

**Comment by whitleyo** [comment]
Hi,

It appears I've been having this issue with a cytoscape session produced in Cytoscape 3.6.1. Can send .cys file if you'd like.
