### ISSUE TITLE
reloading GSEA session p-value/q-value slider only showing up as p-value slider 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#326]
reloading GSEA session p-value/q-value slider only showing up as p-value slider but when using the session previously(prior to save)  the options were p-value or q-value.
<img width="1299" alt="screen shot 2018-03-16 at 12 07 50 pm" src="https://user-images.githubusercontent.com/3842763/37531625-0f0c140a-2913-11e8-8c0c-40379ba39e28.png">

**Comment by risserlin** [comment]
tried in both cytoscape 3.5.1 and cytoscape 3.6.  - problem in both

**Comment by risserlin** [comment]
link to session : https://www.dropbox.com/s/oyaxy6gx7lv833d/EM_gsea_results_unannotated_v2.cys?dl=0

**Comment by mikekucera** [comment]
I was never able to reproduce this.
