### ISSUE TITLE
eliminate the redundancy of gene set name in EM

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#330]
currently there are 3 node attributes that all show the geneset name - name, EM#_name, EM#_formatted_name.  If possible can we get rid of all but one of those names to get rid of redundancy.

**Comment by mikekucera** [comment]
We are adding a column namespaces feature to Cytoscape 3.7. When that releases we can rename all our columns and remove redundant ones.

**Comment by mikekucera** [comment]
Can't remove the name and shared name columns, those are part of the Cytoscape standard. The EM::Name column I think should remain for backwards compatibility. I removed the formatted name column.
