### ISSUE TITLE
Publication-Ready should only remove gene-set labels but not revert manually defined style

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#331]
The purpose of the Publication-Ready box was to remove the purple background and remove gene-set labels. It should not revert any style added by users such as change in color or node size for example.

**Comment by mikekucera** [comment]
EnrichmentMap manages its own style automatically. If you change any of the options in the style section of the EM panel, including publication-ready, it switches back to the EM1_Visual_Style style and makes changes to that style. If you want to have your own separate style you need to manage it yourself. This issue has come up several times now. Maybe we need to rethink how EM manages the style, but that would be a big change.

**Comment by mikekucera** [comment]
Publication-ready could create a separate style, that way the original style remains untouched.

**Comment by mikekucera** [comment]
I believe this is fixed now. The publication ready option only alters the node label and network background. All other style properties are untouched.
