### ISSUE TITLE
importing attribute table: attributes are only visible for last EM network

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#332]
I have a table that I would like to import as attribute as this represents an additional layer of information. The key is 'shared name' (node table) and keys should match any of the 3 maps I have created in one session. I use the Cytoscape menu bar file --> import --> Table --> File --> To a Network collection. The imported columns are only visible for my third network but not for the 2 first ones. I m not sure if this is a Cytoscape or EM issue. I tried Cytocape 3.6, 3.5 and 3.4 and all gave me the same issue. If this is a Cytoscape issue, please let me know how to report it.
This is a feature I used a lot in the past and I think is important as adding extra layers is a valuable option that Cytoscape offers.
Screenshot: in red , the imported columns

![screen shot 2018-04-18 at 1 36 47 pm](https://user-images.githubusercontent.com/7570379/38948821-9836cc1a-430e-11e8-8e48-dd0e5e6437d0.png)

**Comment by mikekucera** [comment]
The three networks in your screenshot are in separate network collections.

Try this instead...

- File -> Import -> Table -> File
- For **Where to import table data** select **To selected networks only**
- A list of networks is shown, select the three enrichment map networks
