### ISSUE TITLE
building the exact same network from commands or from the interface generates two different networks

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#334]
it seems that when I specify a generic file where the genes are separated with ":" using commands the network is created perfectly.
If I use the same files from gui then it can't parse the genes. 

through command:91 nodes - 78 edges
![screen shot 2018-05-03 at 3 22 24 pm](https://user-images.githubusercontent.com/3842763/39598234-d61c9c84-4ee5-11e8-8d41-8b06f432e49e.png)

though gui: 91 nodes - 5 edges
![screen shot 2018-05-03 at 3 23 45 pm](https://user-images.githubusercontent.com/3842763/39598271-ff8cf884-4ee5-11e8-8582-d1c3c48b5d60.png)

**Comment by mikekucera** [comment]
Can you please send me the data files.

**Comment by risserlin** [comment]
figured out the issue.
