### ISSUE TITLE
issue with generic gene comma delimiter

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#335]
I am trying to create an enrichment map where the nodes are patients (not genesets) and common between patients are sets of pathways.  I created a generic file with gs = patient and genes = comma separated list of pathways.  Some of the pathways have commas in their names so although a network is created some of the pathway names are messed up (and subsequently do not map to my expression file)

Is there away to create my generic file so that EM doesn't get messed up with commas in the pathway names?

**Comment by mikekucera** [comment]
No, there is no way to do this currently. You will have to remove the commas from the pathway names.
