### ISSUE TITLE
unable to generate enrichmentmap. no edges and nodes are shown as NA or html links

### ISSUE THREAD

**Issue by kr25** [BaderLab/EnrichmentMapApp#340]
![help1](https://user-images.githubusercontent.com/40844422/42303541-76c4a5f6-8054-11e8-8a34-1d6405a484e2.PNG)
![help2](https://user-images.githubusercontent.com/40844422/42303546-7bc9f772-8054-11e8-990c-969e6a5a98c8.PNG)
![help3](https://user-images.githubusercontent.com/40844422/42303570-a1c38614-8054-11e8-8f11-c4b954bb7707.PNG)

hi really needed help on  this one. not sure where i missed something out.
So i have followed the instructions to generate GSEA output results
and went on to enrichment map in cytoscape;
(tried both the auto scanning of gsea results folder and manual key in),but 
i end up getting the empty nodes (?) without any edges/ or nodes with html links as shown in the picture.

**Comment by risserlin** [comment]
From your screen shot it looks like you are using msigdb c1 dataset.  The c1 genesets are positional genesets where each geneset contains the genes in a specific genomic region.  A Gene can only be found in a single region (maybe some show up in multiple regions but that is an exception).  The edges are calculated based on overlapping genes so for this dataset there are no genes in common.  Which is to be expected.  Try including more geneset databases(for example the msigdb c2 dataset) if you would like to see the connections.

**Comment by kr25** [comment]
Hi Ruth,

Thanks so much for your prompt reply!
Just to clarify, the extra datasets should be included at the enrichment map stage and not gsea right?
Was wondering, how would we know which are the datasets we should in the enrichment map app?
My aim: visualise the strong edges (pathways) that were enriched after overexpression of a specific gene (with unknown gene functions). I would want to include datasets which can cover the entire human genome (because i dont know which genomic region/pathway will be influenced downstream of the overexpression)

(P.S. I'm a wetlab grad student with close to zero bioinformatics knowledge, and I'm currently learning GSEA and enrichment map on my own as it'll be crucial downstream of my microarray experiments)

thank you very much!

**Comment by risserlin** [comment]
Extra datasets should be included at the gsea stage not the enrichment map stage.  We generally use a collection of geneset files that we compile on a monthly basis that you can download from here: http://download.baderlab.org/EM_Genesets/current_release/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_July_01_2018_symbol.gmt

For a description of our standard protocol check out: https://www.biorxiv.org/content/early/2017/12/12/232835

**Comment by kr25** [comment]
Hi Ruth,
Thank you very much for your kind clarifications and help!
and the paper looks extremely informative, gonna check it out now :)
