### ISSUE TITLE
"pathway.commons.url" linkout URL points to localhost rather than PC Painter 

### ISSUE THREAD

**Issue by jvwong** [BaderLab/EnrichmentMapApp#343]
Upon installation of the app, any enrichment map node linkouts for "Apps > EnrichmentMap - Open Pathway Commons" does not launch the PC Apps Painter, but rather points to `localhost`.

I noticed that the "Edit > Preferences > Properties" for "org.baderlab.enrichmentmap"  has a property "pathway.commons.url" whose value is "http://localhost:3000/paint". I suspect this should be "http://apps.pathwaycommons.org/paint".

**Comment by mikekucera** [comment]
Hi Jeff. Did you have an older development build of EM installed at some point? I was using that URL while I was testing the feature. In the build I sent out last week the URL is set to "http://apps.pathwaycommons.org/paint". But I think the value of that property is staying set to the old value.

Can you try going to the CytoscapeConfiguration folder and deleting the file enrichmentmap.props. Then start Cytoscape and go to "Edit > Preferences > Properties", it should have the correct value.

**Comment by jvwong** [comment]
Sorry I should have included more version info: Yes, previously I had something called EnrichmentMap `3.1.0RC` installed. I uninstalled it, then upgraded to `3.1.0`. 

>Can you try going to the CytoscapeConfiguration folder and deleting the file enrichmentmap.props. Then start Cytoscape and go to "Edit > Preferences > Properties", it should have the correct value.

Yes this worked. I guess we should note this as a potential gotcha for devs/testers. Thanks!
