### ISSUE TITLE
Allow custom colouring for Radial Heat Map Image Chart

### ISSUE THREAD

**Issue by s2hui** [BaderLab/EnrichmentMapApp#347]
Currently, the radial heat map image chart style is not customizable (the colour is always red and blue).  
Please change so that this colouring can be customized like the other image chart types (i.e. colour by data set).
For example:
In the Style area in EM Map, make the Chart Data: NES Columns to be like Colour By Data Set
Then in the Style tab, in Image/Chart 1 -> Graphics -> Charts tab -> Radial Heat Map, should allow selection of predefined colour styles or custom colours.
EM version used 3.1.0
Cytoscape version used:  3.6.1

**Comment by mikekucera** [comment]
We do allow selection from a list of predefined colour styles. There is a combo box on the enrichmentmap panel in the style section.

**Comment by risserlin** [comment]
What about custom colours?  I get so many requests for cutsom colors (by dataset or by radial heatmap)
