### ISSUE TITLE
ColorByDataset - allow user to choose colors

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#354]
Colouring by dataset is very handy feature when multiple conditions are being viewed simultaneously in the EMap app. Used this tool to work with 4 Emaps at once, and had feedback.

1) Would be great if the palette could be easily updated to custom colours (allow users to pick each colour) as people usually select a palette for their various conditions in a project (e.g. lung = pink, heart = orange, kidney = purple). 

Currently one needs to change colour mappings via Node Properties > Paint > Pie chart > change colours. This requires multiple steps. Trial and error is required to understand which numbers map to a particular Emap (e.g. for 4 EMaps, you have 4 coloured squares, but which is 1? And which is 2?). 

One possibility is a button right under "Chart Colours" which directly link to the window for setting pie chart colours.  

2) Also currently, the legend in "Show Legend" doesn't change to reflect "Colour by Dataset" mode. I still see a circle cut into 4 pieces (for 4 Emaps). Perhaps the legend could be a set of coloured circles, labelled by the chart name?

3) Finally, please consider a "divergent" colour palette as the default (perhaps Spectral from Color Brewer). The shades of blues and greens that make the current default are only suitable when the conditions are closely-related. 

Thank you!

**Comment by whitleyo** [comment]
I would like to add that this feature would be very useful if you have to make a set of enrichment maps for very similar comparisons. In my particular case, I'm comparing one geneset's (geneset A) enriched pathways to those of another genesets, each of which we'll call geneset B. The datasets that end up getting loaded in are geneset A + geneset B common pathways (intersection), geneset A unique pathways (setdiff(A,B)), geneset B unique pathways (setdiff(B,A)). So, doing the editing as described by shraddah for several similar comparisons becomes rather cumbersome.

**Comment by whitleyo** [comment]
And the legend doesn't change if you manually change the colors
