### ISSUE TITLE
Enrichment Map GMT error 

### ISSUE THREAD

**Issue by pankajdwid** [BaderLab/EnrichmentMapApp#361]
Hi,
 I used my gene list through g:Profiler to generate the result file and GMT file to utilize in Cytoscape enrichment map plugin. When I used the enrichment map, it always show some "GO term does not match to GMT file" as error.

Please suggest how to resolve this issue.

Thanks,
Pankaj

**Comment by risserlin** [comment]
Hi Pankaj, 
Are you downloading the GMT file from g:Profiler?
Can you send me the first 5 lines of each file?
Thanks,
Ruth

**Comment by pankajdwid** [comment]
The first 5 lines:

1. result file:
GO.ID Description p.Val FDR Phenotype Genes
GO:1903039 positive regulation of leukocyte cell-cell adhesion 2.52E-02
2.52E-02 1
"BAD,FYN,CD74,RUNX3,CD44,AP3D1,PRKCQ,CBFB,PTPRC,ICAM1,GRAP2,NKAP,RASAL3,JAK3,DOCK8,CD5,ITGA4,HSPH1,AP3B1,TESPA1,CD27,PDPK1,HSPD1,RPS3,RUNX1,ZBTB7B,TGFBR2,CCDC88B,STAT5B,SART1,PAK2,LCK,PDCD1,TNF"
GO:0051347 positive regulation of transferase activity 1.69E-02 1.69E-02 1
"BAD,PRKAR2B,SPAG9,FYN,CD74,MRE11A,CD44,PNKP,EIF2AK2,PRKCQ,HACD3,PSEN1,HSP90AA1,PTPRC,TPX2,OSBPL8,CLSPN,HSP90AB1,SIRT1,PABPN1,ADNP,STK24,ACD,STUB1,NBN,EZH2,CCNY,PRKAR1A,MAPK10,SERINC1,PRKAR2A,HSPH1,PTK2B,HNRNPA2B1,TRAF2,CHTF18,DKC1,RAF1,PSRC1,KIDINS220,CCNH,STK26,MAP3K7,DBNL,ABI1,MYC,RPLP1,HNRNPD,PARN,RPS2,PDPK1,WRAP53,MINK1,RPTOR,PRKACB,NAF1,RPS3,RANBP2,PEA15,TGFBR2,CCNL1,DTX3L,CCT2,PLK1,NAB2,GOLGA2,ZEB2,SYAP1,CDK1,PAK2,PRKAR1B,PTPN1,TOPORS,DAXX,HMGN1,LAT,TNF"
GO:0051973 positive regulation of telomerase activity 2.48E-03 2.48E-03 1
"PNKP,PRKCQ,HSP90AA1,HSP90AB1,ACD,HNRNPA2B1,DKC1,MYC,HNRNPD,PARN,WRAP53,NAF1,CCT2"
GO:0009615 response to virus 9.89E-03 9.89E-03 1
"BAD,EIF2AK2,PUM2,POLR3E,UFD1L,NCBP3,ENO1,DDX1,PTPRC,MAVS,UNC13D,SAMHD1,CCDC130,HNRNPUL1,ZC3HAV1,HSPB1,GBF1,C1QBP,STAT1,IVNS1ABP,STMN1,TNFAIP3,TRIM25,BATF3,ILF3,ANKRD17,PUM1,DHX9,HMGA1,PML,IFNAR1,XPR1,RRP1B,ADAR,IFI16,DTX3L,DDX21,SIN3A,CFL1,FOSL1,PRKRA,SETD2,DDX41,PCBP2,TNF,LSM14A"
GO:0051098 regulation of binding 3.24E-02 3.24E-02 1
"KDM1A,SPAG9,RSF1,WAPL,SP100,NUCKS1,PSEN1,GSK3B,ADD1,TFAP4,HSP90AB1,TFIP11,ADNP,ARHGEF7,ACD,STUB1,DOT1L,EIF4G1,ITGA4,SUMO1,STMN1,HJURP,TRAF2,TRIM28,DHX9,FAM129B,NCBP1,RB1,EIF4A3,SNAPIN,MEPCE,PLCL2,EPB41,PEX19,IFI16,DTX3L,NIPBL,PLK1,GOLGA2,TMC8,XIRP1,NMD3,SIN3A,SYAP1,JUN,EIF3C,HSF1,HDAC2,CSNK2B,TMSB4X"

2. GMT file

GO:0046950 cellular ketone body metabolic process HMGCLL1 SLC27A5 BDH2 BDH1
HMGCL AACS OXCT1 HMGCS2 OXCT2 ACAT1 ACSS3
REAC:R-HSA-4086398 Ca2+ pathway PRKG2 GNB2 NLK ITPR1 GNB4 GNG5 MAP3K7 AGO4
FZD3 PRKG1 AGO3 GNG2 TCF7 PRKCA WNT5A PPP3CB PDE6G GNAT2 CTNNB1 MOV10 FZD4
TNRC6B PLCB3 LEF1 GNB1 NFATC1 FZD2 TCF7L1 PLCB1 FZD6 PDE6A GNB3 PLCB2 CAMK2A
GNG4 AGO2 TNRC6A GNB5 TNRC6C WNT11 GNAO1 GNG8 TCF7L2 GNG7 PPP3R1 PDE6B GNG3
PPP3CA GNGT1 GNGT2 GNG12 GNG13 CALM1 GNG11 AGO1 GNG10 ITPR2 ITPR3 FZD5
GO:0050917 sensory perception of umami taste GNAT3 ITPR3 TAS1R1 TAS1R3 GNAT1
CALHM1
GO:1990765 colon smooth muscle contraction KIT
GO:0060611 mammary gland fat development CSF1

**Comment by risserlin** [comment]
Ok.  Thanks.  The files look fine so that shouldn't be happening.  What version of EM are you using?

**Comment by risserlin** [comment]
Did you open the gprofiler results file in excel?  There shouldn't be quotes around the gene list.

**Comment by pankajdwid** [comment]
I am using Cytoscape 3.6.1

And yes, GMT FILE  i opened in Excel.

**Comment by risserlin** [comment]
try re-downloading the two files from gprofiler and then creating the the EM without opening either file in excel. Excel can really mess up the file formatting.

**Comment by pankajdwid** [comment]
I got the same error again. Please see scree shot.
![em error](https://user-images.githubusercontent.com/46572449/50990638-2eab9900-14d8-11e9-9907-136e70a69e21.jpg)

**Comment by risserlin** [comment]
Ok.  I think I figured out the issue.
In g:profiler are you using all three types of GO (I.e. BP, MF and CC)?
The pathways.NAME.gmt file from g:profiler contains on GO:BP and Reactome.  The term it can't find is a GO molecular function term and is not in the gmt file you are using.

If you want to use all three divisions of GO in the analysis you need to create a new gmt file that 
has all of GO and pahtways.  
To do that you can concatenate hsapiens.GO.NAME.gmt and hsapiens.GO.pathways.gmt.  for example from the command line:
cat hsapiens.GO.NAME.gmt and hsapiens.GO.pathways.gmt.> hsapiens.GO.and.pathways.gmt 

Alternately, you can re-run gprofiler and unselect MF and CC in the g:profiler options.

**Comment by pankajdwid** [comment]
Thanks  and it seems that deselecting MF and CC worked. 
However, t
![networ output](https://user-images.githubusercontent.com/46572449/50991614-ae3a6780-14da-11e9-92eb-d17e708328d6.jpg)
he network output does not look clean, please see attached. Any suggestion on that ?

**Comment by risserlin** [comment]
Try a much more stringent q-value to see what your strongest signals are.

**Comment by pankajdwid** [comment]
Thanks. It did work after using more stringent p-values.

**Comment by pankajdwid** [comment]
Hi,

Except using GSEA or gProfiler, what are the other ways I can generate GMT files using my gene list? I want to use EM for my proteomics data set.

Thanks.

**Comment by risserlin** [comment]
GMT is a generic format - pathway name (tab) description (tab) list of genes  - https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html#gene-sets-file-gmt-file
You can generate them yourself or get them from any source. 
You can also use any enrichment algorithm to calculate the set of pathways.  you just have to format the results into the generic enrichment result file format. https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html#generic-results-files
https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html#examples-of-generic-enrichment-result-files

**Comment by pankajdwid** [comment]
Thanks. For proteomics experiments, where I will have gene names/protein
names, what would be the best resource to generate GMT file given that I
have to use the specific gene list from my proteomics experiment to
generate the GMT file. Could you please suggest few examples.

**Comment by risserlin** [comment]
On our monthly updated gmt files we have gmt files with UniProt accessions:
http://download.baderlab.org/EM_Genesets/current_release/Human/UniProt/
But I would recommend converting your protein identifiers to gene identifiers for enrichment analysis unless your pathway information has specific data on isoforms or post translational states using proteins instead of genes inflates your universe size and can decrease your significance values.
