### ISSUE TITLE
No EM integration with GeneMANIA, Pathway common etc.

### ISSUE THREAD

**Issue by Alteroldis** [BaderLab/EnrichmentMapApp#365]
Gentoo 64x
Java-1.8
Cytoscape-3.7.1 (from *.jar, from installer and archive, indifferent)
EM-v3.1
No field with other apps, although they are installed (I tried to install them before and after installation of EM). Screenshot attached. I run EM with files from official tutorial.

![screenshot_20190204_193159](https://user-images.githubusercontent.com/8296424/52200117-9aa0d780-28b3-11e9-8a40-98584c965366.png)
![default](https://user-images.githubusercontent.com/8296424/52199783-c1aad980-28b2-11e9-89c5-70ad7a9dc4cc.png)

**Comment by mikekucera** [comment]
The GeneMANIA integration will be available in EnrichmentMap version 3.2 which will be available any day now. The documentation site has already been updated to include the new features in 3.2.  As soon as 3.2 is released just upgrade to it and the new features will be available. Sorry for the confusion.

**Comment by mikekucera** [comment]
EnrichmentMap 3.2 is now available on the app store
