### ISSUE TITLE
Black boxes surrounding EM nodes in Inkscape

### ISSUE THREAD

**Issue by rosscm** [BaderLab/EnrichmentMapApp#367]
After grouping text box with EM nodes (created in v.3.6.1) in Inkscape, black boxes appear around every node.
![Screen Shot 2019-04-04 at 1 58 55 PM](https://user-images.githubusercontent.com/16708715/55577537-ce488400-56e1-11e9-95b4-fba6f3172ac7.png)

**Comment by risserlin** [comment]
Did you import an svg or a pdf into inkscape?  (I use autodesk graphic and I haven't seen this issue)

**Comment by shraddhapai** [comment]
I routinely export svg from Cytoscape into Inkscape and don't see these
boxes.

**Comment by rosscm** [comment]
I imported an svg

**Comment by risserlin** [comment]
@shraddhapai do you group text boxes with nodes?
The grouping is probably including some underlying additional layer.  Cytoscape exports many layers.  I try and remove some of them right off the bat so they don't cause issues later.  
What is the purpose of the grouping?

**Comment by rosscm** [comment]
The grouping was to for me to move the text and EM cluster together - even after ungrouping this square layer remains visible. I will look through the inkscape help forum to resolve. Thanks Ruth
