### ISSUE TITLE
Add important info to DAVID file type in documentation

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#370]
Add to the David enrichment results file that the fdr value we import into EM is taken from the Benjamnin column and not from the FDR column. 

Also, add that if you want to use a different corrected p-value all you have to do is swap the benjamini column with one of the other options in david file (Bonferoni or FDR)

https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html

**Comment by mikekucera** [comment]
https://github.com/BaderLab/EnrichmentMap_docs/commit/724e23794101ffe426b4145307fdd4e04ab49bc0
