### ISSUE TITLE
Add documentation on mastermap (and missing automation commands) to readthedocs

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#373]
expand documentation for available commands (mastermap, post analysis...)
https://enrichmentmap.readthedocs.io/en/latest/Automating.html

**Comment by mikekucera** [comment]
The readthedocs page just points to the swagger docs. I added a lot to the swagger documentation for all of the commands. If that is not sufficient please reopen this issue.

**Comment by risserlin** [comment]
Is it difficult to duplicate the swagger documentation in the readthedocs?  It is difficult to direct people to the documentation through email or on cytoscape-helpdesk if they can only access it when cytoscape is open from within the application.

**Comment by mikekucera** [comment]
No I can do it.

**Comment by mikekucera** [comment]
https://github.com/BaderLab/EnrichmentMap_docs/commit/c39d1e48baa0d735f5a15c93f5c1a7a50f822f5f

https://enrichmentmap.readthedocs.io/en/latest/Automating.html
