### ISSUE TITLE
Add regular expression parameter to mastermap command

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#374]
Add the ability to select a subset of folders in the given directory to create a mastermap.  For example, filter_by = "heart", only directories in the given directory where the names contains the word heart will be included in the mastermap.

**Comment by mikekucera** [comment]
I think its more intuitive to use the glob syntax that you typically use on the command line. For example if you want folders that start with gprofiler you would put `pattern="gprofiler*"`. The equivalent regular expression would be `^gprofiler[^/]*$`.
