### ISSUE TITLE
Providing information about the license EnrichmentMapApp is under

### ISSUE THREAD

**Issue by Alex-Temny** [BaderLab/EnrichmentMapApp#375]
hi.
I'd like to know what license EnrichmentMapApp is under. 
I can't find this information nowhere (neither on http://apps.cytoscape.org/apps/enrichmentmap nor on http://www.baderlab.org/Software/EnrichmentMap). 
Maybe it's also possible to add this information to EnrichmentMapApp GitHub repository.
I'll be thankful for that

**Comment by mikekucera** [comment]
Created LICENSE.md file
