### ISSUE TITLE
Nodes from DAVID Chart appear as Category

### ISSUE THREAD

**Issue by gaelanm** [BaderLab/EnrichmentMapApp#380]
I have downloaded the .txt from DAVID analysis, however, the resulting network on EnrichmentMap has all of the nodes labeled as the categories such as "GOTERM_CC_DIRECT", "UP_KEYWORDS", "INTERPRO", etc.

**Comment by risserlin** [comment]
I am not sure why it is grabbing that column for the node name.  We will look into it.  It is easy to fix though.  
In the style panel you just have to change the what column is being used for the node label.  (for documentation on it see here: http://manual.cytoscape.org/en/stable/Styles.html)

Change the the Label from GS_Descr to Formatted_Name to see better node labels 

<img width="393" alt="Screen Shot 2019-11-07 at 5 45 20 AM" src="https://user-images.githubusercontent.com/3842763/68382818-7ca62300-0122-11ea-9fc5-3cccdb34b111.png">

**Comment by mikekucera** [comment]
EM has been using the GS_DESCR column for node labels for a very long time, and there is a simple workaround. Please reopen this issue if this should be changed.

**Comment by risserlin** [comment]
The issue is that David input is actually a special data type.  It is not in Generic EM format.  This has not always been an issue.  The David input format must have changed slightly.  The David data parser needs to updated so that it associates the right column with the GS_DESCR.

**Comment by mikekucera** [comment]
Ok, no problem.
