### ISSUE TITLE
Multiple points error message

### ISSUE THREAD

**Issue by marcomontagner** [BaderLab/EnrichmentMapApp#383]
Hi, 
I keep receiving this message when creating an EM with EM v3.0.0. in Cytoscape 3.7.2 in MacOS Catalina. I've already successfully created other EM before and I could build one with files generated and processed in the same GSEA analysis, but with a specific set of files I keep getting the message:
Building Enrichment Map
Parsing Bingo Enrichment Result file
multiple points

what could be the issue?
thanks a lot for the help and support!
Marco

**Comment by risserlin** [comment]
Would you mind sharing your enrichment results file with me so I could try it out?  Are these GSEA results files or Bingo files?  I don't think I have ever encounter that error before. 
Thanks, 
Ruth

**Comment by marcomontagner** [comment]
Hi Ruth

Sure! These are results with gsea

Thanks a lot!

marco

 

 

Would you mind sharing your enrichment results file with me so I could try it out? Are these GSEA results files or Bingo files? I don't think I have ever encounter that error before.
Thanks,
Ruth

**Comment by risserlin** [comment]
Is this using the GSEA 4.0.2 or GSEA 3.0?
Did you attach the file to github?  If it won't let you attach it then please send it to me are ruth dot isserlin at utoronto dot ca
Thanks, 
Ruth

**Comment by risserlin** [comment]
Hi Marco, 
Unfortunately it looks like one of the columns in your file have got corrupted (maybe from using it a program like excel or something similar) . In the GSEA results file the NES value seem to have two decimal points.  For example -7.264.658 instead of -7.264658.  Do you by any chance have the original GSEA file?  You can manually go through the file and fix everyone but I can't seem to easily fix them all in one go.
Thanks, 
Ruth

**Comment by marcomontagner** [comment]
Hi Ruth

You are totally right and I don’t know how that happened because to avoid that I didn’t open the file with excel, anyway, that’s the problem, don’t worry, I’ll fix it myself and get back to you if it doesn’t work. I don’t have the original files unfortunately…

Thanks

marco

 

Hi Marco,
Unfortunately it looks like one of the columns in your file have got corrupted (maybe from using it a program like excel or something similar) . In the GSEA results file the NES value seem to have two decimal points. For example -7.264.658 instead of -7.264658. Do you by any chance have the original GSEA file? You can manually go through the file and fix everyone but I can't seem to easily fix them all in one go.
Thanks,
Ruth
