### ISSUE TITLE
How can I tell which column in the "Dataset_Chart" in the node table refers to which dataset?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#384]
the Dataset_Chart is a list of boolean values indicating if the given pathway is found in a dataset.  How can I figure out programmatically (through cyrest) which index refers to which dataset?

**Comment by mikekucera** [comment]
It appears the datasets in the main panel are sorted alphabetically. The list in the Dataset_Chart column is in the same order. There is no way to get the dataset ordering via CyRest, for now you can use the same sorting in your script.

**Comment by risserlin** [comment]
Thanks, that is what I assumed but would be better if it was defined.  is there a way to encode them in the cytoscape list object.

**Comment by mikekucera** [comment]
I don't think so.
