### ISSUE TITLE
gmt upload failed at create Enrichment map validation step 

### ISSUE THREAD

**Issue by cagenet** [BaderLab/EnrichmentMapApp#389]
Dear all,
I'm not sure to be at the right place to get some help but I'm trying and sorry if it disturb. 
I'm following the very nice protocole published in Nat Protoc 2019 : Pathway Enrichment analysis and visualization of omics data using g:Profiler, GSEA, Cytoscape and EnrichmentMap. 
I'm using the supplemental files provides in this article. 
![image](https://user-images.githubusercontent.com/39303168/72548659-6f7a8280-388f-11ea-86a7-1d8e220dc6a5.png)

At step : "Visualization of enrichment results with EnrichmentMap" I encountered the following error  after clicking the build button in EnrichmentMap apps from cytoscape.
![image](https://user-images.githubusercontent.com/39303168/72548633-61c4fd00-388f-11ea-9618-e4f7706ae338.png)
As I had the same error with my own dataset (that's why, in a second time I used the supplementary files provided). I was wondering if there was an error whith EnrichmentMap apps in cytoscape. 
My gmt file looks like 
![image](https://user-images.githubusercontent.com/39303168/72548838-d4ce7380-388f-11ea-8115-5900ccbfa9ad.png)
I have Cytoscape v3.7.2 and all my apps are uptodated.
Thank for your help.

**Comment by risserlin** [comment]
The gmt file associated with that analysis looks like it is incorrect.  

This file should work:
http://download.baderlab.org/EM_Genesets/June_01_2017/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_June_01_2017_symbol.gmt

**Comment by cagenet** [comment]
Well thank.
I didn't explain it correctly sorry.
 The gmt file attached on gitub is the ones from my data. For the supplementary files I used the human one whom correspond to the link you send me. It was just to show you that my files are ok. Thank you.



Envoyé depuis mon smartphone Samsung Galaxy.



-------- Message d'origine --------
De : Ruth Isserlin <notifications@github.com>
Date : 16/01/2020 19:11 (GMT+01:00)
À : BaderLab/EnrichmentMapApp <EnrichmentMapApp@noreply.github.com>
Cc : Carine Genet <carine.genet@inrae.fr>, Author <author@noreply.github.com>
Objet : Re: [BaderLab/EnrichmentMapApp] gmt upload failed at create Enrichment map validation step  (#389)


The gmt file associated with that analysis looks like it is incorrect.

This file should work:
http://download.baderlab.org/EM_Genesets/June_01_2017/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_June_01_2017_symbol.gmt

-

**Comment by cagenet** [comment]
Hi
Sorry I didn't explain correctly sorry.
I used two datasets : mine and the ones provided as supplementary files in Nat protoc. With my data the enrichment map failed. So I used the supplementary files and obtained the same error.
Thank you



Envoyé depuis mon smartphone Samsung Galaxy.



-------- Message d'origine --------
De : Ruth Isserlin <notifications@github.com>
Date : 16/01/2020 19:11 (GMT+01:00)
À : BaderLab/EnrichmentMapApp <EnrichmentMapApp@noreply.github.com>
Cc : Carine Genet <carine.genet@inrae.fr>, Author <author@noreply.github.com>
Objet : Re: [BaderLab/EnrichmentMapApp] gmt upload failed at create Enrichment map validation step  (#389)


The gmt file associated with that analysis looks like it is incorrect.

This file should work:
http://download.baderlab.org/EM_Genesets/June_01_2017/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_June_01_2017_symbol.gmt

-

**Comment by risserlin** [comment]
If you replace the gmt for the supplementary files does the supplementary files work on their own now?

**Comment by risserlin** [comment]
When you run just your data what is the error that you get?

**Comment by cagenet** [comment]
It works with the gmt file you send me. thanks a lot so I have to look what's wrong with my files. thank you so much
