### ISSUE TITLE
EMap 3.1.0 - Fill colour customization gets overwritten

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#392]
I'm creating an EMap in Cytoscape 3.7.2
I set fill color to 'Continuous Mapping' and used an RColorBrewer palette at first (great feature by the way - thank you!). 
I then tried to change the stop points to customize this gradient (e.g. if score < X1, make it yellow ; if  X1 < score < x2, make it orange, etc.,).
When I then click "OK" my changes get reset.
When I open the "Continuous Mapping Editor for Node Fill Color" again, the stop points disappear.

**Comment by mikekucera** [comment]
Cannot reproduce.
