### ISSUE TITLE
when a geneset is empty an edge is created from it to all genesets

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#397]
creating an EM with just a gmt file.

<img width="508" alt="Screen Shot 2020-02-26 at 4 26 54 PM" src="https://user-images.githubusercontent.com/3842763/75389673-ed7d7080-58b4-11ea-8f67-9465b817cce0.png">

ex_rand_subtype_2 is an empty geneset

file used to create EM
[combinded_pathways.gmt.txt](https://github.com/BaderLab/EnrichmentMapApp/files/4258230/combinded_pathways.gmt.txt)

**Comment by mikekucera** [comment]
If a geneset is empty should it even have a node?

**Comment by risserlin** [comment]
Yes. For my use case.  It might be empty in one "species" but populated in another.

**Comment by mikekucera** [comment]
Ok, the fix I committed yesterday keeps the node. The problem was division by zero when calculating overlap. I just added a check for that. Thanks.
