### ISSUE TITLE
EM3.3 beta: color by "all" datasets when only one or 2 datasets out of 3 are checked

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#405]
I have created an enrichment map with 3 gsea results.
In style, I have checked "color by dataset" and I see 3 colors in the nodes.
When I just want to visualize the results of 2 out of the 3 datasets, I still see  3 colors in the nodes instead of 2 (same when i want to visualize just 1 dataset).
 
<img width="1096" alt="Screen Shot 2020-03-24 at 9 54 06 AM" src="https://user-images.githubusercontent.com/7570379/77433252-8a003900-6db5-11ea-9342-df9566906985.png">

**Comment by mikekucera** [comment]
This is a new feature. It will currently hide nodes that are not in any of the selected datasets, but it doesn't update the chart yet. It will have to rewrite the data in the Dataset_Chart column.
