### ISSUE TITLE
Building GEM in Cytoscape from gProfiler .txt -->Error>"parsing generic result file"  

### ISSUE THREAD

**Issue by moutazhelal** [BaderLab/EnrichmentMapApp#414]
Thank you for making a great App.
I have tried to established a  GEM in Cytoscape out of a .txt. file I obtained from gprofiler 2 R package using this code. 

`gostres0 <- gost(query = rownames(sc_C0_markers), 
                organism = "mmusculus", ordered_query = TRUE, 
                multi_query = FALSE, significant = TRUE, exclude_iea = TRUE, 
                measure_underrepresentation = FALSE, evcodes = TRUE, 
                user_threshold = 0.05, correction_method = "g_SCS", 
                domain_scope = "annotated", custom_bg = NULL, 
                numeric_ns = "", sources = "GO", as_short_link = FALSE)
sc_C0gprofiler_results <- gostres0$result

 Order the results by p-adjusted value
sc_C0gprofiler_results <- sc_C0gprofiler_results[order(sc_C0gprofiler_results$p_value), ]
gostplot(gostres0, capped = TRUE, interactive = TRUE)
p0 <- gostplot(gostres0, capped = TRUE, interactive = FALSE)
pdf("sc_C0__gplot.pdf", width = 11, height =11 )

publish_gostplot(p0, highlight_terms = sc_C0gprofiler_results$term_id[1:19], 
                       width = 20, height = 20, filename = NULL)
 dev.off()
 get the GEM file for cytoscape
 gem0 <- gostres0$result[,c("term_id", "term_name", "p_value", "intersection")]
 colnames(gem0) <- c("GO.ID", "Description", "p.Val", "Genes")
 gem0$FDR <- gem0$p.Val
 write.table(gem0, file = "c0gProfiler_gem.txt", sep = "\t", quote = F, row.names = F)`

when Building the map I get an error message which states 
"Building EnrichmentMap
parsing generic result file
For input string:
"Lpar1, Ifitmal,Vtn................"
 
Do you have any idea what might be the problem?
Thank you very much
-----------------------------------------------
Cytoscape : Version: 3.8.0
R version 3.6.3 (2020-02-29)

**Comment by risserlin** [comment]
At the minimum I think that the GEM file requires a pvalue and fdr value.  (ie. it needs Name, description, pval, FDR) but it looks like you are only giving it the pvalue.  I know that in the case of gprofiler the fdr is the pvalue but I usually just duplicate the value and put the pvalue in both the 3rd and 4th column.
