### ISSUE TITLE
Add sequential color palette to visualize q and p values on the EM network

### ISSUE THREAD

**Issue by scaramonche** [BaderLab/EnrichmentMapApp#418]
Hi Mike, 

I am struggling with the visualization of the q and p values on the nodes of the EM network. Since we cannot provide expression data from the stringApp during the import, the nodes are colored based on the FDR or p values. However, all provided color schemas are divergent, i.e. they have three colors with the middle one usually white. However, p/q values can be shown better by using a sequential palette with only two colors and such that small values have stronger color than large values. 

An even more fancy version of the coloring would not use a linear scale, but transfer the (p)values using -log(pvalue) and use these values for the colors.

Best wishes, 
Nadya

**Comment by mikekucera** [comment]
It should be possible to work around these limitations using the Cytoscape API. 

First run the command 'enrichmentmap chart data=NONE' to remove the divergent color scheme.
Then use the VisualMappingManager to get the Style for the EnrichmentMap network, remove the mapping for the Fill Color visual property, then add a new mapping with any color gradient you like.

I don't think Cytoscape supports log scales for mappings. To achieve that you would have to calculate the color values for each individual node and set the values as bypasses (using View.setLockedValue(...)).

**Comment by scaramonche** [comment]
I will try your suggestion. However, the main issue I see with it is the correct timing. I need to wait until the EM network and style are created to be able to change the style and I am not sure how to do that if it is possible at all. 

Have you considered adding more palettes to support better visualization of the pvalues/FDR values or do people use such coloring so rarely that it is not worth it?

**Comment by scaramonche** [comment]
OK, after discussing with Lars, we decided not to try to overwrite EM style and so on.

However, I still struggle a bit to understand what is visualized and how (see attached screenshot). The two nodes (terms) selected in the network have white and red color - the white node has a smaller qvalue than the red node. Then, there is the legend, which shows a color gradient and implies that small qvalues are red and large qvalues are white. Or is this legend not for the qvalues?

<img width="1440" alt="Screen Shot 2020-07-28 at 10 42 07 AM" src="https://user-images.githubusercontent.com/4655368/88693494-a283b580-d0ff-11ea-8ecc-09d241645b69.png">

**Comment by scaramonche** [comment]
After digging a bit more, I realized that the main fill color comes form a Graphics image. However, I wish I would be able to at least see which colors are chosen, but it doesnt seem possible. I attach a screenshot, where I clicked on the Image/Chart 1 in the EM visual style and in the graphics dialog it only says "Radial heat map (by EnrichmentMap)". Is that a bug that one cannot see or edit anything? 

<img width="1308" alt="Screen Shot 2020-07-29 at 3 56 30 PM" src="https://user-images.githubusercontent.com/4655368/88809339-4fb80580-d1b4-11ea-95fd-3e7dc9cdc0a9.png">

**Comment by mikekucera** [comment]
The legend appears to have a bug, its showing the gradient backwards.

The radial heat map is a custom chart that's only used by EnrichmentMap, and is automatically created as part of the style. It wasn't intended to be edited manually so it doesn't have a UI.

I was hesitant to add more color schemes because it won't be backwards compatible with previous versions of EnrichmentMap. But if thats the best option for you then I can take a look at what it would take to make it work.

**Comment by mikekucera** [comment]
Could you please provide an example of a color scheme you'd like to use.

**Comment by scaramonche** [comment]
Thanks for the info and fixing the bug with the legend!

I think any color schema that basically goes from a color to white would work (see the example palettes from CB). I think the important part would be to have the inverse colors, i.e. that small p-values have more color than large p-values. 

<img width="554" alt="Screen Shot 2020-08-12 at 12 42 05 PM" src="https://user-images.githubusercontent.com/4655368/90006765-d29f8c80-dc99-11ea-8e4a-f90ede3839c8.png">

Here I choose black to white and put the middle point to a rather small p-value (0.00001) and a rather light color (third color from top to bottom in the palette). The image you see from the color editor is before I press OK for the value of the middle point, since it goes all the way to the left once I press OK. I am not sure what is the best strategy for adjusting the colors automatically. 

<img width="668" alt="Screen Shot 2020-08-12 at 12 45 18 PM" src="https://user-images.githubusercontent.com/4655368/90006786-dcc18b00-dc99-11ea-90a1-d6adffbb56a2.png">
 
And then it can look like this: 
<img width="696" alt="Screen Shot 2020-08-12 at 12 50 13 PM" src="https://user-images.githubusercontent.com/4655368/90007095-67a28580-dc9a-11ea-8f26-f7c05aa1b1ec.png">

**Comment by scaramonche** [comment]
Just a note to that. I think it would be a nice functionality to have, but I know backwards compatibility is very important. So, I would not insist on it for the stringApp if it is too complicated. We have another idea of how to get a better visualization coming from a stringApp enrichment, but I will create another issue about that.
