### ISSUE TITLE
Provide numerical (gene/protein) data from columns in a network as arguments in the build-table command

### ISSUE THREAD

**Issue by scaramonche** [BaderLab/EnrichmentMapApp#419]
Hey, 

It would be great if we could provide expression data from columns of the node table of a (STRING) network as input for EM. We often have STRING networks with expression data or if not that, with some other numerical data such as disease scores, compartments and tissue scores, etc. Would it be possible to provide EM with 1 to N columns with data that can be used for the EM visualization in the Table panel?

Thanks, 
Nadya

**Comment by mikekucera** [comment]
Hi Nadya,

I have added parameters to the build-table command that allow expression data to be loaded from a second table. Here's an example of what the command looks like:

`enrichmentmap build-table table="STRING Enrichment: All" genesColumn="genes" nameColumn="description" pvalueColumn="FDR value" coefficients=JACCARD similaritycutoff=0.5 networkName="MyNetwork" exprTable="String Expression" exprGeneNameColumn="Gene" exprDescriptionColumn="Description" exprValueColumns="E1,E2,E3,E4" filterByExpresssions=false`

**Comment by scaramonche** [comment]
OK, so I did the following (using the latest EnrichmentMap version from github):
1) Created a string network for Alzheimer's disease and ran enrichment on it
2) Executed the command: 
`enrichmentmap build-table table="STRING Enrichment: All" genesColumn="genes" nameColumn="description" pvalueColumn="FDR value" coefficients=JACCARD similaritycutoff=0.5 networkName="MyNetwork" exprTable="String Network - Alzheimer's disease default network" exprGeneNameColumn="display name" exprDescriptionColumn="stringdb::description" exprValueColumns="stringdb::diseases score" filterByExpressions=false`

However, I get the following error. 
`Error handling command "Column 'display name' is invalid for argument 'exprGeneNameColumn'.`

I think it might be because the argument contains space or something else unexpected. If I only use "name" for the exprGeneNameColumn argument, I get a similar Error then for description and for exprValueColumns. Any suggestions? Do I need to escape it in some way? Or do you need to change it to accept more than just one word?

**Comment by scaramonche** [comment]
Small follow-up: I also tried to rename the column names into single words and executed the command:

`enrichmentmap build-table table="STRING Enrichment: All" genesColumn="genes" nameColumn="description" pvalueColumn="FDR value" coefficients=JACCARD similaritycutoff=0.5 networkName="MyNetwork" exprTable="String Network - Alzheimer's disease default network" exprGeneNameColumn="display" exprDescriptionColumn="description" exprValueColumns="dscore" filterByExpressions=false`

But this didint work either: 

`Error handling command "Column 'display' is invalid for argument 'exprGeneNameColumn'.`

**Comment by scaramonche** [comment]
Update: I figured out that the issue was with the network name I provided. Somehow that did not get recognized. It worked from the commands, when I used "* shared node" where * is the current node table number. Any idea why? 
Since I use the SUID in the stringApp code, it worked fine with that.

**Comment by mikekucera** [comment]
I'm not sure. It validates the table name before it validates the column names. Are you able to send me your session file?

**Comment by scaramonche** [comment]
No need. I checked again and the issue was me trying to use the default network table and not the node one.

**Comment by scaramonche** [comment]
I think it works fine! Thanks for adding this!
Nadya

**Comment by mikekucera** [comment]
No problem. I'm happy to help.
