### ISSUE TITLE
Cluster merge/extract error

### ISSUE THREAD

**Issue by funnell** [BaderLab/EnrichmentMapApp#42]
When I perform automatic annotation, select a cluster and click on the "extract" button, I get an error:

> Argument: 'nodesToUse isn't applicable to command: 'wordcloud create'

Then nothing happens.

Cytoscape 3.2 BETA1
EnrichmentMap 2.0.2

**Comment by funnell** [comment]
I see the same error when merging clusters, but the clusters are merged anyways

**Comment by risserlin** [comment]
fixed in latest version of EM 2.1.0 (Beta 1)
