### ISSUE TITLE
issue with EM sliders and post analysis on computer using French keyboard

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#420]
commas are used as decimals. 
moving the sliders causes it to jump to NA immediately and gets rid of network

Can't load in a file for post analysis unless you set the cutoff to 1.  Any other value less than 1 won't work. 

EM 3.3, java 11, reproducible on windows or Mac with french canadian keyboard.

![signaturegeneset](https://user-images.githubusercontent.com/3842763/88689404-713bc300-d0c8-11ea-9f17-77df8d72e28b.JPG)
<img width="545" alt="Capture d'écran 2020-07-28 10 14 07" src="https://user-images.githubusercontent.com/3842763/88689472-8153a280-d0c8-11ea-9a0b-5a893ed44288.png">

**Comment by mikekucera** [comment]
Tested fix with French-Canadian locale on Mac.
