### ISSUE TITLE
Provide column with NES values in the build-table command

### ISSUE THREAD

**Issue by scaramonche** [BaderLab/EnrichmentMapApp#421]
Hi Mike, 

Would it be possible to also add an argument to the build-table command to import NES values from a given column? And if this column is provided that the default coloring is the one using NES values? 

The idea would be for us to create our own NES values so that we can make better use of the default coloring. After a lengthy discussion with Lars, we decided that this would make most sense for the enrichment results from the stringApp. 

Thanks, 
Nadya

**Comment by mikekucera** [comment]
Let me know how well this works for you. I can still do something to solve #418 if needed.

**Comment by scaramonche** [comment]
The import of the NES values works fine, thanks! Would it be possible to apply the NES coloring by default if NES values are provided? 

I tried running the chart command after the build-table command, but I can't make it work. The task is either ran before the network is there or Cytoscape gets into a weird endless loop of creating an EM network after another, when I use a task observer.

**Comment by scaramonche** [comment]
Great, thank you!
