### ISSUE TITLE
Bug in node size mapping for gs_size

### ISSUE THREAD

**Issue by scaramonche** [BaderLab/EnrichmentMapApp#422]
It looks like the values for the node size mapping based on the EnrichmentMap::gs_size are hard-coded or there is a bug in the way they are determined. I had an issue for both the networks based on the stringApp enrichment as well as for a network using some sample data from gProfiler. I attached a screenshot where I can see that the expected value range is between 10 and 474, while the actual values go only between 2 and 94 (the node table is sorted based on the gs_size column). 

<img width="1407" alt="Screen Shot 2020-08-12 at 3 10 14 PM" src="https://user-images.githubusercontent.com/4655368/90018941-fe2c7200-dcad-11ea-92a2-61fe59d7f7fd.png">

**Comment by mikekucera** [comment]
@risserlin Hi Ruth, Do you know if there's a reason the node size mapping is hardcoded to go from 10 to 474? I think if you were creating several EM networks then the node sizes would be consistent between the networks, but that's just me guessing. Thanks.

**Comment by risserlin** [comment]
@mikekucera those are random numbers to choose though.  It would make more sense if the values were 15 -500 which were the original geneset size threshold we used to use.  There is something to be said for having it as a defined value because if it is set to 94 for one network and 500 for another network then nodes that are the same size in the two networks will actually have very different values.

**Comment by scaramonche** [comment]
I understand and that makes sense. However, I would much prefer if you put the lower bound to 2 and not to 15 since in the stringApp (but also other enrichment tools), we can get terms of size 2. Then the mapping will still work.

**Comment by mikekucera** [comment]
How about we change the values to be 2-500 then? It would create a slight inconsistency with networks created in earlier versions of EM, but I don't think anyone would actually notice.

**Comment by mikekucera** [comment]
Ok, I changed the mapping range to 2-500
