### ISSUE TITLE
Filtering network should filter "color by dataset" pie slices

### ISSUE THREAD

**Issue by klevdiamanti** [BaderLab/EnrichmentMapApp#423]
When importing GSEA datasets with a filtering Q-value X (e.g. 0.1) and then decide to use the in-network filter for Y, where Y < X (e.g. 0.01), the nodes that contain instances from datasets that do not fulfill the new filtering criterion are not removed.

The setup that brought me across this issue is the following:
1. Import 5 GSEA datasets and initially filter on q=0.1
2. Color nodes by dataset so that every node is a pie-chart colored by dataset
3. Filter on q=0.01

When the last filtering is applied (step 3) pie-slices that do not fulfill the 0.01 filtering criterion are not removed. To get around this I had to recreate the networks and filter on 0.01 from the data import step (step 1). I am not entirely certain if this is intentional or a bug, but it feels more like a bug to me.

**Comment by risserlin** [comment]
Which filtering are you using?  Are you using cytoscape's filter tab or are you using the q-value slider bar that is in the EM panel?

**Comment by klevdiamanti** [comment]
I am using the q-value sliding bar from EM.

**Comment by risserlin** [comment]
Sorry another question, When you say pie slices are not removed, is your network "Colored by Dataset"? (the pie slice won't be removed for p-value or q-value but if you have it color by dataset then it should be removed.  
(If it is colored by dataset then this definitely sounds like a bug but might be worked around if you apply the filter and then change the coloring to p-value/q-value and then back to color by dataset might refresh the view.)

**Comment by klevdiamanti** [comment]
Precisely, my network is colored by dataset, so I was expecting "slices" to be removed but it did not happen.

My workaround was that I filtered with the q-value of interest from the beginning that I imported the data, and it worked. I decided to report this just in case.

**Comment by risserlin** [comment]
Ok.  So definitely a bug :)
Did you try the changing the coloring to p-value/q-value and then back to "color by dataset"?  Did that hack work?

**Comment by klevdiamanti** [comment]
Just tested that and it does not seem to be working either.

**Comment by risserlin** [comment]
Ok.  Shame.  I am not sure how to trigger the recalculation of the color by dataset.  There might not be any hacks.  @mikekucera are there any ways around this bug in the meantime?

**Comment by mikekucera** [comment]
No, I have to fix it.

**Comment by klevdiamanti** [comment]
Hi guys. Have you pushed this update to the Cytoscape App Store or do you plan to do so soon?

**Comment by risserlin** [comment]
It for sure hasn't been pushed to the app store yet.   @mikekucera can you create a build quickly?  (I could also create a build but might take me a bit longer.)

**Comment by mikekucera** [comment]
I'll create a beta build and post it here.

**Comment by mikekucera** [comment]
Here is a build for testing. Please let me know if its not working as expected. Thanks.

https://github.com/BaderLab/EnrichmentMapApp/releases/tag/v3.3.1-BETA1
