### ISSUE TITLE
EM post analysis: all nodes get selected even if only one signature gene-set is selected

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#424]
I tried post analysis on an enrichment map using different parameters. I had then multiple entries for signature gene-sets in the "Data Sets" box. I select one signature gene-set to create a subnetwork of the nodes linked to the signature gene-set but additional nodes are also selected. The additional nodes that are erroneously selected are coming from the additional signature gene-sets (although they were unselected). See screenshots and please let me know if this is unclear. 
<img width="1023" alt="Screen Shot 2020-08-20 at 4 08 17 PM" src="https://user-images.githubusercontent.com/7570379/90821175-77f0db00-e300-11ea-8841-47f98f8ae8da.png">
<img width="1013" alt="Screen Shot 2020-08-20 at 4 08 36 PM" src="https://user-images.githubusercontent.com/7570379/90821188-7f17e900-e300-11ea-9c65-9ef3a1b13266.png">

**Comment by mikekucera** [comment]
Hi, I don't think I'm understanding the problem. Can you please give me more detailed steps to reproduce.

Also if you select nodes that are connected to a gene-set, and then uncheck a dataset in the EM panel, that won't cause previously selected nodes to become unselected.
