### ISSUE TITLE
Error while Building Enrichment Map

### ISSUE THREAD

**Issue by comaxfunk** [BaderLab/EnrichmentMapApp#425]
Hello, 

while trying to build an Enrichment Map the app stops, and displays the following error:
Parsing Bingo Enrichment Result file
For input string: "---"

How can I resolve this?

Thank you for your help!
CF

**Comment by GitHubbit** [comment]
I have the same issue - I am using GSEA enrichment results to build the map, not Bingo/gProfiler...

**Comment by risserlin** [comment]
See issue #432.   hacks around this listed in #432
