### ISSUE TITLE
Pathways not found in GMT (even though they are there)

### ISSUE THREAD

**Issue by s2hui** [BaderLab/EnrichmentMapApp#430]
Hello,

When I try to create an EM using a generic formatted file and GMT (either loaded via common files or in the GMT for the specific data set), I get a popup saying three pathways cannot be found.  I grep'd these pathways in the GMT file and they are present however.
![Screen Shot 2020-10-28 at 11 14 47 AM](https://user-images.githubusercontent.com/10944134/97456364-30458b80-190f-11eb-9b6a-ec25f0f11a01.png)

I'm using GMT file:
http://download.baderlab.org/EM_Genesets/current_release/Human/symbol/Human_GOBP_AllPathways_no_GO_iea_October_01_2020_symbol.gmt

I am running Cytoscape 3.8.1, EM app v3.3.1

shirley

**Comment by mikekucera** [comment]
Those gene sets are not actually present in the GMT file with those exact names. The full name of the first gene set in the gmt file is...

HALLMARK_UV_RESPONSE_DN%MSIGDB_C2%HALLMARK_UV_RESPONSE_DN

The name ends with an '_DN', but in the dialog it appears the enrichment file doesn't have '_DN' in the name.  When you use grep its probably matching the name up to but not including the '_DN', but EnrichmentMap looks for an exact match.
