### ISSUE TITLE
Drugs Targets GeneSets not uploaded for current version

### ISSUE THREAD

**Issue by keremw** [BaderLab/EnrichmentMapApp#433]
Hi,
I tried to download Drugs Targets from the Index of /EM_Genesets/current_release/Human/symbol/DrugTargets and noticed that the files are size 0. Might there be a problem in the update?
Thank you very much in advance,
Kerem

**Comment by risserlin** [comment]
Sorry about that.  Looks like it is currently broken in the build.  I will look into that.  
In the meantime The last working copy is from September and can be found here: http://download.baderlab.org/EM_Genesets/September_01_2020/Human/symbol/DrugTargets/ or for other species follow this link: http://download.baderlab.org/EM_Genesets/September_01_2020

**Comment by keremw** [comment]
Thank you! I will.

**Comment by risserlin** [comment]
The original issue has been fixed and the latest drugbank files can now be found on the download site (The version of drugbank that was associated with the build was actually pretty old but I have now updated it to get the latest version, something that wasn't possible previously.)
http://download.baderlab.org/EM_Genesets/current_release/Human/symbol/DrugTargets/
