### ISSUE TITLE
Enrichment Map JAR file Error

### ISSUE THREAD

**Issue by rohitesh13** [BaderLab/EnrichmentMapApp#434]
Dear Team,

I am trying to install enrichment map plugin on cytoscape but i am unable to do in either way. Firstly, the app manager is not connecting to the internet on cytoscape, which i don't understand why. Secondly, the enrichmentmap JAR file is creating error and not opening. What can be done in this case to install enrichment map plugin ? 

Thanks,
Rohitesh

**Comment by mikekucera** [comment]
Hi Rohitesh, are you still having this problem? Were you able to install EnrichmentMap?

**Comment by rohitesh13** [comment]
Hi Mike,

Yes, i was able to install enrichmentmap. However, i do have an independent
query. If possible, please address.
What additional downstream analysis can be done using gsea result file ?
Any help in this regard would be greatly appreciated.

Thanks in advance,
Rohitesh
