### ISSUE TITLE
Compress in heatmap - all classes defined in expression and class file (irregardless of which phenotypes are being compared)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#436]
User supplies class file and expression file and then indicates two classes they are comparing but expression and class file actually represent multiple classes.  When you collapse the expression only the two classes are seen.  What happened to the rest of the data?  (Is it compressed into the second class or is just ignored) .

In our sample data we have Immuno, mesenchymal, differential and proliferative and generally we just compare immuno and mesenchymal but the rest of the definitions and expression are in the files.  It would be nice all classes defined and in the expression file could be represented when compressing the data.

**Comment by mikekucera** [comment]
The rest of the classes were just being ignored. I've added them back to the heat map. But the 2 classes that are chosen for comparison are shown first.
