### ISSUE TITLE
G profiler results don't import properly

### ISSUE THREAD

**Issue by paraish** [BaderLab/EnrichmentMapApp#439]
First, thank you for developing an excellent tool!

I downloaded the GEM file from G profiler, and used it as input for EnrichmentMap. I also provided the required GMT file for all gene sets. However, in the Node table, I noticed that P values/FDRs/Phenotypes/Genes have all been merged into 1 column, which is displayed in the "Genes"  column. Additionally, there is a new "node" which appears to be the header of my GMT file. I've attached a screenshot below.

Is there some way I can modify the GEM file to allow the data to be properly imported?

Thanks,
Paraish 

![image](https://user-images.githubusercontent.com/34377791/103387758-7e276d00-4ad3-11eb-830f-0cb41157779d.png)

**Comment by paraish** [comment]
Solved the problem - I imported the data into excel, changed the scientific notation to number with a 30 decimal places, which allowed the file to be properly imported.

For what it's worth, I had the "scientific notation" option checked during the Build step, but it didn't help. Only changing the format of the source document worked.

**Comment by paraish** [comment]
I don't think this issue is closed - it requires a workaround where Gprofiler result files are imported into excel to get rid of scientific notation. Excel only allows a maximum of 30 decimal places which is problematic for extremely low p values. One could import the file into R as well, but again, an inconvenient workaround.

The issue notwithstanding, I sincerely appreciate the otherwise excellent and powerful software!

**Comment by risserlin** [comment]
When you first used the GEM file from g:profiler did you open it in any other software?  Can you send me your GEM file so I can try and debug it or alternately your gene list you used in g:proviler?
Thanks,
Ruth

**Comment by mikekucera** [comment]
The "scientific notation" check box only applies to the "p-value", "q-value" and "cutoff" text boxes in the dialog. It does not change the behaviour of the result file parser.

We use the Java method Double.parseDouble() to read in the values. This method does support scientific notation, but the numbers have to be in the Java format. Here is an example: http://www.java2s.com/Tutorials/Java/Data_Types/Java_double_type.htm#Scientific_notation
