### ISSUE TITLE
Not able to annotate clusters after getting an enrichment map

### ISSUE THREAD

**Issue by Kalpanag12n** [BaderLab/EnrichmentMapApp#44]
I am using cytoscape version 3.1.1 and enrichment map version 2.0.1. I created an enrichment map using the David panel. Once the map was obtained, according to the tutorial page here (http://www.baderlab.org/Software/EnrichmentMap/Annotation), for automatically annotating clusters, I am not able to find the option 'Annotate clusters' under Enrichment Map. Please let me know if I am missing something in terms of software versions. 

![cyto-issue](https://cloud.githubusercontent.com/assets/9329440/4712148/f1a339de-58c8-11e4-9748-86aa435351fd.png)

**Comment by risserlin** [comment]
Unfortunately the beta version of the auto annotation feature is only available when using cytoscape 3.2 (which is also currently available in beta version http://chianti.ucsd.edu/cytoscape-3.2.0-beta1/) and Enrichmentmap 2.0.2 or higher.

**Comment by longjunyu** [comment]
very helpful
