### ISSUE TITLE
Painter app gene overlap very poor for supposedly identical pathways

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#442]
Not sure if this is a painter issue or an EM issues. 

Right click on a pathway in EM (for example: INTERFERON GAMMA SIGNALING%REACTOME%R-HSA-877300.1) and launch in pathway commons which open the pathway commons beta painter app. 

pathway commons lists a bunch a pathways that have overlap with the genes associated with this pathway.  
issues:
interferon gamma is not number one.  (EGFR1 is).  The closest match is interferon alpha/beta but there are only 3 genes that overlap with it?
If I do the same search directly on the pathway commons interferon alpha/beta comes up first (but no indication of overlap because not the way the web version works.

**Comment by jvwong** [comment]
Here's what Dylan tried to prioritize search results in the Painter, and maybe you can see the edge cases:

1. Let a gene set (i) be `G_i` and an set of expressed genes in that gene set be `E_i`.
2. Group `G_i` into gene subsets of max size 15 and use these to query PC for pathways
3. For each pathway (j) returned `P_ij`, get the set of genes for that pathway `G_Pij`
4. Calculate the overlap `O_ij` which is the intersection between `G_Pij` and `E_i`
5. Prioritize results by `O_ij`

The chunking of genes into search queries (2) may seem weird but it was a trade-off that we made to be able to accommodate some enormous gene sets that would cripple the search.
