### ISSUE TITLE
GREAT enrichment map with multiple datasets: different number of slides in Color by Dataset or NES columns

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#443]
This issue might be related to the previous one that i reported regarding the legend.
I have created an enrichment of 9 datasets from GREAT output. I was doing some node filterings and I noticed an inconsistency between the number of slices displayed for some nodes depending on if I select Color by Dataset or NES column. When I exported the node table, I could see that for my first dataset (EV1), some FDR values were above the FDR 0.05 threshold that I had selected when created the map but the FDR values were all under 0.05 for the other 8 datasets. Therefore for this first dataset (EV1), some NES columns contained erroneously a "1" for these FDR that were > 0.05 (see screenshots).  I did it twice and consistently got the same issue. But the column EnrichmentMap::Dataset_Chart was correct.
<img width="444" alt="Screen Shot 2021-01-08 at 3 26 48 PM" src="https://user-images.githubusercontent.com/7570379/104061864-5cab3d00-51c7-11eb-9692-5aa51770e9e6.png">
<img width="436" alt="Screen Shot 2021-01-08 at 3 27 35 PM" src="https://user-images.githubusercontent.com/7570379/104061871-60d75a80-51c7-11eb-99a4-207296ce2b8d.png">
<img width="1283" alt="Screen Shot 2021-01-08 at 2 52 50 PM" src="https://user-images.githubusercontent.com/7570379/104061906-70ef3a00-51c7-11eb-9dc3-f11cc651d71c.png">
<img width="821" alt="Screen Shot 2021-01-08 at 2 44 16 PM" src="https://user-images.githubusercontent.com/7570379/104061919-78164800-51c7-11eb-9d40-fb3d45ffb9af.png">

**Comment by veroniquevoisin** [comment]
I think that I got this one : NES column says that the gene-set is present in the dataset even if this is above the FDR threshold but  the chart dataset indicates which gene-set passed the FDR threshold.

**Comment by mikekucera** [comment]
Yes I think that's right. The color by dataset chart won't show datasets that don't contain the gene set (or the gene set didn't pass the tests for that data set). I'm going to close this issue. Please re-open if I did not interpret the issue correctly.

**Comment by risserlin** [comment]
Is this documented in Docs?  Might be nice to have a section that deals with EM with multiple datasets.  I think more and more people are using a lot of datasets. Might be good to start thinking of features to better enable using EM for many datasets.

**Comment by mikekucera** [comment]
https://enrichmentmap.readthedocs.io/en/latest/Network.html#chart-visualization

**Comment by risserlin** [comment]
but the above discrepancy is not clear from the documentation.  Might be helpful to have an example comparing the charts to the colour by dataset.  Also in the color by dataset it might be helpful to add that colour by dataset reflect significance (defined by the user) but the heatmaps are not dependent on significance and show the NES irrespective of significance.
