### ISSUE TITLE
Add option to colour by significant NES only

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#446]
currently when you color using NES all NES values are used.  If you want to show only significant ones you have to modify your input file to only contain significant values or you have to manually set NES values that are significantly in the node table. 

It would be helpful to have the option in the dropdown  "Significant NES columns" and only colour the node by NES if it passes the significance threshold.

**Comment by mikekucera** [comment]
Hi Ruth, how do I know if an NES value is significant?

**Comment by risserlin** [comment]
If the corresponding p-value and q-value pass the specified thresholds.  There is no specific value where an NES values are significant.

**Comment by mikekucera** [comment]
ok thanks

**Comment by mikekucera** [comment]
Ok I've added the NES significant chart. Ruth can you please test this when you get a chance, to make sure its what you are looking for. If its not working as you expected then please reopen this issue.

**Comment by risserlin** [comment]
Is there a pre-release version I can downloade to try it out?
