### ISSUE TITLE
DAVID/BINGO/Great import gives error "Enrichments file or GMT file is required"

### ISSUE THREAD

**Issue by kjbussey** [BaderLab/EnrichmentMapApp#447]
I am trying to use EnrichmentMap to visualize the Functional Annotation Chart from a DAVID analysis. To make sure that the tool worked, I attempted to load the 12hr_David_Output.txt that you provide as a demo file and received the error: "Enrichments file or GMT file is required." I was under the impression that for DAVID, this file was optional, so this looks like a bug. I'm using version 3.3.1 with Cytoscape version 3.8.2 with Java 11.0.6 by AdoptOpenJDK on Windows 10, version 1909, 64-bit on a machine with 64 GB of RAM. 

[EnrichmentMapApp_bugreport.zip](https://github.com/BaderLab/EnrichmentMapApp/files/5991935/EnrichmentMapApp_bugreport.zip)

**Comment by risserlin** [comment]
You are correct.  With DAVID results you should not be required to specify anything besides the output file. 
I am not able to recreate this issue though.  
When I use the file you supplied I get no error and I get the following EM:
<img width="686" alt="Screen Shot 2021-02-17 at 9 05 53 AM" src="https://user-images.githubusercontent.com/3842763/108215506-66e22480-70ff-11eb-9cf3-7ea46daf29d1.png">

When you try to create an EM with your David file is the analysis type set to "David/Bingo/great" ?

**Comment by kjbussey** [comment]
Yes. However, in testing today after re-booting the computer and re-starting Cytoscape, it loaded fine. Not quite sure what is going on there.

 

 

Kimberly J. Bussey, Ph.D.

Managing Partner, Equinox Technologies, LLC

Assistant Professor, Precision Medicine, Midwestern University

Adjunct Faculty, Mathematical and Natural Sciences, The New College, ASU

Adjunct Faculty, The BEYOND Center for Fundamental Concepts in Science, ASU

Email:  <mailto:kjbusseyphd@gmail.com> kjbusseyphd@gmail.com

Phone: 480-321-7137

My pronouns: she, her, hers

 

“RETHINKING CANCER” IN PRESS:

 

 <https://urldefense.proofpoint.com/v2/url?u=https-3A__mitpress.mit.edu_books_rethinking-2Dcancer&d=DwMFaQ&c=l45AxH-kUV29SRQusp9vYR0n1GycN4_2jInuKy6zbqQ&r=3pdAVk08fQz0zWNcSq9S6uHJfD17DXw-R28SkYJ89G4&m=qrvv8zwKvt_LmycKaGTJEoUwWrnnSSYSXHVcKar_S1A&s=7q5XdABhnu_M5NaGpIlXBKH2CNc-Hx3ACnsXm9QHXuo&e=> https://mitpress.mit.edu/books/rethinking-cancer
