### ISSUE TITLE
Clicking on post anlaysis node does not show heat map

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#450]
clicking on post analysis node in the heatmap panel lists all the genes and their associated ranks but there is no heatmap.
<img width="597" alt="Screen Shot 2021-03-11 at 1 36 10 PM" src="https://user-images.githubusercontent.com/3842763/110837247-fc8c5200-826e-11eb-9972-efe37a272f11.png">

(when you click on the edge you can see the heatmap though)
<img width="549" alt="Screen Shot 2021-03-11 at 1 37 26 PM" src="https://user-images.githubusercontent.com/3842763/110837268-031ac980-826f-11eb-9be2-5be30b0c5a34.png">

**Comment by mikekucera** [comment]
Hmmm, it works with my test data. Can you send me your session file please.

**Comment by risserlin** [comment]
I emailed you an example session file. Thanks.
