### ISSUE TITLE
chart data -> pvalue or q-value colors in the wrong direction

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#452]
If you color your data by p-value or q-value (in drop down of Style panel in EM panel)

The higher p-values or q-values get a stronger red and the lower are lighter but with p-values and q-values we want to accentuate the smaller values.

**Comment by mikekucera** [comment]
Just checking... is it ever possible to have negative p-values or q-values?

**Comment by risserlin** [comment]
no.  p-value and q-value should be in the range from 0 to 1.

**Comment by mikekucera** [comment]
In that case the 'chart colors' combo box should show two colors and not three when p-value or q-value is selected.

**Comment by risserlin** [comment]
white to red?   is it currently set to blue-white-red?

**Comment by mikekucera** [comment]
The first option when p-value is selected is RdBu-3, which shows red-white-blue in the chart color combo. But blue is not used and it currently uses white for 0 and red for the max p-value. I'm thinking it should just show red-white in the combo box and use white for max p-value and red for zero. Does that sound right?

**Comment by risserlin** [comment]
yes.  that sounds right.
