### ISSUE TITLE
Custom fill nodes by dataset

### ISSUE THREAD

**Issue by rosscm** [BaderLab/EnrichmentMapApp#454]
Hi,

I'm attempting to set custom fills for EM nodes but unable to do so.
Two methods tried so far:

1. EM -> **Chart Data = Color by Dataset** -> Style Fill Color (Column = Dataset_Chart; Mapping type = Discrete). This method seems to only affect the border paint, where the preset blue/green colours remain visible.
![EM_1](https://user-images.githubusercontent.com/16708715/112024943-10f00a80-8b0b-11eb-95b5-79a8ec47193d.png)

2. EM -> **Chart Data = None** -> Style Fill Color (Column = Dataset_Chart; Mapping type = Discrete). This method changes the fill colours, but nodes shared by multiple datasets are overridden by a single colour. 
![EM_2](https://user-images.githubusercontent.com/16708715/112025004-1fd6bd00-8b0b-11eb-9aed-af289dffdd74.png)

Is it possible to custom fill nodes by dataset?

**Comment by risserlin** [comment]
What version of EM are you using?

In the latest version of EM there is an option in EM panel to specify the colour:
<img width="369" alt="Screen Shot 2021-03-22 at 12 51 56 PM" src="https://user-images.githubusercontent.com/3842763/112027404-82c95380-8b0d-11eb-85cd-e9f38087cd5e.png">
rs:

**Comment by risserlin** [comment]
I think it was introduce in version 3.3.0

**Comment by rosscm** [comment]
Ohh I see, I didn't try actually clicking the colour boxes to specify custom ones (I'm using EM version 3.3.1 for reference). Thanks Ruth!
![Screen Shot 2021-03-22 at 1 08 36 PM](https://user-images.githubusercontent.com/16708715/112029530-bad19600-8b0f-11eb-8041-cc5c6418f2b3.png)

Do you know by any chance if this dataset colouring can be automated via RCy3? Or is that a question I should ask there?
(setNodeColorMapping() creates the situation where blue/green preset dominates over custom colours)

**Comment by risserlin** [comment]
I don't think it can be automated by RCy3 yet.  But definitely something we can put a ticket in for.  I know it is something I would love to do via RCy3 as well!

I added a ticket to add this feature - https://github.com/BaderLab/EnrichmentMapApp/issues/455
