### ISSUE TITLE
Update the read the docs tutorial to use updated GSEA data

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#456]
GSEA changed the format of their files.  If users try and run gsea with the data and then go through the tutorial EM won't recognize their files.  
This might be fixed with the release of EM 3.3.2 but still good to update the GSEA results associated with the tutorial.

https://enrichmentmap.readthedocs.io/en/latest/QuickTour.html

**Comment by mikekucera** [comment]
Possibly use the GSEAtutoria_4.1 data that I have.

**Comment by mikekucera** [comment]
Done
