### ISSUE TITLE
Issues using upload_em_file from Windows in EM 3.3.2 beta

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#457]
Recieved from Feifei Li - 

 I tried relaunching Cytoscape several times but no luck...then I tried relaunching docker and cytoscapePing() works now...and...here comes another new error message:
![bug](https://user-images.githubusercontent.com/3842763/113342759-dfdabb80-92fc-11eb-89f5-dde6cea3ccb7.png)

Although the error occured on the line calling content(), but it appear to be that POST() failed to escape backslashes in the Windows file path properly when parsing it in json format. I then checked the value returned by POST():

![bug2](https://user-images.githubusercontent.com/3842763/113342780-e701c980-92fc-11eb-95bc-e724b06ebd7d.png)

I pasted the link in my browser and it showed me this page:

![bug3](https://user-images.githubusercontent.com/3842763/113342806-ef5a0480-92fc-11eb-9d2c-e1f2ac238fac.png)

This issue appears to be OS specific (Windows 10). I will be great if I could find a way to manually handle the file path, but this appears to arise from a deep level of the implementation of POST(), given that long chain of function calls...

There are another 2 things that also concern me:

In the instruction for em_base_image, it asks users to specify parameter "host_machine_dir", but it is never used in the script. I presumed it should go into the "params" section at the top; I wonder if I placed it in the wrong place...
When launching Cytoscape, I found this in the cytoscape task history:
![bug4](https://user-images.githubusercontent.com/3842763/113342824-f6811280-92fc-11eb-8394-b26018d469ed.png)

This occurs to both version 3.3.1 and 3.3.2 beta of EM app. Should I be worried about this warning?

**Comment by mikekucera** [comment]
Fixed in 680114df2b6ebaf36f0476f524ccdb2aea848007
