### ISSUE TITLE
New Feature: annotate post analysis edges with overlap

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#458]
I spend a lot of time often annotating post analysis edges.  

I run a post analysis with specific genesets and I then want to highlight in the figure what genes were responsible for the overlap so manually go through the edges adding an annotation onto the edge with the names of the genes in the overlap.  It is cumbersome but would be great if we coulud add the feature to do this automatically.
Either "annotate selected edges with overlap" or "annotate all post analysis edge with overlap"

There is probably more that we could add to this type of feature but this is what I find myself doing a ton.  

@veroniquevoisin would you find this useful?

**Comment by mikekucera** [comment]
Do you mean setting the edge label?

**Comment by risserlin** [comment]
I didn't think of it as an edge label but that might work.  Is the edge label easy to re-position?

I am adding annotations to the edges like this:
<img width="295" alt="Screen Shot 2021-04-15 at 1 58 27 PM" src="https://user-images.githubusercontent.com/3842763/114916346-af157e80-9df2-11eb-842f-133a2bcd9e24.png">

**Comment by mikekucera** [comment]
Edge labels are always positioned at the middle point of the edge. They can't be manually repositioned. 

I'm concerned about automatically generating annotations for this. I think users might be confused if they move the edges and the annotations don't move along with them. I would prefer to use edge labels.

BTW the overlaps can be large, the labels might get very long

**Comment by risserlin** [comment]
Tried using edge labels instead --> work perfectly!
