### ISSUE TITLE
What is the difference between EnrichmentMap::Genes and EnrichmentMap::Enrichment_Genes

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#459]
only a fraction of Enrichment_genes are populated but all the genes look to be populated. confusing.

**Comment by mikekucera** [comment]
Enrichment_genes is populated only for signature nodes. It contains the genes from the Genes column but it filters out genes that are not in the gene universe of the original network.

This column isn't mentioned in the docs, so that needs to be fixed.
