### ISSUE TITLE
EnrichmentMap with GSEA shows URLs in the geneset names 

### ISSUE THREAD

**Issue by komalsrathi** [BaderLab/EnrichmentMapApp#460]
I ran GSEA (NOT pre-ranked) on my dataset and here is the structure and parameters of the GSEA run:

structure of GSEA output folder:
```
human_gsea_control_vs_treat
├── ... (lots of pngs/html)
├── butterfly_plot.png
├── edb
│   ├── gene_sets.gmt
│   ├── human_gsea_control_vs_treat.cls
│   ├── human_gsea_control_vs_treat.rnk
│   └── results.edb
├── ... (lots of pngs/html)
├── gene_set_sizes.xls
├── global_es_histogram.png
├── gsea_report_for_Control_1620063771620.html
├── gsea_report_for_Control_1620063771620.xls
├── gsea_report_for_Treat_1620063771620.html
├── gsea_report_for_Treat_1620063771620.xls
├── ... (lots of pngs/html)
├── heat_map_corr_plot.html
├── human_gsea_control_vs_treat.Gsea.1620063771620.rpt
├── index.html
├── neg_snapshot.html
├── pos_snapshot.html
├── pvalues_vs_nes_plot.png
├── ranked_gene_list_Control_versus_Treat_1620063771620.xls
├── ranked_list_corr_124.png
└── xtools.css

```

Parameters of GSEA from index.html:
```
producer_class	xtools.gsea.Gsea
producer_timestamp	1620063771620
param	zip_report	false
param	num	100
param	scoring_scheme	weighted
param	norm	meandiv
param	out	/Users/rathik/Projects/Skeletal_Muscle_Patrick/results/human_filtered/gsea_output
param	mode	Max_probe
param	include_only_symbols	true
param	set_max	1500
param	gmx	ftp.broadinstitute.org://pub/gsea/gene_sets/h.all.v7.2.symbols.gmt,ftp.broadinstitute.org://pub/gsea/gene_sets/c2.cp.v7.2.symbols.gmt
param	plot_top_x	20
param	nperm	1000
param	order	descending
param	rpt_label	human_gsea_control_vs_treat
param	rnd_seed	42
param	set_min	15
param	res	/Users/rathik/Projects/Skeletal_Muscle_Patrick/results/human_filtered/gsea/human_gsea_control_vs_treat.gct
param	create_svgs	false
param	cls	/Users/rathik/Projects/Skeletal_Muscle_Patrick/results/human_filtered/gsea/human_gsea_control_vs_treat.cls#Control_versus_Treat
param	sort	real
param	create_gcts	false
param	help	false
param	save_rnd_lists	false
param	median	false
param	metric	Signal2Noise
param	make_sets	true
param	rnd_type	no_balance
param	gui	false
param	permute	phenotype
param	collapse	No_Collapse

file	/Users/rathik/Projects/Skeletal_Muscle_Patrick/results/human_filtered/gsea_output/human_gsea_control_vs_treat.Gsea.1620063771620/index.html
```

I imported this folder in Cytoscape EnrichmentMap and it filled the following fields automatically:

<img width="1440" alt="Screen Shot 2021-05-04 at 1 45 46 PM" src="https://user-images.githubusercontent.com/7000615/117046806-2007d200-acdf-11eb-8b0b-181b6134e767.png">

I increased the `FDR cut-off to 0.5` and hit `Build` and got this warning:

<img width="1438" alt="Screen Shot 2021-05-04 at 1 46 55 PM" src="https://user-images.githubusercontent.com/7000615/117046924-43328180-acdf-11eb-8a6c-8c6e30cd5501.png">

I hit `Continue to Build` and this is what I got:

<img width="1440" alt="Screen Shot 2021-05-04 at 1 41 04 PM" src="https://user-images.githubusercontent.com/7000615/117046207-66a8fc80-acde-11eb-954e-cef5fc631c7e.png">

I am confused why I am getting the full URLs of the gene sets and how do I remove them?

**Comment by risserlin** [comment]
You are using the GSEA gmt files and EM is optimized for the baderlab genesets that are updated on a monthly basis.   (http://download.baderlab.org/EM_Genesets/current_release/)

The easiest fix for the above is just swap the attribute that is being used for the label.  It defaults to GS_description but if you change it to Name it should fix it.

In the Style panel expand the Label and change the column from GS_Descr to Name.
<img width="460" alt="Screen Shot 2021-05-04 at 1 46 09 PM" src="https://user-images.githubusercontent.com/3842763/117046978-547b8e00-acdf-11eb-8dc0-af4600163a4a.png">

**Comment by komalsrathi** [comment]
Great, thanks for the immediate response!
