### ISSUE TITLE
using enrichment map for GSEA result

### ISSUE THREAD

**Issue by SunYYQQ** [BaderLab/EnrichmentMapApp#461]
When I used the app to plot network figures, I met the problem as follows.
<img width="536" alt="截屏2021-05-13 下午10 45 28" src="https://user-images.githubusercontent.com/84140294/118142404-eea8a800-b43c-11eb-81c2-0c587d08c7b6.png">

I checked my files format and could not find the problem

**Comment by risserlin** [comment]
are you using GSEA result files or result from another program?

**Comment by SunYYQQ** [comment]
> are you using GSEA result files or result from another program?

I used WebGestalt for GSEA analysis and organized the result for enrichment map

**Comment by risserlin** [comment]
can you post an example results file that you are using?

**Comment by SergioRodLla** [comment]
Hi, how did you solve this issue at the end?

**Comment by risserlin** [comment]
Going through my emails and they never sent an example of WebGestalt output file for us to help troubleshoot the issue.  Do you have a file that we can use to help solve the issue?

**Comment by SergioRodLla** [comment]
Yes, but I have to say that I'm getting this error not using files from WebGestalt, but data sets obtained by using the `GSEA` function of `clusterProfiler` package in R to get enriched GO terms. I basically then split the results for NES>0 and NES<0 to have files for the Positive and Negative enrichments (.tsv). For the GMT file I am using the one I downloaded from [GSEA Molecular Signatures Database](http://www.gsea-msigdb.org/gsea/msigdb/index.jsp) M5 (ontology gene sets) for mouse organism. Then when using EnrichmentMap (GSEA analysis type) with these 3 files I get the same error message from above.

I'm not sure how the format of the Pos and Neg files has to be (e.g. tab or semicolon separated columns)

Best,
Sergio

**Comment by risserlin** [comment]
Hi Sergio, 
There is no requirement to use the GSEA format.  When I use a new enrichment tool I often convert the output to the generic format.   It might be easier if you format the file according to our generic format - https://enrichmentmap.readthedocs.io/en/latest/FileFormats.html?highlight=generic#generic-results-files. What are the headers for the clusterProfiler output files?  
Ruth

**Comment by SergioRodLla** [comment]
Hi Ruth,
The headers look like this:
`ID	Description	setSize	enrichmentScore	NES	pvalue	p.adjust	qvalue	rank	leading_edge core_enrichment	phenotype`
Fields are tab-separated.
Do the column names or their order have to match the expected file formats?

Thank you,
Sergio

**Comment by risserlin** [comment]
I don't think column names matter but order does.  The only thing you loose by not converting it to proper GSEA type files is the leading edge.  I recommend putting it in generic format and see if you can create the EM that way.  You don't need the NES values but you can always load them in after as node attributes if you want.  Just set the phenotype to +1 if NES > 0 and -1 if NES < 0.

**Comment by risserlin** [comment]
if you want, send me the the file (ruth.isserlin at utoronto.ca) and I can see if I can get it to work.  
the gmt file that you are using for EM is the same one that you are giving to clusterProfiler?  (It sounds like clusterprofiler has its own set of pathways that it is using)

**Comment by SergioRodLla** [comment]
The function [GSEA](https://www.rdocumentation.org/packages/clusterProfiler/versions/3.0.4/topics/GSEA) from clusterProfiler is a generic function for doing GSEA analysis and lets you select your own GMT file (TERM2GENE argument). And yes, it's the same GMT file that I'm using for EM. I'm sending you the file. One question, is it better then to set the analysis type (in the dropdown menu) to "Generic/gProfiler/Enrichr" instead of "GSEA" in this case?

**Comment by risserlin** [comment]
if you have made a generic file as opposed to GSEA file type then yes, you need to change the analysis type to "Generic/gProfiler/Enrichr"
