### ISSUE TITLE
post-analysis with a 4 datasets: showing edges for all datasets even if just one is selected

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#462]
I have created an enrichment map with 4 datasets but in addition to visualize the 4 datasets together, sometimes I just visualize them one by one. Although only 1 dataset is selected , the edges of the added gene-set using post-analysis are showing for the 4 datasets. 
<img width="1213" alt="Screen Shot 2021-05-17 at 3 43 06 PM" src="https://user-images.githubusercontent.com/7570379/118546915-a16f5380-b726-11eb-905b-a92d44b965d7.png">

**Comment by mikekucera** [comment]
Possibly use the GSEAtutoria_4.1 data that I have.
