### ISSUE TITLE
Color By Data Set: Change Colors... Is it possible to make this option change the node color only?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#468]
On a map created with multiple datasets, there is the option to change the colors. It changes the node colors but also the edge colors. Is it possible that it change only the node colors but not the edge colors?
<img width="1014" alt="Screen Shot 2021-07-28 at 2 36 00 PM" src="https://user-images.githubusercontent.com/7570379/127377972-bfe7f9bf-19d0-4eaa-964e-e0f031510501.png">

**Comment by mikekucera** [comment]
This option does not currently exist. The idea was that the edge colors should correspond to the data set colors so you can tell which edge corresponds to which data set (unless you are using combined edges then this isn't an issue).
So its working as intended :)
