### ISSUE TITLE
How to change the cluster name on the annotation panel?

### ISSUE THREAD

**Issue by Cycao** [BaderLab/EnrichmentMapApp#47]
Hi,

I am trying to make my Enrichment Map with the annotation feature. As the instruction, I double clicked the name and typed the new name on it, but it can not be changed after I pressed Enter. Which step I did wrong?

Thanks.

**Comment by risserlin** [comment]
It looks like a bug. Just working on fixing it now. In the mean time you can manually change the label by right clicking on the label and select Edit -> modify Annotation.  A dialog should come up and you change the appearance and content of the annotation.

**Comment by Cycao** [comment]
Hi Ruth,

It works. Thanks. But when I moved the cluster, the label of the cluster turned back, even I change the appearance. By the way, can I change the name of the node? Will you release a new version after you finish fixing these bugs? Thanks.

Johnny

**Comment by risserlin** [comment]
HI Johnny, 
the issue with renaming clusters has been fixed.  You can find an updated version at http://baderlab.org/Software/EnrichmentMap#Development_Versions
You can change the name of an individual node by double clicking the name in the node table.  (You can change any value in the node table by double clicking on the cell).  In the enrichment map the label of the  nodes is taken from the Node table column EM#_formatted_name so to change a node label in the EM you need to update that column.
