### ISSUE TITLE
GSEAtutorial.zip not working with EnrichmentMap

### ISSUE THREAD

**Issue by ARW-UBT** [BaderLab/EnrichmentMapApp#471]
Hello, 
I have tried to use the data in GSEAtutorial.zip (https://enrichmentmap.readthedocs.io/en/latest/_downloads/419eb265cf06a982bb39816dbccdcc8a/GSEATutorial.zip) to run GSEA in the Cytoscape app. 
Unfortunately, the 'scan folder for enrichment data' in the app seems not to work with these data. 

According to the quick tutorial at readthedocs, it should contain all data for GSEA, or did I get it wrong?
To be more specific: I do have a ranked list and a gmt file, which I want to sunmit to GSEA. 

Thanks for your suggestions.

**Comment by risserlin** [comment]
Are you trying to run GSEA from cytoscape?  If you have a rank file and a gmt file then you first need to run it in GSEA to get the results that EM in Cytoscape can use.

**Comment by ARW-UBT** [comment]
Thanks for the fast reply and the clarification. I have seen that GSEA can hand over the results directly to a Cytoscape instance. 
Best regards,
