### ISSUE TITLE
Seeing which datasets a given node is associated with (major issue when using 20+ datasets)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#474]
When you have many many datasets (I am currently working with 100+ datasets) there are only small variations in the colors associated with each dataset.  It is very difficult to figure out which datasets a given node is associated with.  

It would be helpful if for the given selection the datasets pane in the Enrichment map input panel would highlight the datasets that are associated with the given selection. 

alternately (or as well) it would be useful to have a node attribute that lists the datasets the node is associated with.

**Comment by mikekucera** [comment]
You can work around this using the heat map panel. Set "Compress" to "Data Set: *any*". Then when you select some nodes the header of the heat map table will show the datasets for the selected nodes.

I still think having this information in the main panel would be much more accessible, so I think this enhancement is a good idea, but for the meantime you can try the workaround.
