### ISSUE TITLE
Customizing heat strips

### ISSUE THREAD

**Issue by ravipatel4** [BaderLab/EnrichmentMapApp#476]
Hello,

I am interested in customizing the heat strips to show some type of scores from different datasets. I have a table of scores (positive and negative values) for a number of genesets (rows) in seven different datasets (columns). I want to visualize these scores as heat strip, where the height (y-axis) of the strip would represent the score and the color would represent the dataset. Is there a way to do this using enrichmentmap? So far, I have been writing the scores in the FDR column of the generic enrichment results file format. This has allowed me to visualize the scores as strips with the height representing the magnitude and the direction representing positive vs negative (see the image below). However, this approach doesn't allow me to color the strips by the samples. Do you have any suggestions about how I could accomplish this?

Thank you.

![image](https://user-images.githubusercontent.com/3804100/150453511-8881ed73-b5ba-4f87-91ab-614ddccc1d63.png)

**Comment by mikekucera** [comment]
Unfortunately there is no way to do this in Cytoscape. EnrichmentMap uses the built-in Cytoscape bar chart for the heat strips. This chart does not allow for separate columns to be used for bar height and bar color.

**Comment by ravipatel4** [comment]
Ah I see. Thanks for a quick response. Since you are an expert in the subject matter, I was wondering if you are aware of any open source tool that allows creating custom charts as nodes of a network. Thanks.

**Comment by mikekucera** [comment]
You could take a look at the enhancedGraphics App: https://apps.cytoscape.org/apps/enhancedgraphics
I've not used it before so I'm not sure if it can do what you need.
If you do start experimenting with charts on an EnrichmentMap network then I advise to create a copy of the EM style and switch the network to the copy.

**Comment by ravipatel4** [comment]
This is very helpful! I will look into enhancedGraphics App. Thank you so much for the advice!
