### ISSUE TITLE
Failed installation from App Manager

### ISSUE THREAD

**Issue by thielde** [BaderLab/EnrichmentMapApp#485]
I tried to install EnrichmentMap form the cytoscape App Manager both on its own and as part of the EnrichmentMap Pipeline Collection.
WordCloud, AutoAnnotate and EnrichmetnMap Pipeline Collection all have the status Installed, but EnrichementMap itself always fails with the status "Failed to Start".
It doesn't show up in the Apps tab.
I'm using cytoscape_v3.7.2, trying to install EnrichmentMap 3.3.4.

When I try to circumvent this by installing from a downloaded file, I run into the same problem. (Downloaded the enrichmentmap-3.3.4.jar file.)

**Comment by risserlin** [comment]
That is a pretty old version of Cytoscape.  I think there is probably an incompatibility with the latest version of EM and that version of Cytoscape.  Is there a reason that you are using that version of Cytoscape?

**Comment by thielde** [comment]
It's just the version that I had installed already.
With cytoscape 3.9.1 it works now.

Thanks for the quick reply.
