### ISSUE TITLE
Change "Fill Color" only change the edge color not node color

### ISSUE THREAD

**Issue by Zejian-Wang** [BaderLab/EnrichmentMapApp#488]
Dear Administrator,

Thanks for the powerful software, I use EnrichmentMap to visualize result generated from g::profiler, I only have one data-set to visualize.
![image](https://user-images.githubusercontent.com/34888291/170408362-608e4b3b-12d2-4911-8b78-7748075b1a7e.png)
![image](https://user-images.githubusercontent.com/34888291/170408405-a1ce8328-1737-4211-ba0e-1aa94c9eac05.png)

I want reverse the fill of dot-plot (set 0.0 as red and 0.05 as white), however when I change "Style->Fill Color-> Current Mapping" to my own setting, I found only the color in border changed, the fill of dot-plot doesn't change.
![image](https://user-images.githubusercontent.com/34888291/170408921-3792cca0-a95e-446c-896f-5321dcdcc438.png)

How can we change the fill color in node? Were I select wrong bottom?

I'll be grateful if you can help us to fix this problem, thank you!

Best,
ZJ

**Comment by mikekucera** [comment]
You need to remove the charts that are over the nodes.

In the main EnrichmentMap panel, go to the Style section, and set "Chart Data" to "--None--".

**Comment by Zejian-Wang** [comment]
Hi Mike,

Thanks for your quick reply! It's work for me, Thank you!

Best
