### ISSUE TITLE
g:profiler not running

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#489]
Ran random example on g:profiler website, download GEM file, plugged into EM
![Screen Shot 2022-06-24 at 10 28 15 AM](https://user-images.githubusercontent.com/3842763/175556655-42e190b8-7a79-4803-9cf6-b9aeecd4dad2.png)

Cytoscape 3.9.1, EM 3.3.4

**Comment by mikekucera** [comment]
I used the GEM file as an 'enrichments' file and it worked.

Can you please provide more detailed steps to reproduce, because I may be missing something, or send me the GEM file you used. 
Thanks.

**Comment by risserlin** [comment]
![Screen Shot 2022-06-24 at 12 14 46 PM](https://user-images.githubusercontent.com/3842763/175575592-c65933f3-ef7f-4c0f-b77a-66c396ff1f2a.png)
[gProfiler_hsapiens_6-24-2022_10-24-58 AM.gem.txt](https://github.com/BaderLab/EnrichmentMapApp/files/8977598/gProfiler_hsapiens_6-24-2022_10-24-58.AM.gem.txt)

**Comment by mikekucera** [comment]
It works.
Ruth, this fails for you?

**Comment by Julia-Elsayed-Moustafa** [comment]
Hello, I have been trying to use EnrichmentMap 3.3.4 in Cytoscape 3.9.1.

I have been using a gem file generated from my own data using gProfiler in R (code used -taken from the gProfiler tutorial- included below):

## Produce GEM table for cytoscape
gem <- gostres$result[,c("term_id", "term_name", "p_value", "intersection")]
colnames(gem) <- c("GO.ID", "Description", "p.Val", "Genes")
gem$FDR <- gem$p.Val
gem$Phenotype = "+1"
gem <- gem[,c("GO.ID", "Description", "p.Val", "FDR", "Phenotype", "Genes")]
head(gem, 3)

write.table(gem, file = "MM_gProfiler_gem_20220907.txt", sep = "\t", quote = F, row.names = F)

GMT file downloaded from the following link (https://biit.cs.ut.ee/gprofiler/static/gprofiler_full_hsapiens.ENSG.gmt). 

I get the following error anytime I try to run EnrichmentMap:

Index 1 out of bounds for length 1.

Any idea what mimght be causing this?

Thanks!

**Comment by risserlin** [comment]
Can you send me a sample of your MM_gProfiler_gem_20220907.txt file?

How are the genes in the "Genes" column separated?

**Comment by Julia-Elsayed-Moustafa** [comment]
[example.gem.txt](https://github.com/BaderLab/EnrichmentMapApp/files/9527967/example.gem.txt)

Hello,
I've attached an example file with the first few lines. They are comma separated (I fed in the standard output I got from gProfiler).

**Comment by risserlin** [comment]
It works for me.  

What version of cytoscape and Enrichment map are you using?



<img width="611" alt="Screen Shot 2022-09-08 at 11 21 52 AM" src="https://user-images.githubusercontent.com/3842763/189161534-85e3a61b-4ebe-4ec8-9f28-91a768872cf1.png">

**Comment by Julia-Elsayed-Moustafa** [comment]
Hm, ok, thanks, I'll keep trying to reinstall everything... I'm using EnrichmentMap 3.3.4 in Cytoscape 3.9.1.

**Comment by risserlin** [comment]
I am using 3.3.4 snapshot.  It is possible that I might be using the later version than the one released.  Let me downgrade to the released version to check.

**Comment by risserlin** [comment]
Yes.  It works with the released version as well.  Does the example file that you sent me work for you?

Maybe it is something in the full file that is causing problems.

**Comment by Julia-Elsayed-Moustafa** [comment]
I actually just re-installed Cytoscape and EnrichmentMap again (same versions), and the full file has now started working, no change in file itself or versions installed. No idea what caused the issue over the last few days, but glad it's now working! Thanks very much for your quick replies.
