### ISSUE TITLE
July gene sets (at least the Human ones) are missing the genes

### ISSUE THREAD

**Issue by toddajohnson** [BaderLab/EnrichmentMapApp#490]
I had previously used Human_GO_AllPathways_no_GO_iea_April_01_2022_symbol.gmt and today downloaded the July 2022 version Human_GO_AllPathways_no_GO_iea_July_01_2022_symbol.gmt.txt, but the gene symbols in the July file seem to be missing.  Also missing in Human_GOBP_AllPathways_no_GO_iea_July_01_2022_symbol.gmt, which I first downloaded after realizing it's the recommended file.

For instance
July:
PROTEIN CITRULLINATION%BIOCYC%PWY-4921  protein citrullination

April:
PROTEIN CITRULLINATION%HUMANCYC%PWY-4921        protein citrullination  PADI6   PADI3   PADI2   PADI4   PADI1

**Comment by risserlin** [comment]
Thanks for reporting.  Looks like the identifier conversion might be down.  The identifiers are only found for the original ID the data was downloaded in.  I will rebuild and let you know when the latest fixed version is up. 
Thanks,

**Comment by risserlin** [comment]
Fixed (for now :) , unfortunately it is a bigger issue )  The July genesets have been updated and are available here - https://download.baderlab.org/EM_Genesets/July_05_2022/
