### ISSUE TITLE
enhancement RCy3: enrichmentmap build with Great: not able to filter using binomial q value (only hypergeometric test available)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#494]
When we build an enrichmentmap from Great, we can filter the results based on the hypergeometric q value or the binomial test q value. When the map is being built, there is a pop up menu that gives us the choice between hypergeometric or binomial. However it is not possible with the current Rcy3 command.
As a work around I'm thinking of building the map with qvalue of 1 and then filtering the nodes using the binomial qvalue by importing the original great result as node table.

**Comment by mikekucera** [comment]
Added a new argument called `greatFilter` to the `enrichmentmap mastermap` command.
