### ISSUE TITLE
cytoscape Enrichment Map no responce

### ISSUE THREAD

**Issue by ChaoWilliam** [BaderLab/EnrichmentMapApp#496]
Hi guys,
When I ran the enrichment map with gsea output, once I set the file and was ready to build the map, however, when I clicked the build button nothing happened but the bottom of the build became gray and did not pop out the window of processing even the error message. I'm not sure what's going on. Does anyone know what happened?
![image](https://user-images.githubusercontent.com/112256796/196439822-c9cb363d-2643-46a9-8f52-0582b646d7a8.png)

**Comment by risserlin** [comment]
sometimes the error box can be hidden behind. If you click on Cytoscape the hidden error box might be listed there as well. 

Alternately, can you send your cystocape frameworks file.  You can find it at:
C:\Users\YourUserName\CytoscapeConfiguration\3\framework-cytoscape.log
