### ISSUE TITLE
Post Analysis Heat map missing genes that are listed in the edge overlap (edge parameter) 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#5]
When you set the limit of common genes to for example 14 and then click on the edge produced the heatmap show only 6 genes but when you look at the list of genes associated with the edge in the edge browser there are 14 genes listed.

common genes between the Genesets and the post analysis set are being calculating on the original geneset without restriction to the expression set being used for the EM. This generates number based on the absolute overlap instead of what is represented in the EM. When you click on the edge though the expression viewer will only show you the genes that overlap between the two sets that are in the expression set.

**Comment by mikekucera** [comment]
I can't reproduce this.

**Comment by risserlin** [comment]
common genes is missing from the options of how to compute edge weights.

**Comment by mikekucera** [comment]
Hi Ruth,
I'm not entirely understanding what the problem is. Could you please try if this still happens with a current build of EM. And if so could you provide the steps to reproduce it. Thanks.

**Comment by risserlin** [comment]
This is fixed in the latest version of EM.
