### ISSUE TITLE
testing EM 3.3.5 ( enhancement): be able to see full name in heatmap table headers

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#501]
be able to read full name in heatmap table headers if possible: 
<img width="1272" alt="Screen Shot 2022-12-02 at 10 37 01 AM" src="https://user-images.githubusercontent.com/7570379/205333845-5d0dcd9a-5a19-446f-ac8c-4b7023d58738.png">

**Comment by mikekucera** [comment]
I added an option to the heat map panel menu that allows you to increase the size of the vertical table headers.

<img width="1368" alt="Screen Shot 2022-12-05 at 3 44 23 PM" src="https://user-images.githubusercontent.com/5350528/205740253-20177bb6-7f2c-48a7-9c75-095d8ecaa34e.png">
