### ISSUE TITLE
testing EM3.3.5: changing Data Set Colors change all edges to color dataset1

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#502]
When working with a mastermap, I usually color the nodes by Dataset and I don't use the default but change the colors. However, it also changes the colors of the edges and I think that it changes all edges to color of dataset1. I usually manually change edge color back to a more neutral color like gray.
I'm wondering if there could be a way to add options so that node colors and edge colors are separated when in this color option menu.

<img width="1249" alt="Screen Shot 2022-12-02 at 11 02 32 AM" src="https://user-images.githubusercontent.com/7570379/205334623-f7b913f9-f9cb-4dbb-b615-80aba9bd6c94.png">

**Comment by mikekucera** [comment]
I added an extra option to specify the edge color...

<img width="1303" alt="Screen Shot 2022-12-07 at 9 20 36 AM" src="https://user-images.githubusercontent.com/5350528/206268827-129df9be-8cee-4eea-b8c8-cf55f60995c9.png">
