### ISSUE TITLE
EM 3.3.5: force directed layout does not work on hidden edges (but organic layout does)

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#505]
This is related to an issue that I had mentioned previously. When I adjust the number of edges using the enrichmentmap slidebar , and reapply the layout, the layout does not change (it was working in the past years). I could see that the organic layout is working and this is only with the force directed layout that it is not working (on whole network or on subnetwork). Sorry if this is a duplicated ticket.

[formike.cys.zip](https://github.com/BaderLab/EnrichmentMapApp/files/10143434/formike.cys.zip)

**Comment by mikekucera** [comment]
Hi Veronique. You are right that hiding just edges does not change the results of the prefuse force directed layout. However, this appears to have been the case for some time, as I'm getting the same results in Cytoscape 3.8. Looking at the code it appears that the layout takes hidden nodes into account, but not hidden edges. Perhaps you were hiding nodes in the past when you got different results?

**Comment by veroniquevoisin** [comment]
I'm quite sure it was working but it must have been a while ago. I remember adjusting the edges and then clicking on the icon to redo the layout. It makes the edge sliding bar less useful as it was. Except maybe for users who can get the idea to perform the organic layout which is not a default layout algorithm. I'm not sure what to suggest here (send a note to the Cytoscape team, dialog box to say to apply the organic layout,...). It is not for me but for users in general.
