### ISSUE TITLE
Heatmap only displaying expression/ranks for dataset where geneset is significant eventhough it is found in the second dataset

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#508]
EM - 3.3.5
Cytoscape - 3.9.1

Two dataset enrichment map.  Geneset found to be enriched in one dataset but not the other.  when you click on the node to see the difference in expression/ranks of the genes that it contains the heatmap only displays the ranks for the dataset the geneset is signficant in. 

<img width="327" alt="Screen Shot 2023-01-09 at 1 02 12 PM" src="https://user-images.githubusercontent.com/3842763/211376694-1a228cbb-af26-4209-8e97-7ff0dcb93c43.png">

<img width="434" alt="Screen Shot 2023-01-09 at 1 02 18 PM" src="https://user-images.githubusercontent.com/3842763/211376723-91614729-344d-4cca-8547-2b8c224397be.png">

**Comment by mikekucera** [comment]
This is actually an option in the Heat Map panel. 
Click the little hamburger menu and deselect the option that says "Display only selected data sets"

<img width="885" alt="Screenshot 2023-11-08 at 4 50 02 PM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/5350528/8fa6ff14-d359-4ad3-87df-5dfd048d8536">
