### ISSUE TITLE
Error - Gene sets in enrichment file missing from GMT file

### ISSUE THREAD

**Issue by lcorrie** [BaderLab/EnrichmentMapApp#511]
I am getting an error message saying that gene sets in the enrichment file are missing from the GMT file. However when I grep the GMT file for one of the GO terms that it lists as missing, the GO term is there. This is in enrichment map (v3.3.2) and cytoscape (3.8.2). Any help moving forward would be greatly appreciated!
![image](https://user-images.githubusercontent.com/65260254/212193308-90ed2780-89bf-4c81-8419-ffb4ab3e8d94.png)
![image](https://user-images.githubusercontent.com/65260254/212192614-65619844-969e-4759-a5fd-053cca047df5.png)

**Comment by mikekucera** [comment]
EnrichmentMap 3.3.2 is over two years old now. My first suggestion is to try the latest release. Even if this is still a bug in the latest version I would have to fix it in a new version so you would have to upgrade anyway.

**Comment by lcorrie** [comment]
thanks for the speedy response! I just updated to 3.3.5 and I am still getting the same error as above unfortunately.

**Comment by mikekucera** [comment]
Would you be able to send me your data files? My email is mikekucera(at)gmail(dot)com

**Comment by risserlin** [comment]
Which GMT file are you using?
Also, you should be able to click on close on the first error message and then Continue on the one below it and it should still build the network even though those genesets are missing.

**Comment by lcorrie** [comment]
@mikekucera  I just sent you an email with the files that I am using to generate the enrichment maps. Thank you again for the help!

@risserlin I'm not sure what you mean by what gmt file I am using. Could you elaborate please? It was generated in a pipeline that my lab uses so sadly I am not an expert on the details. I do know I can generate the network without the missing gene sets, however there are 107 of them throughout my three data sets so I am hoping to not have to do that!

**Comment by risserlin** [comment]
@lcorrie I was just wondering if you got the gmt files from gprofiler or GSEA or baderlab sets.  I have been having some issues with the baderlab sets having some weird hidden characters and I was wondering if it was related.

**Comment by mikekucera** [comment]
Issue has been resolved over email.
