### ISSUE TITLE
enrichmentmap build command - two generic datasets not working properly

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#514]
specifying two datasets with the build command with generic analysis type:

two dataset files and one gmt file does not behave the same way as the interface.  

I think the gmt is not being associated with either datasets or is only being set to one of the datasets.  

Here are example files - 
gmt file - https://www.dropbox.com/s/kcnwjgr66casvhu/gprofiler_full_hsapiens_e109_eg56_p17_1d3191d_.name.gmt?dl=0
dataset1 - https://www.dropbox.com/s/xut4zxwqj3h0j0f/gProfiler_hsapiens_lab2_results_GEM_termmin3_max250.gem.txt?dl=0
dataset2 - https://www.dropbox.com/s/zksgib85yhjl4zs/gProfiler_hsapiens_lab2_results_GEM_termmin3_max10000.gem.txt?dl=0

parameters - q-value 0.001
jaccard
threshold 0.35

result in the interface :
 
<img width="647" alt="Screen Shot 2023-05-08 at 3 40 12 PM" src="https://user-images.githubusercontent.com/3842763/236917486-3c21b391-effa-4e60-bf0a-e5549c3f13a0.png">

results with the same parameters but using build command - 
<img width="735" alt="Screen Shot 2023-05-08 at 3 41 00 PM" src="https://user-images.githubusercontent.com/3842763/236917672-e94d0fc0-a786-49f3-b908-3c6a05ef2c32.png">

In the build command there is no option for gmt1 or gmt2 or commongmt that I can see. 

Do I have to create a mastermap for 2 datasets?

**Comment by mikekucera** [comment]
Hi Ruth, I'm getting the same results from the command and from the UI. They both look like the second screenshot above. Something else must be different in the UI settings. Can you give it another try and let me know if you can still reproduce the issue? Thanks.
