### ISSUE TITLE
Style updates for EM networks

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#517]
Style updates for EM networks
- Map node size and label font size to -log10(pvalue)
  - Question: If there is more than one dataset, should the -log10(pvalue) column be the average?
  - Question: What about q-value?
- The label of the most significant node in a cluster should be significantly larger so that it stands out.
  - Note: The style is part of EM, but clusters are created by AA. So for this to work AA would need to detect an EM network and set a style bypass. This bypass would need to be reset every time the annotation set is changed.
- Add transparency to nodes
- Change label color to dark grey instead of black

**Comment by risserlin** [comment]
> Question: If there is more than one dataset, should the -log10(pvalue) column be the average?

I don't think it should be the average because then a strong signal from an individual dataset won't stand out.  Or will it be the average of datasets that are significant?
Will this be a setting that it is easy to adjust? (between using p-value and q-value)

**Comment by mikekucera** [comment]
We could add options to the style section to choose which dataset to use for the mapping, and to choose p or q value.

**Comment by risserlin** [comment]
By default I would set it to the max -log(pval) for all the datasets

**Comment by mikekucera** [comment]
Opened separate issue in AA for "label of the most significant node in a cluster should be significantly larger": https://github.com/BaderLab/AutoAnnotateApp/issues/196
