### ISSUE TITLE
filtering GSEA results by NES assumes positives are in one file and negatives are in another

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#526]
Using FGSEA to analyze data and create "fake" GSEA results files but putting all results into one file (with both positive and negative in the same file to reduce amount of files that I create).  
Run EM with "NES (GSEA) only option --> positive" and it shows both positive and negative results.  

If you then divide the file, one positive with +ve NES values and one negative with all the -ve NES values, then it works.  

Problem - if you put the negative file in the positive spot in the input panel and the positive file in the negative spot in the input panel EM creates the wrong network and assumes the negative file are actually positive!

**Comment by mikekucera** [comment]
What is the format of the header row of your files? It looks like EM is assuming that GSEA results have 11 columns.

**Comment by risserlin** [comment]
here is the header row for fGSEA results that I have created - 
name	description	GS details	SIZE	ES	NES	pval	padj	FWER	Rank at Max	leading edge genes
(truthfully I am not sure which file the above is referring to but I have a generic method for creating fGSEA results and they all look like this)

**Comment by mikekucera** [comment]
Hi Ruth, 
What is the actual problem? I just tried creating a network from a GSEA data set and I swapped the positive and negative files and it appears to still have worked.
