### ISSUE TITLE
AutoAnnotate new features / enhancement

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#53]
###### 

new features suggestion 
###### 
# be able to adjust the cluster label width as we are able to adjust the node label width
# be able to annotate the singletons
# be able to click on a cluster label and highlight in yellow the corresponding nodes

**Comment by risserlin** [comment]
By width do you mean the font size or do you mean the number of words in the labek?

Currently you can annotate singletons.  Just click on the node of interest and click on the button in the Clusters row "Extract" and it will create an annotation on that individual node.

**Comment by veroniquevoisin** [comment]
By width, I mean the number of words per line:
width of 200: "positive regulation of DNA repair"
width of 150:
line 1: "positive regulation"
line 2: "of  DNA repair"

**Comment by arkadyark** [comment]
If I recall, I wanted to get to this as well, but the way that annotations
are implemented it seems like the only way to accomplish this is by having
multiple annotations (one for each line)
