### ISSUE TITLE
Different results when running via CLI vs. CyREST

### ISSUE THREAD

**Issue by AlexanderPico** [BaderLab/EnrichmentMapApp#532]
The vignette [here](https://bioconductor.org/packages/release/bioc/vignettes/rWikiPathways/inst/doc/Pathway-Analysis.html) produces [these enrichment results](https://github.com/BaderLab/EnrichmentMapApp/files/13667457/clusterprofiler_cluster_enr_results.txt) and then instructs R users to prepare a command string to pass through CyREST Commands API via `commandsRun`. Interestingly, this command works find in the Cytoscape CLI, but it fails when run via Swagger (or RCy3). I'm certain that it used to work, back when it was first written, but that was a few years ago...

Any insights into why this command fails via CyREST, but works via CLI?

WORKS via Cytoscape CLI
> enrichmentmap build analysisType=generic pvalue=0.05 qvalue=0.05 similaritycutoff=0.25 coefficients=JACCARD enrichmentsDataset1=/Users/apico/Desktop/Temp/clusterprofiler_cluster_enr_results.txt

DOESN'T WORK via Swagger
> http://localhost:1234/v1/commands/enrichmentmap/build?analysisType=generic&classDataset1=%2FUsers%2Fapico%2FDesktop%2FTemp%2Fclusterprofiler_cluster_enr_results.txt&coefficients=JACCARD&pvalue=0.05&qvalue=0.05&similaritycutoff=0.25

OP: https://github.com/cytoscape/RCy3/issues/217

**Comment by risserlin** [comment]
duplicate of #514 
Fixed in the current development version of EM - 3.4

**Comment by mikekucera** [comment]
Its working for me on 3.3.6

The example above uses different arguments. The CLI example uses 'enrichmentsDataset1' while the swagger example uses 'classDataset1'. When using 'enrichmentsDataset1' from swagger it works.

Can you please double check the command from swagger is using the correct arguments.

**Comment by AlexanderPico** [comment]
It works! 

RCy3 still fails, but that's my bug to fix... darn!
