### ISSUE TITLE
GSEA-Enrichmentmap-Cytoscape-desktop applicaion

### ISSUE THREAD

**Issue by sarneg** [BaderLab/EnrichmentMapApp#534]
I am doing GSEA analysis on desktop application. I have two RNAseq experiments.
1.     Cell line treated with control siRNA and siRNA-Gene (gene of interest).
2.     Cells treated with DMSO and a drug.

I have 3 replicates for each condition. My goal is to do pathway analysis for both treatments (siRNA and drug) and to see how similar/different the two treatments are.
Note: My controls from both experiments are different as control treatments may have different effects on gene expression. I run separate GSEA for the two experiments.

I have expression data of all samples from both experiments. I am using Ensembl id for column "Name" and Gene names for column "Description". I choose desired phenotype label and run GSEA for each experiment separately.

Then I run enrichment map visualization. I select result of desired experiment to visualize enrichment Map. It selects GSEA analysis for dataset 1. It selects rnk from edb folder for expression. Then on cytoscape, I get my networks. I get heatmaps for nodes with the ranking of genes. I need the heatmap with expression values in each sample and want to filter genes based on fold change and p-values. 

I also want to make a Network map of few selected nodes with each node showing their String network for proteins.

I would like to highlight my protein of interest (that was silenced using siRNA) in this Network.

**Comment by risserlin** [comment]
If I understand your issue correctly, instead of using the rnk file from the Edb directory for your expression file you can use your original file that you uploaded to run your analysis with GSEA.

The only issue that I think you will have is that you have given GSEA an expression file ensembl id and gene name and I think GSEA is translating  those for you into and rank file with just gene name <tab> rank.  If you want to keep all of your results as is, you can create a separate expression file from your original expression and swap your ensembl id column and your gene name column and use that instead of the rank file for the expression file.  

Are you creating your enrichment directly from within the GSEA interface or are you using the EM input panel inside cytoscape?

Thanks, 
Ruth

**Comment by sarneg** [comment]
I am using enrichment directly within GSEA and uploading original expression file after swapping gene name and ensemble id worked. Now I have heatmaps with gene expression for each sample. Thank You.

My other queries

 I want to make heatmaps of different nodes after filtering genes based on fold change and p-values.

I also want to make a Network map of few selected nodes with each node showing their String network for proteins.

I would like to highlight my protein of interest (that was silenced using siRNA) in this Network.

**Comment by sarneg** [comment]
I am using enrichment directly within GSEA and uploading original
expression file after swapping gene name and ensemble id worked. Now I have
heatmaps with gene expression for each sample. Thank You.


My other queries

1. I want to make separate heatmaps of a few nodes after filtering genes
based on fold change and p-values.

2. I also want to make a Network map with few selected nodes with each node
showing their String network for proteins.

3. I would like to highlight my protein of interest (that was silenced
using siRNA) in this Network.


Thank you in advance

**Comment by risserlin** [comment]
1. Unfortunately, you can't make specific heatmaps in enrichmentmap.  You can recreate your network with a a subset of the expression files to generate  more specific heatmap but that is not the best way to create a heatmap.  It is easier to export the heatmap as a text file and create your specialized heatmap in R or similiar program.   - https://baderlab.github.io/EnrichmentMap_Protocol/a-exploring-the-table-panel-heat-map.html from the heatmap panel menu there is the option to export as a txt file. 
2. In cytoscape you can make a subnetwork by selecting File -> new network --> from selected nodes.  To create a String network from a node selection you can find that option in the right click context menu - see here for how - https://baderlab.github.io/EnrichmentMap_Protocol/string.html#
3. The are a few different ways to highlight your gene of interest in the network.  

    - In the top right hand corner of the network you can put your gene of interest in the search bar and cytoscape will highlight all the nodes where that genes is contained.  When you have them highlighted you can go into the style panel and change a visual attribute to make those nodes more obvious (for example their size or their shape.  You will have to use the bypass option in the style - https://manual.cytoscape.org/en/stable/Styles.html.  
    - You can also do a post analysis where the post analysis set consists of just your gene of interest.  This will add a node to your network and edges to every set that it overlaps with - see https://enrichmentmap.readthedocs.io/en/latest/PostAnalysis.html?highlight=post%20analysis.
