### ISSUE TITLE
Diffuse string Network

### ISSUE THREAD

**Issue by sarneg** [BaderLab/EnrichmentMapApp#536]
Hi!

I am using Desktop App for Cytoscape on Mac. When I try to run heat diffusion a string network, I get Error message.
Error running diffusion: java.io.IOException: OOps! an error occurred while connection to the heat diffusion service in the cloud. How can I resolve the issue.

thank you

**Comment by mikekucera** [comment]
Hi, please report cytoscape bugs here: https://cytoscape.org/bug-report.html
