### ISSUE TITLE
gray nodes (not colored by -log10(value)when creating the map

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#540]
gray nodes (not colored by -log10(value)when creating the map
I then modify the fill color style myself. 
AA was working fine.
<img width="1021" alt="Screenshot 2024-02-29 at 8 02 35 AM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/0618647d-b245-4103-a13a-2ac79170a08e">

<img width="1263" alt="Screenshot 2024-02-29 at 8 03 02 AM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/295c99fe-4628-4c49-b052-318bb09eee4d">

**Comment by mikekucera** [comment]
Hi Veronique, can you please send me the session file. Thanks.

**Comment by veroniquevoisin** [comment]
Hi,
I got a new one today. It is again when I create a new map on a complex session with already a lot of maps (not sure if related).
<img width="1293" alt="Screenshot 2024-03-06 at 4 51 39 PM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/ae6281da-5157-44bd-8245-881ca516d1a7">

**Comment by veroniquevoisin** [comment]
link to session file: https://www.dropbox.com/s/8g5z6v0emckyi9q/test%20_forMike.cys?dl=0

**Comment by mikekucera** [comment]
Hi Veronique,

In the network above the entire p-value column is zeros. The -log10(pvalue) column is blank. That causes the mapping to not have a range which results in the grey nodes. Is there something wrong with the data, or is this a valid case?

Regardless it should detect when the range is invalid for -log10(pvalue) and use a different mapping.

**Comment by veroniquevoisin** [comment]
Hi Mike,
Yes, it is a valid case. I have an example right now where all the pvalue are 0. They are so many significant pathways that I do a map with the top pathways and GSEA returned them with a pvalue = 0 and -log10(0) = inf. 
In this case, all nodes should be red and I suppose that you can replace the 0 by any small value? eg 1e-10?


![Screenshot 2024-03-07 at 10 28 20 AM](https://github.com/BaderLab/EnrichmentMapApp/assets/7570379/80cfb0a8-beda-49b2-9db3-1be49ba060fc)

**Comment by mikekucera** [comment]
Hi Veronique.

When all the pvalues are 0.0 (or missing) then it uses 1e-10 for the pvalue. This results in 10.0 for -log10(pvalue).

This is an example of what the network and style look like when all pvalues are 0.0. 
Is this ok?

<img width="1300" alt="Screenshot 2024-03-07 at 11 22 26 AM" src="https://github.com/BaderLab/EnrichmentMapApp/assets/5350528/239841d2-4174-48b9-8f30-d8c7a6d15b17">

**Comment by veroniquevoisin** [comment]
Yes, it looks ok
