### ISSUE TITLE
No documentation discussing how to create EM from just gmt file 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#544]
I get quite a few requests for this feature and there is nowhere to direct them.  Checked and feature is still there.  It is like an EM easter egg :)

**Comment by mikekucera** [comment]
I'm planning to update on the docs when this new version of EM gets released. I'll add a section for this.

**Comment by mikekucera** [comment]
https://github.com/BaderLab/EnrichmentMap_docs/tree/215d1a8c1dac0e23cb3af3751540df7d9dacc6b2
