### ISSUE TITLE
Not able to generate an enrichment map from GSEA or cytoscape

### ISSUE THREAD

**Issue by ddsmd** [BaderLab/EnrichmentMapApp#55]
I ran all my analysis on GSEA and all was fine, then I tried to build an enrichment map and nothing happened on GSEA but when I tried with cytoscape a message saying: NO SUCH FILE appeared. I have tried uninstalling and re-installing the program but nothing changed.
I have Cytoscape 3.2.0, Enrichment Map v2.0.1, and I am running it in OS X Yosemite version 10.10.1
Thank you

**Comment by mikekucera** [comment]
Beta release of GSEA supports cytoscape 3
