### ISSUE TITLE
Change generic option in interface to generic (i.e. gprofiler)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#57]
Change generic option in interface to "generic (e.g. gProfiler)"

**Comment by veroniquevoisin** [comment]
Hi Ruth,
by the way,
I was thinking that we could ask Juri if there would be a possibility to
change the gProfiler output so it looks like DAVID or BinGo output with the
aim to get the information about the genes overlapping in each gene-set. I
think that it is easy to do as the default output of gprofiler contains the
list of gene names included (overlapping) in each gene-set.
In this case, gProfiler could go in the DAVID/Bingo category in the EM
interface.
I wanted to get back to Juri as soon as I have finished to reorganize the
project lists for us.
Which format is better Bingo or DAVID? or which would be the ideal format?

Veronique

**Comment by risserlin** [comment]
Updated gprofiler format is:
GO.ID   Description p.Val   FDR Phenotype   Genes
GO:0072006  nephron development 4.48e-02    4.48e-02    1   MYC,NPNT,RET,CTNNB1,PODXL,GATA3,TACSTD2
GO:0009888  tissue development  2.35e-02    2.35e-02    1   IL20,BAMBI,MYC,NPNT,DGAT2,ID2,AKR1C3,S100A7,DAB2,FABP5,JAK2,GSTM3,DDX17,PTPLA,COBL,GAL,DKK1,TUFT1,RET,CTNNB1,ERBB4,RILPL2,EFNA1,TCF7L2,PODXL,MEST,GATA3,BTG1,TACSTD2,EFEMP1,ASCL1

**Comment by risserlin** [comment]
I already added this one.  Forgot to close it.
