### ISSUE TITLE
Post analysis - over writing node with edges found

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#58]
For a network with edges for 5 different of the post analysis sets it only puts the edges to one post analysis edge instead of separate edges for each post analysis set. this occurs when computing for an entire set of sets. 

To get around this issue you can run post analysis separately for each set of interest. 

This was an issue in the cytoscape 3 version with the original post analysis code

**Comment by mikekucera** [comment]
Can you tell me how to reproduce this please?

**Comment by risserlin** [comment]
Sorry.  I don't know what this one is either.

**Comment by risserlin** [comment]
Using the known signature option with more than one geneset will put all the computed edges on the last geneset in the file.  For example, gmt file has set A and B.  All calculated edges (whether they are to A or B) will go from B.  
The resulting network will have 2 post analysis edges but only one of them will have edges.
