### ISSUE TITLE
Re-running post analysis should update existing hub node instead of creating a new one.

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#62]
Re-running the same post analysis (with some parameters tweaked) should update the existing hub node and edges rather than creating a new one.

(What to do about edges that no longer pass the cutoff? Delete them?)

**Comment by risserlin** [comment]
Don't delete edges that don't pass the current cut off or you can put in a question to the user "Some of the edges already in the network for this post analysis set currently don't pass the threshold you have set.  Do you want to delete them?"

**Comment by mikekucera** [comment]
I can't pop up a question dialog from a Task because it deadlocks the cytoscape UI. I will just have to leave the edges there.

**Comment by risserlin** [comment]
Not even using the observableTask?  We pop up a question for hierarchical clustering in the heatmap and for GREAT analysis using an observable task.

**Comment by mikekucera** [comment]
Thanks, I didn't know about ObservableTask.

**Comment by mikekucera** [comment]
Fixed in pa_merge
