### ISSUE TITLE
Deleting nodes and edges in an enrichment map causes null pointer on reload with row normalization

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#63]
If you delete a lot of nodes and edges in the enrichment map
save session
reload session
try and view node/edge expression row normalized it through a null pointer exception.

to get around this issue you can hide nodes and edges instead of deleting them.

**Comment by mikekucera** [comment]
I don't know how to reproduce this. It seems to work for me.

**Comment by mikekucera** [comment]
Can't reproduce.
