### ISSUE TITLE
Expression set Universe option is not correct

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#72]
Not sure if this is an issue farther up the chain (i.e when the expression set is loaded in) but the expression set unverse setting is not correct. 
In the below screen shot the Expression Set and intersection is exactly the same
![screen shot 2015-04-20 at 2 02 51 pm](https://cloud.githubusercontent.com/assets/3842763/7237032/a76dd860-e766-11e4-991a-0ae12cfa432d.png)

Expression set should be 6238 in the above example.

**Comment by mikekucera** [comment]
The ExpressionFileReaderTask filters out genes from the expression file that are not in the data set. So basically its already computing the intersection as it loads the expression file. I just have to store the number of expression genes in a new field.

**Comment by mikekucera** [comment]
The expression set size is never saved to the session file. (It saves the number of genes after its been filtered, so it saves the intersection size.) That means I can't fix this for old sessions.

**Comment by mikekucera** [comment]
I fixed this as best I could. It will still show a wrong value when loading a session file created with an older version of enrichment map.
