### ISSUE TITLE
There are multiple node/edge matches for name --> coming from delete edges

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#74]
Error message in console for edges that were deleted
There are multiple node/edge matches for name:UP_IN_MIR126KD_EXPRESSION (sig) BASIGIN INTERACTIONS%REACTOME%REACT_12560.3 []

This might be related to cytoscape node/edge deletion but what happens when a post analysis tries to create an edge that exists? what if that edge is actually deleted?

**Comment by mikekucera** [comment]
PA will create an edge if it does not already exist, if it does exist it will update the edge attributes. I think that console message is bogus, it says there are multiple edges when there are none. I think I should just get rid of the message.

**Comment by risserlin** [comment]
I think it is referring to deleted edges.(which are never really deleted)

**Comment by risserlin** [comment]
Ok.  Thanks.  I just unracked the buildNumber.properties file in the
version you merged.
I am working off of this version now.
