### ISSUE TITLE
What happens when the message "There are existing edges that did not pass the current cutoff value"

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#75]
![screen shot 2015-04-20 at 2 35 19 pm](https://cloud.githubusercontent.com/assets/3842763/7237612/9ed671e0-e76a-11e4-80cc-4d5b8761bd55.png)
What happens in the network when the above message is shown?  Please specify in the box what happens.

Can we add the choise - Delete edges that don't pass or keep edges that don't pass.

**Comment by mikekucera** [comment]
The existing edges that did not pass the new cutoff still get their attributes updated. I think I can store a list of existing edges that did not pass the cutoff and ask the user if they should be deleted in that dialog.
