### ISSUE TITLE
hypergeometric pvalue not updated after repeated post analysis run.

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#76]
related to issue #70.- tried this to get around the issue created by issue 70
When I calculate the mann whitney followed by the hypergeometric for the exact same post analysis set the hypergeometric pvalue remain -1 (but all the other hypergeometric values get filled in)
![screen shot 2015-04-20 at 2 39 39 pm](https://cloud.githubusercontent.com/assets/3842763/7237731/71144cf4-e76b-11e4-9fc1-a0221d24d1c3.png)

**Comment by mikekucera** [comment]
Hmmm, need to look into this.

**Comment by mikekucera** [comment]
Can't reproduce this. I think it was fixed along with #70.
