### ISSUE TITLE
Post analysis input panel doesn't refresh using the toggle after first switch

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#77]
From the Know signature view, select Signature discovery and the panel refreshes to show the Signature discovery panel.
If you then click on Known Signature again it doesn't show the known signature panel.
If you change the tab to Style tab,  for example, and come back to the post analysis linput panel it is on the right toggled option panel.

**Comment by mikekucera** [comment]
I was not able to reproduce this bug on my machine. However the code that toggles the panel did look suspicious. I rewrote it to something more reasonable. Hopefully that fixes it, if not then please reopen this issue.
