### ISSUE TITLE
Post analysis puts back deleted nodes if there is a post analysis edge to it.

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#78]
After delete a whole bunch of nodes
Calculating post analysis with the resulting smaller network computes post analysis edges to the deleted nodes as well and puts the deleted nodes back into the network.

This node/edge deletion issue keeps coming up with different cytoscape apps.  Not sure if they are working on fixing the issue from the cytoscape side.

**Comment by mikekucera** [comment]
What version of cytoscape did you try this with? I'm using cytoscape 3.3 development build and it appears to be working as expected.

**Comment by risserlin** [comment]
cytosacpe 3.2.1. I know they have done a lot of work on the deleted node/edge between 3.2 and 3.3 but likely people will be using 3.2 for a while yet.

**Comment by mikekucera** [comment]
Hi Ruth. Could you please provide me with steps to reproduce this. I've tried it on some smaller networks and on 3.2.1 and I can't reproduce it so far.

**Comment by risserlin** [comment]
I can't recreate this bug with the current version of EM in cytoscape 3.2.1.
