### ISSUE TITLE
How do you distinguish between dataset1 and dataset2 post analysis edges?

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#80]
When I computed a post analysis with dataset 1 followed by dataset2 I got a dialog saying some of the edges did not pass the given threshold.  These were new edges (of a different type).  There should be no overlap.

**Comment by mikekucera** [comment]
Can you please provide me with a session/gmt file so I can try to reproduce this.  Thanks.

**Comment by mikekucera** [comment]
I will make the edges dashed when I fix the visual style.
