### ISSUE TITLE
All edges go to the last signature hub that is created.

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/EnrichmentMapApp#85]
If you run post-analysis on multiple genesets, all the edges are connected to the last hub node that is created.

For example if I run PA on two gene-sets with 4 gene-sets in the enrichment map, then one of the signature gene sets has 8 edges and the other has zero. 

![screen shot 2015-04-24 at 11 14 35 am](https://cloud.githubusercontent.com/assets/5350528/7321995/4077c318-ea73-11e4-8456-812a27bd5675.png)

But if I run PA on each gene set one at a time, then each signature node has 4 edges.

![screen shot 2015-04-24 at 11 13 16 am](https://cloud.githubusercontent.com/assets/5350528/7322002/47a870ec-ea73-11e4-8e97-0ce2155c209e.png)

**Comment by risserlin** [comment]
same as #58
