### ISSUE TITLE
missing options from edge overlap calculation

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#87]
Currently only has Hypergeometric and Mann-whitney.

Missing:
Number of common genes
directed overlap
overlap X percent of EM gs
Overlap X percent of signature gs

**Comment by mikekucera** [comment]
What is "directed overlap"? It's not currently used in the filter box.
Is "Number of common genes" the same thing as "Overlap has at least X genes"?

**Comment by risserlin** [comment]
Number of common genes is the the same as Overlap has at least X genes.

Directed overlap should be overlap coeffecient - intersection/union
