### ISSUE TITLE
Need to get rid of all the column Auto annotate creates

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#92]
Get rid of all the boolean columns " __mclCluster Column Annotation Set Cloud #" created by autoannotate

I don't know why they are needed but need to figure out a way to transfer it to code.

**Comment by risserlin** [comment]
This is actually happening in Wordcloud and not in the autoannotate.  I can't find any references to it in the enrichment map but it might be important to wordcloud.

https://github.com/BaderLab/WordCloudPlugin/blob/f589f3bace44eb50af3ad4f91181a6737079f187/WordCloud/src/main/java/org/baderlab/wordcloud/internal/model/CloudParameters.java

**Comment by mikekucera** [comment]
Opened an enhancement request on WordCloud.
https://github.com/BaderLab/WordCloudPlugin/issues/51
