### ISSUE TITLE
Null pointer when I try to run post analysis

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#99]
with code from revision r5a6539d (on Windows, haven't tried it on my Mac with cytoscape 3.2.1) 
Create EM
Run post analysis with gmt file (containing one gs) with default selections [It works if I change the selection to Hypergeometric but does not work with mann whitney]

java.lang.NullPointerException
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.m
annWhitney(BuildDiseaseSignatureTask.java:587)
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.b
uildDiseaseSignature(BuildDiseaseSignatureTask.java:313)
        at org.baderlab.csplugins.enrichmentmap.task.BuildDiseaseSignatureTask.r
un(BuildDiseaseSignatureTask.java:664)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:321)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
It looks like its possible that one of the gene scores is null. I'm worried that the bug might be somewhere else and this is just a symptom. Do you have a session file I can reproduce this with?

**Comment by mikekucera** [comment]
This happens when there's a gene without a score in the Ranking object. Its very easy to trigger by just creating an enrichment map without providing a ranks file.

Its easy to fix by just defaulting the score to 0, is that safe to do? 

Should the mann-whitney cutoff be available if the user hasn't specified a ranks file? The current code would just always default to a p-value of 1.5.

**Comment by risserlin** [comment]
If there are no ranks available then an info message should come up to say Mann-whitney requires ranks. Upload ranks to use this test.  OR if there are no ranks don't have the option in the drop down box. 

Rank file missing some of the genes:
Will a rank of zero be ignored?  I would rather we don't exclude the gene but by default put it at the bottom of the rank list Or in the advanced settings maybe have this as a setting to either exclude unranked genes or include.

**Comment by mikekucera** [comment]
I think removing the mann-whitney option from the drop down without
explanation might be confusing. I will try to make the mann-whitney option
look disabled or pop up an info message.

A rank of zero is not ignored. I tried adding some extra zeros to the array
and it causes the result of the calculation to change.

I could add a checkbox "include unranked genes" right below the ranks combo
box. Should it be checked or unchecked by default?

**Comment by risserlin** [comment]
Include by default.  Thanks.

Is a zero a bottom rank?  It is important that the unranked genes get added to the bottom the ranks.

**Comment by mikekucera** [comment]
I'm not sure what a "bottom rank" is.
